/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2024 MediaTek Inc.
 */

// Here saves all MTK's smc call related to pKVM

// It is for el1 only
#define SMC_ID_MTK_PKVM_ADD_HVC 0xC400ff10

#define SMC_ID_MTK_PKVM_PMM_ASSIGN_BUFFER_V2     0xBB00FE00
#define SMC_ID_MTK_PKVM_PMM_UNASSIGN_BUFFER_V2   0xBB00FE01
#define SMC_ID_MTK_PKVM_PMM_DEFRAGMENT           0xBB00FE02

#define SMC_ID_MTK_PKVM_SMMU_SEC_REGION_UNMAP    0xBB00FFB0
#define SMC_ID_MTK_PKVM_SMMU_PAGE_TABLE_MERGE    0xBB00FFB1
#define SMC_ID_MTK_PKVM_CMDQ_SUBMIT_TASK         0xBB00FFB2
#define SMC_ID_MTK_PKVM_CMDQ_RES_RELEASE         0xBB00FFB3
#define SMC_ID_MTK_PKVM_CMDQ_CANCEL_TASK         0xBB00FFB4
#define SMC_ID_MTK_PKVM_CMDQ_PATH_RES_ALLOCATE   0xBB00FFB5
#define SMC_ID_MTK_PKVM_CMDQ_PATH_RES_RELEASE    0xBB00FFB6
#define SMC_ID_MTK_PKVM_CMDQ_PKVM_INIT           0xBB00FFB7
#define SMC_ID_MTK_PKVM_CMDQ_PKVM_DISABLE        0xBB00FFB8
#define SMC_ID_MTK_PKVM_CMDQ_GET_MEMORY          0xBB00FFB9
#define SMC_ID_MTK_PKVM_CMDQ_CAM_PREVIEW_SUPPORT 0xBB00FFBA
#define SMC_ID_MTK_PKVM_ISP_CHECKPIPE            0xBB00FFBB
#define SMC_ID_MTK_PKVM_ISP_FREE                 0xBB00FFBC
#define SMC_ID_MTK_PKVM_TMEM_REGION_PROTECT      0xBB00FFC7
#define SMC_ID_MTK_PKVM_TMEM_REGION_UNPROTECT    0xBB00FFC8
#define SMC_ID_MTK_PKVM_TMEM_PAGE_PROTECT        0xBB00FFC9
#define SMC_ID_MTK_PKVM_TMEM_PAGE_UNPROTECT      0xBB00FFCA
#define SMC_ID_MTK_PKVM_SMMU_SEC_MAP             0xBB00FFCB
#define SMC_ID_MTK_PKVM_SMMU_SEC_UNMAP           0xBB00FFCC
#define SMC_ID_MTK_PKVM_SMMU_MEM_SHARE           0xBB00FFCD
#define SMC_ID_MTK_PKVM_SMMU_DEBUG_DUMP          0xBB00FFCE
#define SMC_ID_MTK_PKVM_SMMU_SEC_REGION_MAP      0xBB00FFCF

// smc result code
#define SMC_RET_MTK_PKVM_SMC_HANDLER_DUPLICATED_ID -1
#define SMC_RET_MTK_PKVM_SMC_HANDLER_OUT_OF_HVC_COUNT -2

#define MTK_SIP_HYP_SECIO_WRITE 0xC2000812
#define MTK_SIP_HYP_SECIO_READ  0xC2000813

#define FFA_MIN_FUNC_NUM 0x60
#define FFA_MAX_FUNC_NUM 0xFF
