# SPDX-License-Identifier: GPL-2.0

# ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include/mt-plat/
# ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/gpu/mediatek/gpufreq/
# ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/power_throttling/
# ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/sched/core_ctl/

# ifeq ($(CONFIG_MTK_GCOV_KERNEL),y)
# GCOV_PROFILE_mtk_bp_thl.o := y
# endif

# obj-$(CONFIG_MTK_MD_POWER_THROTTLING) += mtk_md_power_throttling.o

