# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include/
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/hwccf/include
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/clk/mediatek
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/vmm/inc
# ifneq ($(wildcard $(src)/mtk-vmm-notifier-mt6991.c),)
# obj-$(CONFIG_MTK_VMM_NOTIFIER_MT6991) += mtk-vmm-notifier-mt6991.o
# endif
# ifneq ($(wildcard $(src)/mtk-vmm-notifier-mt6993.c),)
# obj-$(CONFIG_MTK_VMM_NOTIFIER_MT6993) += mtk-vmm-notifier-mt6993.o
# endif
# ifneq ($(wildcard $(src)/mtk-vmm-notifier.c),)
# obj-$(CONFIG_MTK_VMM_NOTIFIER) += mtk-vmm-notifier.o
# endif
