load("//build/bazel_mgk_rules:mgk_ddk_ko.bzl", "define_mgk_ddk_ko")
load("//build/kernel/kleaf:kernel.bzl", "ddk_headers")
load("@mgk_info//:kernel_version.bzl", "kernel_version",)
load("@mgk_info//:dict.bzl", "DEFCONFIG_OVERLAYS",)

package(
    default_visibility = [
        "//visibility:public",
    ],
)

filegroup(
    name = "ddk_kconfigs",
    srcs = glob([
        "**/Kconfig",
    ]),
)

filegroup(
    name = "srcs",
    srcs = glob([
        "**/*.c",
        "**/*.h",
    ]),
)

# to export headers for other modules to use
ddk_headers(
    name = "headers",
    hdrs = [
        "mtk_vcodec_util.h",
        "mtk-v4l2-controls.h",
        "vcodec_ipi_msg.h",
    ],
    includes = ["."],
)

define_mgk_ddk_ko(
    name = "mtk-vcodec-common",
    srcs = [],
    conditional_srcs = {
        "CONFIG_DEVICE_MODULES_VIDEO_MEDIATEK_VCODEC": {
            True: glob([
                "mtk_vcodec_util.c",
                "mtk_vcodec_intr.c",
                "mtk_vcodec_fence.c",
                "*.h",
            ]),
        },
    },
    hdrs = [
        "mtk_vcodec_util.h",
        "mtk-v4l2-controls.h",
        "vcodec_ipi_msg.h",
    ] + [
        "//kernel_device_modules-{}/drivers/misc/mediatek/slbc:headers".format(kernel_version),
        "//kernel_device_modules-{}/drivers/media/platform/mtk-vcu:headers".format(kernel_version),
    ],
    includes = [
        ".",
    ],
    header_deps = [
        "//kernel_device_modules-{}/drivers/misc/mediatek/videogo:headers".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/sched:cpufreq_sugov_ext_headers".format(kernel_version),
    ],
    ko_deps = [
        "//kernel_device_modules-{}/drivers/misc/mediatek/sched:cpufreq_sugov_ext".format(kernel_version),
        "//kernel_device_modules-{}/drivers/dma-buf/heaps:system_heap".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/sched:scheduler".format(kernel_version),
    ],
    copts = [
        "-Werror",
        "-I$(srctree)/kernel/",
        "-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include/mt-plat",
    ],
)

define_mgk_ddk_ko(
    name = "mtk-vcodec-trace",
    srcs = [],
    conditional_srcs = {
        "CONFIG_DEVICE_MODULES_VIDEO_MEDIATEK_VCODEC": {
            True: glob([
                "mtk_vcodec_trace.c",
                "mtk_vcodec_trace.h",
            ]),
        },
    },
    includes = [
        ".",
    ],
    header_deps = [
    ],
    ko_deps = [
        "//kernel_device_modules-{}/drivers/media/platform/mtk-vcodec:mtk-vcodec-common".format(kernel_version),
    ],
    copts = [
        "-Werror",
        "-I$(srctree)/kernel/",
        "-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include/mt-plat",
    ],
)

define_mgk_ddk_ko(
    name = "mtk-vcodec-dec",
    srcs = [],
    conditional_srcs = {
        "CONFIG_DEVICE_MODULES_VIDEO_MEDIATEK_VCODEC": {
            True: glob([
                "mtk_vcodec_dec_drv.c",
                "mtk_vcodec_dec.c",
                "mtk_vcodec_dec_pm.c",
                "mtk_vcodec_dec_slc.c",
                "vdec_drv_if.c",
                "vdvfs_vqos/mtk_vcodec_dec_pm_plat.c",
                "vdvfs_vqos/vcodec_dvfs.c",
                "*.h"
            ]),
        },
        "CONFIG_VIDEO_MEDIATEK_VCU": {
            True: glob([
                "vdec/vdec_common_if.c",
                "vdec/vdec_vcu_if.c",
            ]),
        },
        "CONFIG_MTK_TINYSYS_VCP_SUPPORT": {
            True: glob([
                "vdec/vdec_vcp_if.c",
            ]),
        },
    },
    includes = [
        ".",
    ],
    header_deps = [
        "//kernel_device_modules-{}/drivers/iommu/arm/arm-smmu-v3:smmu_public_headers".format(kernel_version),
        "//kernel_device_modules-{}/drivers/media/platform/mtk-vcu:headers".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/iommu:iommu_misc_headers".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/mtk-interconnect:mtk_interconnect".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/sched:cpufreq_sugov_ext_headers".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/vcp/rv_v2:vcp_status_v2_headers".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/vcp/include:vcp_public_headers".format(kernel_version),
        "//kernel_device_modules-{}/drivers/thermal/mediatek:thermal_headers".format(kernel_version),
    ],
    ko_deps = [
        "//kernel_device_modules-{}/drivers/dma-buf/heaps:mtk_sec_heap".format(kernel_version),
        "//kernel_device_modules-{}/drivers/dma-buf/heaps:system_heap".format(kernel_version),
        "//kernel_device_modules-{}/drivers/media/platform/mtk-vcodec:mtk-vcodec-common".format(kernel_version),
        "//kernel_device_modules-{}/drivers/memory/mediatek:emi".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/cpufreq_lite:cpudvfs".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/iommu:iommu_debug".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/iommu:iommu_gz".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/irq_monitor:irq_monitor".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/mmdvfs:mtk-mmdvfs-debug".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/mtk-interconnect:mtk-icc-core".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/sched:cpufreq_sugov_ext".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/slbc:mtk_slbc".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/smi:mtk-smi-dbg".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/vcp/rv_v2:vcp_status_v2".format(kernel_version),
        "//kernel_device_modules-{}/drivers/soc/mediatek:mtk_tinysys_ipi".format(kernel_version),
        "//kernel_device_modules-{}/drivers/thermal/mediatek:thermal_interface".format(kernel_version),
    ] + ([
        "//kernel_device_modules-{}/drivers/soc/mediatek:mtk-mmdvfs-v3".format(kernel_version),
    ] if "entry_level.config" not in DEFCONFIG_OVERLAYS else []),
    copts = [
        "-Werror",
        "-I$(srctree)/kernel/",
        "-I$(DEVICE_MODULES_PATH)/include/linux/soc/mediatek",
        "-I$(DEVICE_MODULES_PATH)/include/soc/mediatek",
        "-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include/mt-plat",
    ],
)

define_mgk_ddk_ko(
    name = "mtk-vcodec-enc",
    srcs = [],
    conditional_srcs = {
        "CONFIG_DEVICE_MODULES_VIDEO_MEDIATEK_VCODEC": {
            True: glob([
                "mtk_vcodec_enc_drv.c",
                "mtk_vcodec_enc.c",
                "mtk_vcodec_enc_pm.c",
                "venc_drv_if.c",
                "vdvfs_vqos/mtk_vcodec_enc_pm_plat.c",
                "vdvfs_vqos/vcodec_dvfs.c",
                "*.h"
            ]),
        },
        "CONFIG_VIDEO_MEDIATEK_VCU": {
            True: glob([
                "venc/venc_common_if.c",
                "venc/venc_vcu_if.c",
            ]),
        },
        "CONFIG_MTK_TINYSYS_VCP_SUPPORT": {
            True: glob([
                "venc/venc_vcp_if.c",
            ]),
        },
    },
    includes = [
        ".",
    ],
    header_deps = [
        "//kernel_device_modules-{}/drivers/iommu/arm/arm-smmu-v3:smmu_public_headers".format(kernel_version),
        "//kernel_device_modules-{}/drivers/media/platform/mtk-vcu:headers".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/iommu:iommu_misc_headers".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/mtk-interconnect:mtk_interconnect".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/sched:cpufreq_sugov_ext_headers".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/slbc:headers".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/vcp/rv_v2:vcp_status_v2_headers".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/vcp/include:vcp_public_headers".format(kernel_version),
        "//kernel_device_modules-{}/drivers/thermal/mediatek:thermal_headers".format(kernel_version),
    ],
    ko_deps = [
        "//kernel_device_modules-{}/drivers/dma-buf/heaps:mtk_sec_heap".format(kernel_version),
        "//kernel_device_modules-{}/drivers/dma-buf/heaps:system_heap".format(kernel_version),
        "//kernel_device_modules-{}/drivers/media/platform/mtk-vcodec:mtk-vcodec-common".format(kernel_version),
        "//kernel_device_modules-{}/drivers/memory/mediatek:emi".format(kernel_version),
        "//kernel_device_modules-{}/drivers/memory/mediatek:emi-slb".format(kernel_version),
        "//kernel_device_modules-{}/drivers/memory:mtk-smi".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/cpufreq_lite:cpudvfs".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/iommu:iommu_debug".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/iommu:iommu_gz".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/irq_monitor:irq_monitor".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/mtk-interconnect:mtk-icc-core".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/sched:cpufreq_sugov_ext".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/slbc:mtk_slbc".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/smi:mtk-smi-dbg".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/vcp/rv_v2:vcp_status_v2".format(kernel_version),
        "//kernel_device_modules-{}/drivers/soc/mediatek:mtk_tinysys_ipi".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/task_turbo:vip_engine".format(kernel_version),
        "//kernel_device_modules-{}/drivers/thermal/mediatek:thermal_interface".format(kernel_version),
    ] + ([
        "//kernel_device_modules-{}/drivers/soc/mediatek:mtk-mmdvfs-v3".format(kernel_version),
    ] if "entry_level.config" not in DEFCONFIG_OVERLAYS else []),
    copts = [
        "-Werror",
        "-I$(srctree)/kernel/",
        "-I$(DEVICE_MODULES_PATH)/include/linux/soc/mediatek",
        "-I$(DEVICE_MODULES_PATH)/include/soc/mediatek",
        "-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include/mt-plat",
    ],
)
