#
# Makefile for ise_lpm components
#

ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/tinysys_scmi/
ccflags-y += -I$(DEVICE_MODULES_PATH)/include/linux/soc/mediatek/
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include/mt-plat/

#obj-$(CONFIG_MTK_ISE_LPM_SUPPORT) += ise_lpm.o
#obj-$(CONFIG_MTK_ISE_LPM_SUPPORT) += ise_lpm_v2.o


