ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/scp/include
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/sensor/2.0/sensorhub
obj-m += ts_scp_common.o

ts_scp_common-y := \
			touch_ipi_comm.o \
			touch_comm.o \
			tiny_crc8.o \
			ts_scp_core.o

