ccflags-y += \
        -I$(srctree)/include/ \
        -I$(srctree)/kernel/ \
        -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/sched/ \
        -I$(DEVICE_MODULES_PATH)/drivers/gpu/drm/mediatek/mediatek_v2/ \
        -I$(DEVICE_MODULES_PATH)/drivers/gpu/mediatek/ged/include \
        -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/performance/fpsgo_v8/base/include/ \
        -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/performance/sbe/include/ \

#obj-$(CONFIG_MTK_SBE) += mtk_sbe.o

#mtk_sbe-y += src/sbe_main.o
#mtk_sbe-y += src/sbe_sysfs.o
#mtk_sbe-y += src/sbe_base.o
#mtk_sbe-y += src/sbe_cpu_ctrl.o
