load("//build/bazel_mgk_rules:mgk_ddk_ko.bzl", "define_mgk_ddk_ko")
load("//build/kernel/kleaf:kernel.bzl", "ddk_headers")

package(
    default_visibility = [
        "//visibility:public",
    ],
)

define_mgk_ddk_ko(
    name = "mtk_boot_common",
    srcs = [
        "mtk_boot_common.c",
    ],
    hdrs = glob(["**/*.h"]),
    includes = ["."],
    copts = [
        "-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include/",
    ],
    out = "mtk_boot_common.ko",
)

ddk_headers(
   name = "headers",
   hdrs = glob(["**/*.h"]),
   includes = ["."],
   linux_includes = [
       "include",
   ],
)

filegroup(
    name = "srcs",
    srcs = glob([
        "**/Makefile",
        "**/*.c",
        "**/*.h",
        ]),
)
