/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (C) 2024 MediaTek Inc.
 * Author: Light Hsieh <light.hsieh@mediatek.com>
 *
 */

#ifndef __PINCTRL_MTK_MT6993_H
#define __PINCTRL_MTK_MT6993_H

#include "pinctrl-paris.h"

static const struct mtk_pin_desc mtk_pins_mt6993[] = {
	MTK_PIN_NODRV(
		0, "GPIO0",
		MTK_EINT_FUNCTION(0, 0),
		MTK_FUNCTION(0, "GPIO0"),
		MTK_FUNCTION(1, "SRCLKENA1"),
		MTK_FUNCTION(3, "DSI3_ERR_FLG"),
		MTK_FUNCTION(5, "KPCOL2"),
		MTK_FUNCTION(6, "TP_GPIO8_AO"),
		MTK_FUNCTION(7, "DBG_MON_A8"),
		MTK_FUNCTION(8, "IOBIST0")
	),
	MTK_PIN_NODRV(
		1, "GPIO1",
		MTK_EINT_FUNCTION(0, 1),
		MTK_FUNCTION(0, "GPIO1"),
		MTK_FUNCTION(1, "CONN_TCXOENA_REQ"),
		MTK_FUNCTION(3, "GPS_PPS1"),
		MTK_FUNCTION(5, "KPROW2"),
		MTK_FUNCTION(7, "DBG_MON_A7"),
		MTK_FUNCTION(8, "IOBIST1")
	),
	MTK_PIN_NODRV(
		2, "GPIO2",
		MTK_EINT_FUNCTION(0, 2),
		MTK_FUNCTION(0, "GPIO2"),
		MTK_FUNCTION(1, "DSI_HSYNC"),
		MTK_FUNCTION(2, "LCM2_RST"),
		MTK_FUNCTION(3, "I2SOUT5_BCK"),
		MTK_FUNCTION(4, "I2SIN5_BCK"),
		MTK_FUNCTION(5, "PCIE_CLKREQN_1P"),
		MTK_FUNCTION(6, "TP_GPIO14_AO"),
		MTK_FUNCTION(7, "DBG_MON_B2"),
		MTK_FUNCTION(8, "IOBIST2")
	),
	MTK_PIN_NODRV(
		3, "GPIO3",
		MTK_EINT_FUNCTION(0, 3),
		MTK_FUNCTION(0, "GPIO3"),
		MTK_FUNCTION(1, "DSI1_HSYNC"),
		MTK_FUNCTION(2, "DSI2_TE"),
		MTK_FUNCTION(3, "I2SOUT5_LRCK"),
		MTK_FUNCTION(4, "I2SIN5_LRCK"),
		MTK_FUNCTION(5, "PCIE_WAKEN_1P"),
		MTK_FUNCTION(6, "TP_GPIO15_AO"),
		MTK_FUNCTION(7, "DBG_MON_B3"),
		MTK_FUNCTION(8, "IOBIST3")
	),
	MTK_PIN_NODRV(
		4, "GPIO4",
		MTK_EINT_FUNCTION(0, 4),
		MTK_FUNCTION(0, "GPIO4"),
		MTK_FUNCTION(3, "I2SOUT5_DATA0"),
		MTK_FUNCTION(5, "PCIE_PERSTN_1P"),
		MTK_FUNCTION(8, "IOBIST4")
	),
	MTK_PIN_NODRV(
		5, "GPIO5",
		MTK_EINT_FUNCTION(0, 5),
		MTK_FUNCTION(0, "GPIO5"),
		MTK_FUNCTION(2, "SPI7_A_CLK"),
		MTK_FUNCTION(3, "I2SOUT5_DATA1"),
		MTK_FUNCTION(8, "IOBIST5")
	),
	MTK_PIN_NODRV(
		6, "GPIO6",
		MTK_EINT_FUNCTION(0, 6),
		MTK_FUNCTION(0, "GPIO6"),
		MTK_FUNCTION(1, "MD_GPS_BLANK"),
		MTK_FUNCTION(2, "SPI7_A_CSB"),
		MTK_FUNCTION(3, "AUD_DAC_26M_CLK"),
		MTK_FUNCTION(8, "IOBIST6")
	),
	MTK_PIN_NODRV(
		7, "GPIO7",
		MTK_EINT_FUNCTION(0, 7),
		MTK_FUNCTION(0, "GPIO7"),
		MTK_FUNCTION(1, "DMIC2_CLK"),
		MTK_FUNCTION(2, "SPI7_A_MO"),
		MTK_FUNCTION(3, "GPS_PPS0"),
		MTK_FUNCTION(8, "IOBIST7")
	),
	MTK_PIN_NODRV(
		8, "GPIO8",
		MTK_EINT_FUNCTION(0, 8),
		MTK_FUNCTION(0, "GPIO8"),
		MTK_FUNCTION(1, "DMIC2_DAT"),
		MTK_FUNCTION(2, "SPI7_A_MI"),
		MTK_FUNCTION(3, "GPS_PPS1"),
		MTK_FUNCTION(8, "IOBIST8")
	),
	MTK_PIN_NODRV(
		9, "GPIO9",
		MTK_EINT_FUNCTION(0, 9),
		MTK_FUNCTION(0, "GPIO9"),
		MTK_FUNCTION(1, "CONN_TCXOENA_REQ"),
		MTK_FUNCTION(3, "I2SIN1_LRCK"),
		MTK_FUNCTION(6, "RG_TSFDC_LDO_REFSEL0"),
		MTK_FUNCTION(8, "IOBIST9")
	),
	MTK_PIN_NODRV(
		10, "GPIO10",
		MTK_EINT_FUNCTION(0, 10),
		MTK_FUNCTION(0, "GPIO10"),
		MTK_FUNCTION(1, "LCM1_RST"),
		MTK_FUNCTION(3, "I2SOUT1_DO"),
		MTK_FUNCTION(6, "RG_TSFDC_LDO_REFSEL1"),
		MTK_FUNCTION(8, "IOBIST10")
	),
	MTK_PIN_NODRV(
		11, "GPIO11",
		MTK_EINT_FUNCTION(0, 11),
		MTK_FUNCTION(0, "GPIO11"),
		MTK_FUNCTION(1, "DSI1_TE"),
		MTK_FUNCTION(6, "TSFDC_BG_COMP"),
		MTK_FUNCTION(7, "DBG_MON_B11"),
		MTK_FUNCTION(8, "IOBIST11")
	),
	MTK_PIN_NODRV(
		12, "GPIO12",
		MTK_EINT_FUNCTION(0, 12),
		MTK_FUNCTION(0, "GPIO12"),
		MTK_FUNCTION(1, "DMIC1_CLK"),
		MTK_FUNCTION(2, "SPI0_HOLD"),
		MTK_FUNCTION(3, "DSI_HSYNC"),
		MTK_FUNCTION(4, "SCP_DMIC1_CLK"),
		MTK_FUNCTION(6, "TP_GPIO3_AO"),
		MTK_FUNCTION(7, "DBG_MON_A9"),
		MTK_FUNCTION(8, "IOBIST12")
	),
	MTK_PIN_NODRV(
		13, "GPIO13",
		MTK_EINT_FUNCTION(0, 13),
		MTK_FUNCTION(0, "GPIO13"),
		MTK_FUNCTION(1, "DMIC1_DAT"),
		MTK_FUNCTION(3, "DSI_ERR_FLG"),
		MTK_FUNCTION(4, "SCP_DMIC1_DAT"),
		MTK_FUNCTION(6, "TP_GPIO4_AO"),
		MTK_FUNCTION(7, "DBG_MON_A28"),
		MTK_FUNCTION(8, "IOBIST13")
	),
	MTK_PIN_NODRV(
		14, "GPIO14",
		MTK_EINT_FUNCTION(0, 14),
		MTK_FUNCTION(0, "GPIO14"),
		MTK_FUNCTION(1, "SRCLKENA2"),
		MTK_FUNCTION(3, "SPI4_B_CLK"),
		MTK_FUNCTION(4, "SPMI_M_TRIG_FLAG"),
		MTK_FUNCTION(5, "MBISTREADEN_TRIGGER"),
		MTK_FUNCTION(8, "IOBIST14")
	),
	MTK_PIN_NODRV(
		15, "GPIO15",
		MTK_EINT_FUNCTION(0, 15),
		MTK_FUNCTION(0, "GPIO15"),
		MTK_FUNCTION(3, "UCTS0"),
		MTK_FUNCTION(5, "I2SIN3_BCK"),
		MTK_FUNCTION(7, "DBG_MON_A1"),
		MTK_FUNCTION(8, "IOBIST15")
	),
	MTK_PIN_NODRV(
		16, "GPIO16",
		MTK_EINT_FUNCTION(0, 16),
		MTK_FUNCTION(0, "GPIO16"),
		MTK_FUNCTION(2, "LCM1_RST"),
		MTK_FUNCTION(3, "URTS0"),
		MTK_FUNCTION(4, "DP_TX_HPD"),
		MTK_FUNCTION(5, "I2SIN3_LRCK"),
		MTK_FUNCTION(6, "TP_GPIO10_AO"),
		MTK_FUNCTION(7, "DBG_MON_A29"),
		MTK_FUNCTION(8, "IOBIST16")
	),
	MTK_PIN_NODRV(
		17, "GPIO17",
		MTK_EINT_FUNCTION(0, 17),
		MTK_FUNCTION(0, "GPIO17"),
		MTK_FUNCTION(1, "MD_INT0"),
		MTK_FUNCTION(2, "DSI1_TE"),
		MTK_FUNCTION(3, "UCTS1"),
		MTK_FUNCTION(4, "DP_OC_EN"),
		MTK_FUNCTION(5, "I2SIN3_DI"),
		MTK_FUNCTION(6, "TP_GPIO11_AO"),
		MTK_FUNCTION(7, "DBG_MON_A30"),
		MTK_FUNCTION(8, "IOBIST17")
	),
	MTK_PIN_NODRV(
		18, "GPIO18",
		MTK_EINT_FUNCTION(0, 18),
		MTK_FUNCTION(0, "GPIO18"),
		MTK_FUNCTION(1, "SRCLKENAI0"),
		MTK_FUNCTION(2, "DMIC1_CLK"),
		MTK_FUNCTION(3, "URTS1"),
		MTK_FUNCTION(4, "DP_RAUX_SBU1"),
		MTK_FUNCTION(6, "TP_GPIO12_AO"),
		MTK_FUNCTION(7, "DBG_MON_A31"),
		MTK_FUNCTION(8, "IOBIST18")
	),
	MTK_PIN_NODRV(
		19, "GPIO19",
		MTK_EINT_FUNCTION(0, 19),
		MTK_FUNCTION(0, "GPIO19"),
		MTK_FUNCTION(1, "SRCLKENAI1"),
		MTK_FUNCTION(2, "DMIC1_DAT"),
		MTK_FUNCTION(4, "DP_RAUX_SBU2"),
		MTK_FUNCTION(5, "I2SOUT3_DO"),
		MTK_FUNCTION(6, "TP_GPIO13_AO"),
		MTK_FUNCTION(8, "IOBIST19")
	),
	MTK_PIN_NODRV(
		20, "GPIO20",
		MTK_EINT_FUNCTION(0, 20),
		MTK_FUNCTION(0, "GPIO20"),
		MTK_FUNCTION(1, "IDDIG"),
		MTK_FUNCTION(2, "GPS_PPS1"),
		MTK_FUNCTION(3, "SPI4_B_CSB"),
		MTK_FUNCTION(5, "MBISTWRITEEN_TRIGGER"),
		MTK_FUNCTION(8, "IOBIST20")
	),
	MTK_PIN_NODRV(
		21, "GPIO21",
		MTK_EINT_FUNCTION(0, 21),
		MTK_FUNCTION(0, "GPIO21"),
		MTK_FUNCTION(1, "BPI_BUS11"),
		MTK_FUNCTION(3, "GPS_L1_ELNA_EN"),
		MTK_FUNCTION(6, "EMI_INFRA_RV33_JTAG_TRSTN_V"),
		MTK_FUNCTION(8, "IOBIST21")
	),
	MTK_PIN_NODRV(
		22, "GPIO22",
		MTK_EINT_FUNCTION(0, 22),
		MTK_FUNCTION(0, "GPIO22"),
		MTK_FUNCTION(1, "BPI_BUS12"),
		MTK_FUNCTION(3, "GPS_L5_ELNA_EN"),
		MTK_FUNCTION(5, "TP_URTS1_VCORE"),
		MTK_FUNCTION(6, "EMI_INFRA_RV33_JTAG_TCK_VCO"),
		MTK_FUNCTION(8, "IOBIST22")
	),
	MTK_PIN_NODRV(
		23, "GPIO23",
		MTK_EINT_FUNCTION(0, 23),
		MTK_FUNCTION(0, "GPIO23"),
		MTK_FUNCTION(1, "BPI_BUS13"),
		MTK_FUNCTION(3, "VBUSVALID"),
		MTK_FUNCTION(5, "TP_UCTS1_VCORE"),
		MTK_FUNCTION(6, "EMI_INFRA_RV33_JTAG_TMS_VCO"),
		MTK_FUNCTION(8, "IOBIST23")
	),
	MTK_PIN_NODRV(
		24, "GPIO24",
		MTK_EINT_FUNCTION(0, 24),
		MTK_FUNCTION(0, "GPIO24"),
		MTK_FUNCTION(1, "BPI_BUS14"),
		MTK_FUNCTION(2, "SPI2_A_CLK"),
		MTK_FUNCTION(3, "UCTS4"),
		MTK_FUNCTION(5, "TP_UTXD1_VCORE"),
		MTK_FUNCTION(6, "EMI_INFRA_RV33_JTAG_TDO_VCO"),
		MTK_FUNCTION(8, "IOBIST24")
	),
	MTK_PIN_NODRV(
		25, "GPIO25",
		MTK_EINT_FUNCTION(0, 25),
		MTK_FUNCTION(0, "GPIO25"),
		MTK_FUNCTION(1, "BPI_BUS15"),
		MTK_FUNCTION(2, "SPI2_A_CSB"),
		MTK_FUNCTION(3, "URTS4"),
		MTK_FUNCTION(4, "IDDIG"),
		MTK_FUNCTION(5, "TP_URXD1_VCORE"),
		MTK_FUNCTION(6, "EMI_INFRA_RV33_JTAG_TDI_VCO"),
		MTK_FUNCTION(8, "IOBIST25")
	),
	MTK_PIN_NODRV(
		26, "GPIO26",
		MTK_EINT_FUNCTION(0, 26),
		MTK_FUNCTION(0, "GPIO26"),
		MTK_FUNCTION(1, "BPI_BUS16"),
		MTK_FUNCTION(2, "SPI2_A_MO"),
		MTK_FUNCTION(3, "UTXD4"),
		MTK_FUNCTION(4, "USB_DRVVBUS"),
		MTK_FUNCTION(5, "TP_GPIO9_AO"),
		MTK_FUNCTION(6, "DSI3_HSYNC"),
		MTK_FUNCTION(8, "IOBIST26")
	),
	MTK_PIN_NODRV(
		27, "GPIO27",
		MTK_EINT_FUNCTION(0, 27),
		MTK_FUNCTION(0, "GPIO27"),
		MTK_FUNCTION(1, "BPI_BUS17"),
		MTK_FUNCTION(2, "SPI2_A_MI"),
		MTK_FUNCTION(3, "URXD4"),
		MTK_FUNCTION(4, "SPMI_P_TRIG_FLAG"),
		MTK_FUNCTION(8, "IOBIST27")
	),
	MTK_PIN_NODRV(
		28, "GPIO28",
		MTK_EINT_FUNCTION(0, 28),
		MTK_FUNCTION(0, "GPIO28"),
		MTK_FUNCTION(1, "BPI_BUS18"),
		MTK_FUNCTION(6, "SPM_JTAG_TCK_VLP"),
		MTK_FUNCTION(7, "JTCK_SEL1"),
		MTK_FUNCTION(8, "IOBIST28")
	),
	MTK_PIN_NODRV(
		29, "GPIO29",
		MTK_EINT_FUNCTION(0, 29),
		MTK_FUNCTION(0, "GPIO29"),
		MTK_FUNCTION(1, "BPI_BUS19"),
		MTK_FUNCTION(6, "SPM_JTAG_TMS_VLP"),
		MTK_FUNCTION(7, "JTMS_SEL1"),
		MTK_FUNCTION(8, "IOBIST29")
	),
	MTK_PIN_NODRV(
		30, "GPIO30",
		MTK_EINT_FUNCTION(0, 30),
		MTK_FUNCTION(0, "GPIO30"),
		MTK_FUNCTION(1, "BPI_BUS20"),
		MTK_FUNCTION(6, "SPM_JTAG_TDO_VLP"),
		MTK_FUNCTION(7, "JTDO_SEL1"),
		MTK_FUNCTION(8, "IOBIST30")
	),
	MTK_PIN_NODRV(
		31, "GPIO31",
		MTK_EINT_FUNCTION(0, 31),
		MTK_FUNCTION(0, "GPIO31"),
		MTK_FUNCTION(1, "BPI_BUS21"),
		MTK_FUNCTION(6, "SPM_JTAG_TDI_VLP"),
		MTK_FUNCTION(7, "JTDI_SEL1"),
		MTK_FUNCTION(8, "IOBIST31")
	),
	MTK_PIN_NODRV(
		32, "GPIO32",
		MTK_EINT_FUNCTION(0, 32),
		MTK_FUNCTION(0, "GPIO32"),
		MTK_FUNCTION(1, "HFRP_JTAG0_TCK"),
		MTK_FUNCTION(2, "DP_TX_HPD"),
		MTK_FUNCTION(3, "SSPM_JTAG_TCK_VLP"),
		MTK_FUNCTION(4, "ADSP_JTAG0_TCK"),
		MTK_FUNCTION(5, "SCP_JTAG0_TCK_VLP"),
		MTK_FUNCTION(6, "SPU0_TCK"),
		MTK_FUNCTION(7, "MDSWD_MCU_SWCK"),
		MTK_FUNCTION(8, "IOBIST32")
	),
	MTK_PIN_NODRV(
		33, "GPIO33",
		MTK_EINT_FUNCTION(0, 33),
		MTK_FUNCTION(0, "GPIO33"),
		MTK_FUNCTION(1, "HFRP_JTAG0_TRSTN"),
		MTK_FUNCTION(2, "DP_OC_EN"),
		MTK_FUNCTION(3, "SSPM_JTAG_TRSTN_VLP"),
		MTK_FUNCTION(4, "ADSP_JTAG0_TRSTN"),
		MTK_FUNCTION(5, "SCP_JTAG0_TRSTN_VLP"),
		MTK_FUNCTION(6, "SPU0_NTRST"),
		MTK_FUNCTION(8, "IOBIST33")
	),
	MTK_PIN_NODRV(
		34, "GPIO34",
		MTK_EINT_FUNCTION(0, 34),
		MTK_FUNCTION(0, "GPIO34"),
		MTK_FUNCTION(1, "HFRP_JTAG0_TDI"),
		MTK_FUNCTION(2, "DP_RAUX_SBU1"),
		MTK_FUNCTION(3, "SSPM_JTAG_TDI_VLP"),
		MTK_FUNCTION(4, "ADSP_JTAG0_TDI"),
		MTK_FUNCTION(5, "SCP_JTAG0_TDI_VLP"),
		MTK_FUNCTION(6, "SPU0_TDI"),
		MTK_FUNCTION(8, "IOBIST34")
	),
	MTK_PIN_NODRV(
		35, "GPIO35",
		MTK_EINT_FUNCTION(0, 35),
		MTK_FUNCTION(0, "GPIO35"),
		MTK_FUNCTION(1, "HFRP_JTAG0_TDO"),
		MTK_FUNCTION(2, "DP_RAUX_SBU2"),
		MTK_FUNCTION(3, "SSPM_JTAG_TDO_VLP"),
		MTK_FUNCTION(4, "ADSP_JTAG0_TDO"),
		MTK_FUNCTION(5, "SCP_JTAG0_TDO_VLP"),
		MTK_FUNCTION(6, "SPU0_TDO"),
		MTK_FUNCTION(8, "IOBIST35")
	),
	MTK_PIN_NODRV(
		36, "GPIO36",
		MTK_EINT_FUNCTION(0, 36),
		MTK_FUNCTION(0, "GPIO36"),
		MTK_FUNCTION(1, "HFRP_JTAG0_TMS"),
		MTK_FUNCTION(2, "DISP_PWM1"),
		MTK_FUNCTION(3, "SSPM_JTAG_TMS_VLP"),
		MTK_FUNCTION(4, "ADSP_JTAG0_TMS"),
		MTK_FUNCTION(5, "SCP_JTAG0_TMS_VLP"),
		MTK_FUNCTION(6, "SPU0_TMS"),
		MTK_FUNCTION(7, "MDSWD_MCU_SWD"),
		MTK_FUNCTION(8, "IOBIST36")
	),
	MTK_PIN_NODRV(
		37, "GPIO37",
		MTK_EINT_FUNCTION(0, 37),
		MTK_FUNCTION(0, "GPIO37"),
		MTK_FUNCTION(1, "MD_INT3"),
		MTK_FUNCTION(2, "LCM3_RST"),
		MTK_FUNCTION(7, "MDSWD_DSP0_SWCK"),
		MTK_FUNCTION(8, "IOBIST37")
	),
	MTK_PIN_NODRV(
		38, "GPIO38",
		MTK_EINT_FUNCTION(0, 38),
		MTK_FUNCTION(0, "GPIO38"),
		MTK_FUNCTION(1, "MD_INT4"),
		MTK_FUNCTION(2, "DSI3_TE"),
		MTK_FUNCTION(7, "MDSWD_DSP0_SWD"),
		MTK_FUNCTION(8, "IOBIST38")
	),
	MTK_PIN_NODRV(
		39, "GPIO39",
		MTK_EINT_FUNCTION(0, 39),
		MTK_FUNCTION(0, "GPIO39"),
		MTK_FUNCTION(1, "KPROW0"),
		MTK_FUNCTION(6, "TP_GPIO0_AO"),
		MTK_FUNCTION(8, "IOBIST39")
	),
	MTK_PIN_NODRV(
		40, "GPIO40",
		MTK_EINT_FUNCTION(0, 40),
		MTK_FUNCTION(0, "GPIO40"),
		MTK_FUNCTION(1, "KPCOL0"),
		MTK_FUNCTION(6, "TP_GPIO1_AO"),
		MTK_FUNCTION(7, "DBG_MON_A0"),
		MTK_FUNCTION(8, "IOBIST40")
	),
	MTK_PIN_NODRV(
		41, "GPIO41",
		MTK_EINT_FUNCTION(0, 41),
		MTK_FUNCTION(0, "GPIO41"),
		MTK_FUNCTION(1, "KPROW1"),
		MTK_FUNCTION(2, "SPI0_WP"),
		MTK_FUNCTION(3, "DISP_PWM1"),
		MTK_FUNCTION(4, "SRCLKENAI1"),
		MTK_FUNCTION(6, "TP_GPIO2_AO"),
		MTK_FUNCTION(8, "IOBIST41")
	),
	MTK_PIN_NODRV(
		42, "GPIO42",
		MTK_EINT_FUNCTION(0, 42),
		MTK_FUNCTION(0, "GPIO42"),
		MTK_FUNCTION(1, "SPI0_CLK"),
		MTK_FUNCTION(2, "SCP_SPI4_CK"),
		MTK_FUNCTION(3, "DSI1_ERR_FLG"),
		MTK_FUNCTION(4, "I2SIN2_BCK"),
		MTK_FUNCTION(5, "FMI2S_BCK"),
		MTK_FUNCTION(6, "TP_GPIO5_AO"),
		MTK_FUNCTION(8, "IOBIST42")
	),
	MTK_PIN_NODRV(
		43, "GPIO43",
		MTK_EINT_FUNCTION(0, 43),
		MTK_FUNCTION(0, "GPIO43"),
		MTK_FUNCTION(1, "SPI0_CSB"),
		MTK_FUNCTION(2, "SCP_SPI4_CS"),
		MTK_FUNCTION(3, "DSI2_ERR_FLG"),
		MTK_FUNCTION(4, "I2SIN2_LRCK"),
		MTK_FUNCTION(6, "TP_GPIO6_AO"),
		MTK_FUNCTION(8, "IOBIST43")
	),
	MTK_PIN_NODRV(
		44, "GPIO44",
		MTK_EINT_FUNCTION(0, 44),
		MTK_FUNCTION(0, "GPIO44"),
		MTK_FUNCTION(1, "SPI0_MO"),
		MTK_FUNCTION(2, "SCP_SPI4_MO"),
		MTK_FUNCTION(3, "MD_INT3"),
		MTK_FUNCTION(4, "I2SOUT2_DO"),
		MTK_FUNCTION(5, "FMI2S_LRCK"),
		MTK_FUNCTION(6, "TP_GPIO7_AO"),
		MTK_FUNCTION(8, "IOBIST44")
	),
	MTK_PIN_NODRV(
		45, "GPIO45",
		MTK_EINT_FUNCTION(0, 45),
		MTK_FUNCTION(0, "GPIO45"),
		MTK_FUNCTION(1, "SPI0_MI"),
		MTK_FUNCTION(2, "SCP_SPI4_MI"),
		MTK_FUNCTION(3, "MD_INT4"),
		MTK_FUNCTION(4, "I2SIN2_DI"),
		MTK_FUNCTION(5, "FMI2S_DI"),
		MTK_FUNCTION(6, "TP_GPIO9_AO"),
		MTK_FUNCTION(8, "IOBIST45")
	),
	MTK_PIN_NODRV(
		46, "GPIO46",
		MTK_EINT_FUNCTION(0, 46),
		MTK_FUNCTION(0, "GPIO46"),
		MTK_FUNCTION(1, "I2S_MCK0"),
		MTK_FUNCTION(2, "GPS_PPS0"),
		MTK_FUNCTION(3, "DMIC2_CLK"),
		MTK_FUNCTION(7, "DBG_MON_A2"),
		MTK_FUNCTION(8, "IOBIST46")
	),
	MTK_PIN_NODRV(
		47, "GPIO47",
		MTK_EINT_FUNCTION(0, 47),
		MTK_FUNCTION(0, "GPIO47"),
		MTK_FUNCTION(1, "I2SIN0_BCK"),
		MTK_FUNCTION(2, "SPI3_A_CLK"),
		MTK_FUNCTION(3, "DMIC2_DAT"),
		MTK_FUNCTION(4, "UCTS2"),
		MTK_FUNCTION(5, "MD32_0_GPIO0"),
		MTK_FUNCTION(7, "DBG_MON_A3"),
		MTK_FUNCTION(8, "IOBIST47")
	),
	MTK_PIN_NODRV(
		48, "GPIO48",
		MTK_EINT_FUNCTION(0, 48),
		MTK_FUNCTION(0, "GPIO48"),
		MTK_FUNCTION(1, "I2SIN0_LRCK"),
		MTK_FUNCTION(2, "SPI3_A_CSB"),
		MTK_FUNCTION(4, "URTS2"),
		MTK_FUNCTION(5, "MD32_1_GPIO0"),
		MTK_FUNCTION(7, "DBG_MON_A4"),
		MTK_FUNCTION(8, "IOBIST48")
	),
	MTK_PIN_NODRV(
		49, "GPIO49",
		MTK_EINT_FUNCTION(0, 49),
		MTK_FUNCTION(0, "GPIO49"),
		MTK_FUNCTION(1, "I2SIN0_DI"),
		MTK_FUNCTION(2, "SPI3_A_MO"),
		MTK_FUNCTION(4, "URXD2"),
		MTK_FUNCTION(5, "MD32_2_GPIO0"),
		MTK_FUNCTION(7, "DBG_MON_A5"),
		MTK_FUNCTION(8, "IOBIST49")
	),
	MTK_PIN_NODRV(
		50, "GPIO50",
		MTK_EINT_FUNCTION(0, 50),
		MTK_FUNCTION(0, "GPIO50"),
		MTK_FUNCTION(1, "I2SOUT0_DO"),
		MTK_FUNCTION(2, "SPI3_A_MI"),
		MTK_FUNCTION(4, "UTXD2"),
		MTK_FUNCTION(5, "MD32_3_GPIO0"),
		MTK_FUNCTION(7, "DBG_MON_A6"),
		MTK_FUNCTION(8, "IOBIST50")
	),
	MTK_PIN_NODRV(
		51, "GPIO51",
		MTK_EINT_FUNCTION(0, 51),
		MTK_FUNCTION(0, "GPIO51"),
		MTK_FUNCTION(1, "MCU_B_PMIC_POC_I"),
		MTK_FUNCTION(7, "DBG_MON_A11"),
		MTK_FUNCTION(8, "IOBIST51")
	),
	MTK_PIN_NODRV(
		52, "GPIO52",
		MTK_EINT_FUNCTION(0, 52),
		MTK_FUNCTION(0, "GPIO52"),
		MTK_FUNCTION(1, "MCU_M_PMIC_POC_I"),
		MTK_FUNCTION(7, "DBG_MON_A10"),
		MTK_FUNCTION(8, "IOBIST52")
	),
	MTK_PIN_NODRV(
		53, "GPIO53",
		MTK_EINT_FUNCTION(0, 53),
		MTK_FUNCTION(0, "GPIO53"),
		MTK_FUNCTION(1, "SPBM_ADC_SYNC"),
		MTK_FUNCTION(7, "DBG_MON_A12"),
		MTK_FUNCTION(8, "IOBIST53")
	),
	MTK_PIN_NODRV(
		54, "GPIO54",
		MTK_EINT_FUNCTION(0, 54),
		MTK_FUNCTION(0, "GPIO54"),
		MTK_FUNCTION(7, "DBG_MON_A22"),
		MTK_FUNCTION(8, "IOBIST54")
	),
	MTK_PIN_NODRV(
		55, "GPIO55",
		MTK_EINT_FUNCTION(0, 55),
		MTK_FUNCTION(0, "GPIO55"),
		MTK_FUNCTION(1, "DPM2PMIC"),
		MTK_FUNCTION(2, "SRCLKENA1"),
		MTK_FUNCTION(7, "DBG_MON_A14"),
		MTK_FUNCTION(8, "IOBIST55")
	),
	MTK_PIN_NODRV(
		56, "GPIO56",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO56"),
		MTK_FUNCTION(1, "WATCHDOG"),
		MTK_FUNCTION(7, "DBG_MON_A15"),
		MTK_FUNCTION(8, "IOBIST56")
	),
	MTK_PIN_NODRV(
		57, "GPIO57",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO57"),
		MTK_FUNCTION(1, "SRCLKENA0"),
		MTK_FUNCTION(7, "DBG_MON_A16"),
		MTK_FUNCTION(8, "IOBIST57")
	),
	MTK_PIN_NODRV(
		58, "GPIO58",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO58"),
		MTK_FUNCTION(1, "SCP_VREQ_VAO"),
		MTK_FUNCTION(7, "DBG_MON_A17"),
		MTK_FUNCTION(8, "IOBIST58")
	),
	MTK_PIN_NODRV(
		59, "GPIO59",
		MTK_EINT_FUNCTION(0, 59),
		MTK_FUNCTION(0, "GPIO59"),
		MTK_FUNCTION(7, "DBG_MON_A19"),
		MTK_FUNCTION(8, "IOBIST59")
	),
	MTK_PIN_NODRV(
		60, "GPIO60",
		MTK_EINT_FUNCTION(0, 60),
		MTK_FUNCTION(0, "GPIO60"),
		MTK_FUNCTION(1, "MCU_L_PMIC_POC_I"),
		MTK_FUNCTION(2, "CMFLASH0"),
		MTK_FUNCTION(3, "MD_INT0"),
		MTK_FUNCTION(8, "IOBIST60")
	),
	MTK_PIN_NODRV(
		61, "GPIO61",
		MTK_EINT_FUNCTION(0, 61),
		MTK_FUNCTION(0, "GPIO61"),
		MTK_FUNCTION(7, "DBG_MON_A20"),
		MTK_FUNCTION(8, "IOBIST61")
	),
	MTK_PIN_NODRV(
		62, "GPIO62",
		MTK_EINT_FUNCTION(0, 62),
		MTK_FUNCTION(0, "GPIO62"),
		MTK_FUNCTION(1, "PRE_UVLO"),
		MTK_FUNCTION(7, "DBG_MON_A13"),
		MTK_FUNCTION(8, "IOBIST62")
	),
	MTK_PIN_NODRV(
		63, "GPIO63",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO63"),
		MTK_FUNCTION(1, "RTC32K_CK"),
		MTK_FUNCTION(7, "DBG_MON_A18"),
		MTK_FUNCTION(8, "IOBIST63")
	),
	MTK_PIN_NODRV(
		64, "GPIO64",
		MTK_EINT_FUNCTION(0, 64),
		MTK_FUNCTION(0, "GPIO64"),
		MTK_FUNCTION(1, "DCXO_FPM_LPM"),
		MTK_FUNCTION(7, "DBG_MON_A23"),
		MTK_FUNCTION(8, "IOBIST64")
	),
	MTK_PIN_NODRV(
		65, "GPIO65",
		MTK_EINT_FUNCTION(0, 65),
		MTK_FUNCTION(0, "GPIO65"),
		MTK_FUNCTION(1, "CONN_FAULTB"),
		MTK_FUNCTION(8, "IOBIST65")
	),
	MTK_PIN_NODRV(
		66, "GPIO66",
		MTK_EINT_FUNCTION(0, 66),
		MTK_FUNCTION(0, "GPIO66"),
		MTK_FUNCTION(1, "SPI5_CLK"),
		MTK_FUNCTION(2, "USB_DRVVBUS"),
		MTK_FUNCTION(3, "DP_TX_HPD"),
		MTK_FUNCTION(7, "DBG_MON_A24"),
		MTK_FUNCTION(8, "IOBIST66")
	),
	MTK_PIN_NODRV(
		67, "GPIO67",
		MTK_EINT_FUNCTION(0, 67),
		MTK_FUNCTION(0, "GPIO67"),
		MTK_FUNCTION(1, "SPI5_CSB"),
		MTK_FUNCTION(2, "VBUSVALID"),
		MTK_FUNCTION(3, "DP_OC_EN"),
		MTK_FUNCTION(7, "DBG_MON_A25"),
		MTK_FUNCTION(8, "IOBIST67")
	),
	MTK_PIN_NODRV(
		68, "GPIO68",
		MTK_EINT_FUNCTION(0, 68),
		MTK_FUNCTION(0, "GPIO68"),
		MTK_FUNCTION(1, "SPI5_MO"),
		MTK_FUNCTION(3, "DP_RAUX_SBU1"),
		MTK_FUNCTION(7, "DBG_MON_A26"),
		MTK_FUNCTION(8, "IOBIST68")
	),
	MTK_PIN_NODRV(
		69, "GPIO69",
		MTK_EINT_FUNCTION(0, 69),
		MTK_FUNCTION(0, "GPIO69"),
		MTK_FUNCTION(1, "SPI5_MI"),
		MTK_FUNCTION(3, "DP_RAUX_SBU2"),
		MTK_FUNCTION(7, "DBG_MON_A27"),
		MTK_FUNCTION(8, "IOBIST69")
	),
	MTK_PIN_NODRV(
		70, "GPIO70",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO70"),
		MTK_FUNCTION(1, "SCL3"),
		MTK_FUNCTION(8, "IOBIST70")
	),
	MTK_PIN_NODRV(
		71, "GPIO71",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO71"),
		MTK_FUNCTION(1, "SDA3"),
		MTK_FUNCTION(8, "IOBIST71")
	),
	MTK_PIN_NODRV(
		72, "GPIO72",
		MTK_EINT_FUNCTION(0, 72),
		MTK_FUNCTION(0, "GPIO72"),
		MTK_FUNCTION(1, "CMMCLK0"),
		MTK_FUNCTION(2, "MD_INT3"),
		MTK_FUNCTION(6, "TP_GPIO14_AO"),
		MTK_FUNCTION(8, "IOBIST72")
	),
	MTK_PIN_NODRV(
		73, "GPIO73",
		MTK_EINT_FUNCTION(0, 73),
		MTK_FUNCTION(0, "GPIO73"),
		MTK_FUNCTION(1, "CMMCLK1"),
		MTK_FUNCTION(2, "MD_INT4"),
		MTK_FUNCTION(6, "TP_GPIO15_AO"),
		MTK_FUNCTION(8, "IOBIST73")
	),
	MTK_PIN_NODRV(
		74, "GPIO74",
		MTK_EINT_FUNCTION(0, 74),
		MTK_FUNCTION(0, "GPIO74"),
		MTK_FUNCTION(1, "MSDC1_CLK"),
		MTK_FUNCTION(2, "MD1_SIM2_SCLK"),
		MTK_FUNCTION(3, "DSI2_ERR_FLG"),
		MTK_FUNCTION(4, "UDI_TCK"),
		MTK_FUNCTION(5, "CONN_BGF_DSP_L1_JCK"),
		MTK_FUNCTION(6, "SCP_JTAG_LITTLE_TCK_VLP"),
		MTK_FUNCTION(7, "JTCK2_SEL1"),
		MTK_FUNCTION(8, "IOBIST74")
	),
	MTK_PIN_NODRV(
		75, "GPIO75",
		MTK_EINT_FUNCTION(0, 75),
		MTK_FUNCTION(0, "GPIO75"),
		MTK_FUNCTION(1, "MSDC1_CMD"),
		MTK_FUNCTION(3, "DSI3_ERR_FLG"),
		MTK_FUNCTION(4, "UDI_TMS"),
		MTK_FUNCTION(5, "CONN_BGF_DSP_L1_JMS"),
		MTK_FUNCTION(6, "SCP_JTAG_LITTLE_TMS_VLP"),
		MTK_FUNCTION(7, "JTMS2_SEL1"),
		MTK_FUNCTION(8, "IOBIST75")
	),
	MTK_PIN_NODRV(
		76, "GPIO76",
		MTK_EINT_FUNCTION(0, 76),
		MTK_FUNCTION(0, "GPIO76"),
		MTK_FUNCTION(1, "MSDC1_DAT0"),
		MTK_FUNCTION(2, "MD1_SIM2_SRST"),
		MTK_FUNCTION(3, "LCM1_RST"),
		MTK_FUNCTION(4, "UDI_TDI_0"),
		MTK_FUNCTION(5, "CONN_BGF_DSP_L1_JDI"),
		MTK_FUNCTION(6, "SCP_JTAG_LITTLE_TDI_VLP"),
		MTK_FUNCTION(7, "JTDI2_SEL1"),
		MTK_FUNCTION(8, "IOBIST76")
	),
	MTK_PIN_NODRV(
		77, "GPIO77",
		MTK_EINT_FUNCTION(0, 77),
		MTK_FUNCTION(0, "GPIO77"),
		MTK_FUNCTION(1, "MSDC1_DAT1"),
		MTK_FUNCTION(2, "MD1_SIM2_SIO"),
		MTK_FUNCTION(3, "DSI1_TE"),
		MTK_FUNCTION(4, "UDI_TDO_0"),
		MTK_FUNCTION(5, "CONN_BGF_DSP_L1_JDO"),
		MTK_FUNCTION(6, "SCP_JTAG_LITTLE_TDO_VLP"),
		MTK_FUNCTION(7, "JTDO2_SEL1"),
		MTK_FUNCTION(8, "IOBIST77")
	),
	MTK_PIN_NODRV(
		78, "GPIO78",
		MTK_EINT_FUNCTION(0, 78),
		MTK_FUNCTION(0, "GPIO78"),
		MTK_FUNCTION(1, "MSDC1_DAT2"),
		MTK_FUNCTION(2, "DSI2_HSYNC"),
		MTK_FUNCTION(3, "LCM2_RST"),
		MTK_FUNCTION(4, "UDI_NTRST"),
		MTK_FUNCTION(6, "SCP_JTAG_LITTLE_TRSTN_VLP"),
		MTK_FUNCTION(7, "JTRSTN2_SEL1"),
		MTK_FUNCTION(8, "IOBIST78")
	),
	MTK_PIN_NODRV(
		79, "GPIO79",
		MTK_EINT_FUNCTION(0, 79),
		MTK_FUNCTION(0, "GPIO79"),
		MTK_FUNCTION(1, "MSDC1_DAT3"),
		MTK_FUNCTION(2, "DSI3_HSYNC"),
		MTK_FUNCTION(3, "DSI2_TE"),
		MTK_FUNCTION(5, "CONN_BGF_DSP_L1_JINTP"),
		MTK_FUNCTION(8, "IOBIST79")
	),
	MTK_PIN_NODRV(
		80, "GPIO80",
		MTK_EINT_FUNCTION(0, 80),
		MTK_FUNCTION(0, "GPIO80"),
		MTK_FUNCTION(1, "SCP_SPI0_CK"),
		MTK_FUNCTION(2, "SPI6_B_CLK"),
		MTK_FUNCTION(4, "PWM_VLP"),
		MTK_FUNCTION(6, "TP_GPIO6_AO"),
		MTK_FUNCTION(8, "IOBIST80")
	),
	MTK_PIN_NODRV(
		81, "GPIO81",
		MTK_EINT_FUNCTION(0, 81),
		MTK_FUNCTION(0, "GPIO81"),
		MTK_FUNCTION(1, "SCP_SPI0_CS"),
		MTK_FUNCTION(2, "SPI6_B_CSB"),
		MTK_FUNCTION(6, "TP_GPIO7_AO"),
		MTK_FUNCTION(8, "IOBIST81")
	),
	MTK_PIN_NODRV(
		82, "GPIO82",
		MTK_EINT_FUNCTION(0, 82),
		MTK_FUNCTION(0, "GPIO82"),
		MTK_FUNCTION(1, "SCP_SPI0_MO"),
		MTK_FUNCTION(2, "SPI6_B_MO"),
		MTK_FUNCTION(6, "TP_GPIO8_AO"),
		MTK_FUNCTION(8, "IOBIST82")
	),
	MTK_PIN_NODRV(
		83, "GPIO83",
		MTK_EINT_FUNCTION(0, 83),
		MTK_FUNCTION(0, "GPIO83"),
		MTK_FUNCTION(1, "SCP_SPI0_MI"),
		MTK_FUNCTION(2, "SPI6_B_MI"),
		MTK_FUNCTION(6, "TP_GPIO9_AO"),
		MTK_FUNCTION(8, "IOBIST83")
	),
	MTK_PIN_NODRV(
		84, "GPIO84",
		MTK_EINT_FUNCTION(0, 84),
		MTK_FUNCTION(0, "GPIO84"),
		MTK_FUNCTION(1, "SCP_SPI1_CK"),
		MTK_FUNCTION(2, "SPI7_B_CLK"),
		MTK_FUNCTION(3, "I2SIN5_DATA0"),
		MTK_FUNCTION(4, "PWM_VLP"),
		MTK_FUNCTION(6, "TP_GPIO10_AO"),
		MTK_FUNCTION(8, "IOBIST84")
	),
	MTK_PIN_NODRV(
		85, "GPIO85",
		MTK_EINT_FUNCTION(0, 85),
		MTK_FUNCTION(0, "GPIO85"),
		MTK_FUNCTION(1, "SCP_SPI1_CS"),
		MTK_FUNCTION(2, "SPI7_B_CSB"),
		MTK_FUNCTION(3, "I2SIN5_DATA1"),
		MTK_FUNCTION(4, "PMSR_SMAP"),
		MTK_FUNCTION(6, "TP_GPIO11_AO"),
		MTK_FUNCTION(8, "IOBIST85")
	),
	MTK_PIN_NODRV(
		86, "GPIO86",
		MTK_EINT_FUNCTION(0, 86),
		MTK_FUNCTION(0, "GPIO86"),
		MTK_FUNCTION(1, "SCP_SPI1_MO"),
		MTK_FUNCTION(2, "SPI7_B_MO"),
		MTK_FUNCTION(3, "I2SIN5_DATA2"),
		MTK_FUNCTION(4, "PMSR_SMAP_MAX"),
		MTK_FUNCTION(6, "TP_GPIO12_AO"),
		MTK_FUNCTION(8, "IOBIST86")
	),
	MTK_PIN_NODRV(
		87, "GPIO87",
		MTK_EINT_FUNCTION(0, 87),
		MTK_FUNCTION(0, "GPIO87"),
		MTK_FUNCTION(1, "SCP_SPI1_MI"),
		MTK_FUNCTION(2, "SPI7_B_MI"),
		MTK_FUNCTION(3, "I2SIN5_DATA3"),
		MTK_FUNCTION(4, "PMSR_SMAP_MAX_W"),
		MTK_FUNCTION(6, "TP_GPIO13_AO"),
		MTK_FUNCTION(8, "IOBIST87")
	),
	MTK_PIN_NODRV(
		88, "GPIO88",
		MTK_EINT_FUNCTION(0, 88),
		MTK_FUNCTION(0, "GPIO88"),
		MTK_FUNCTION(1, "DSI_TE"),
		MTK_FUNCTION(8, "IOBIST88")
	),
	MTK_PIN_NODRV(
		89, "GPIO89",
		MTK_EINT_FUNCTION(0, 89),
		MTK_FUNCTION(0, "GPIO89"),
		MTK_FUNCTION(1, "LCM_RST"),
		MTK_FUNCTION(8, "IOBIST89")
	),
	MTK_PIN_NODRV(
		90, "GPIO90",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO90"),
		MTK_FUNCTION(1, "MD1_SIM1_SCLK"),
		MTK_FUNCTION(2, "MD1_SIM2_SCLK"),
		MTK_FUNCTION(4, "CLKM0_A"),
		MTK_FUNCTION(6, "TSFDC_26M"),
		MTK_FUNCTION(7, "DBG_MON_B4"),
		MTK_FUNCTION(8, "IOBIST90")
	),
	MTK_PIN_NODRV(
		91, "GPIO91",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO91"),
		MTK_FUNCTION(1, "MD1_SIM1_SRST"),
		MTK_FUNCTION(2, "MD1_SIM2_SRST"),
		MTK_FUNCTION(3, "MCUPM_JTAG_TCK"),
		MTK_FUNCTION(4, "CLKM1_A"),
		MTK_FUNCTION(5, "CONN_BGF_DSP_L5_JCK"),
		MTK_FUNCTION(6, "TSFDC_SDO"),
		MTK_FUNCTION(7, "SCP_JTAG0_TCK_VCORE"),
		MTK_FUNCTION(8, "IOBIST91")
	),
	MTK_PIN_NODRV(
		92, "GPIO92",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO92"),
		MTK_FUNCTION(1, "MD1_SIM1_SIO"),
		MTK_FUNCTION(2, "MD1_SIM2_SIO"),
		MTK_FUNCTION(3, "MCUPM_JTAG_TRSTN"),
		MTK_FUNCTION(4, "CLKM2_A"),
		MTK_FUNCTION(5, "CONN_BGF_DSP_L5_JINTP"),
		MTK_FUNCTION(6, "TSFDC_FOUT"),
		MTK_FUNCTION(7, "SCP_JTAG0_TRSTN_VCORE"),
		MTK_FUNCTION(8, "IOBIST92")
	),
	MTK_PIN_NODRV(
		93, "GPIO93",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO93"),
		MTK_FUNCTION(1, "MD1_SIM2_SCLK"),
		MTK_FUNCTION(2, "MD1_SIM1_SCLK"),
		MTK_FUNCTION(3, "MCUPM_JTAG_TDI"),
		MTK_FUNCTION(4, "CLKM0_B"),
		MTK_FUNCTION(5, "CONN_BGF_DSP_L5_JDI"),
		MTK_FUNCTION(6, "TSFDC_SCK"),
		MTK_FUNCTION(7, "SCP_JTAG0_TDI_VCORE"),
		MTK_FUNCTION(8, "IOBIST93")
	),
	MTK_PIN_NODRV(
		94, "GPIO94",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO94"),
		MTK_FUNCTION(1, "MD1_SIM2_SRST"),
		MTK_FUNCTION(2, "MD1_SIM1_SRST"),
		MTK_FUNCTION(3, "MCUPM_JTAG_TMS"),
		MTK_FUNCTION(4, "CLKM1_B"),
		MTK_FUNCTION(5, "CONN_BGF_DSP_L5_JMS"),
		MTK_FUNCTION(6, "TSFDC_SDI"),
		MTK_FUNCTION(7, "SCP_JTAG0_TMS_VCORE"),
		MTK_FUNCTION(8, "IOBIST94")
	),
	MTK_PIN_NODRV(
		95, "GPIO95",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO95"),
		MTK_FUNCTION(1, "MD1_SIM2_SIO"),
		MTK_FUNCTION(2, "MD1_SIM1_SIO"),
		MTK_FUNCTION(3, "MCUPM_JTAG_TDO"),
		MTK_FUNCTION(4, "CLKM2_B"),
		MTK_FUNCTION(5, "CONN_BGF_DSP_L5_JDO"),
		MTK_FUNCTION(6, "TSFDC_SCF"),
		MTK_FUNCTION(7, "SCP_JTAG0_TDO_VCORE"),
		MTK_FUNCTION(8, "IOBIST95")
	),
	MTK_PIN_NODRV(
		96, "GPIO96",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO96"),
		MTK_FUNCTION(1, "SCP_SCL1"),
		MTK_FUNCTION(3, "TDM_MCK"),
		MTK_FUNCTION(8, "IOBIST96")
	),
	MTK_PIN_NODRV(
		97, "GPIO97",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO97"),
		MTK_FUNCTION(1, "SCP_SDA1"),
		MTK_FUNCTION(3, "TDM_DATA3"),
		MTK_FUNCTION(8, "IOBIST97")
	),
	MTK_PIN_NODRV(
		98, "GPIO98",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO98"),
		MTK_FUNCTION(1, "AUD_CLK_MOSI"),
		MTK_FUNCTION(3, "TDM_BCK"),
		MTK_FUNCTION(7, "DBG_MON_B5"),
		MTK_FUNCTION(8, "IOBIST98")
	),
	MTK_PIN_NODRV(
		99, "GPIO99",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO99"),
		MTK_FUNCTION(1, "AUD_CLK_MISO"),
		MTK_FUNCTION(2, "I2SOUT2_BCK"),
		MTK_FUNCTION(3, "TDM_LRCK"),
		MTK_FUNCTION(4, "AUD_SW_CLK"),
		MTK_FUNCTION(5, "SCP_SW_CLK"),
		MTK_FUNCTION(7, "DBG_MON_B6"),
		MTK_FUNCTION(8, "IOBIST99")
	),
	MTK_PIN_NODRV(
		100, "GPIO100",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO100"),
		MTK_FUNCTION(1, "AUD_DAT_MOSI0"),
		MTK_FUNCTION(2, "I2SOUT2_LRCK"),
		MTK_FUNCTION(3, "TDM_DATA0"),
		MTK_FUNCTION(7, "DBG_MON_B7"),
		MTK_FUNCTION(8, "IOBIST100")
	),
	MTK_PIN_NODRV(
		101, "GPIO101",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO101"),
		MTK_FUNCTION(1, "AUD_DAT_MOSI1"),
		MTK_FUNCTION(2, "I2SOUT2_DO"),
		MTK_FUNCTION(3, "TDM_DATA1"),
		MTK_FUNCTION(4, "AUD_SW_DAT"),
		MTK_FUNCTION(5, "SCP_SW_DAT"),
		MTK_FUNCTION(7, "DBG_MON_B8"),
		MTK_FUNCTION(8, "IOBIST101")
	),
	MTK_PIN_NODRV(
		102, "GPIO102",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO102"),
		MTK_FUNCTION(1, "AUD_DAT_MISO0"),
		MTK_FUNCTION(3, "TDM_DATA2"),
		MTK_FUNCTION(6, "RG_TSFDC_LDO_EN"),
		MTK_FUNCTION(7, "DBG_MON_B9"),
		MTK_FUNCTION(8, "IOBIST102")
	),
	MTK_PIN_NODRV(
		103, "GPIO103",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO103"),
		MTK_FUNCTION(1, "AUD_DAT_MISO1"),
		MTK_FUNCTION(3, "I2SIN1_BCK"),
		MTK_FUNCTION(6, "DA_TSFDC_LDO_MODE"),
		MTK_FUNCTION(7, "DBG_MON_B10"),
		MTK_FUNCTION(8, "IOBIST103")
	),
	MTK_PIN_NODRV(
		104, "GPIO104",
		MTK_EINT_FUNCTION(0, 104),
		MTK_FUNCTION(0, "GPIO104"),
		MTK_FUNCTION(1, "CMFLASH1"),
		MTK_FUNCTION(2, "MD_INT0"),
		MTK_FUNCTION(3, "DISP_PWM1"),
		MTK_FUNCTION(4, "TP_URTS1_VLP"),
		MTK_FUNCTION(6, "TP_GPIO0_AO"),
		MTK_FUNCTION(7, "DBG_MON_B12"),
		MTK_FUNCTION(8, "IOBIST104")
	),
	MTK_PIN_NODRV(
		105, "GPIO105",
		MTK_EINT_FUNCTION(0, 105),
		MTK_FUNCTION(0, "GPIO105"),
		MTK_FUNCTION(1, "CMFLASH2"),
		MTK_FUNCTION(2, "MD_INT3"),
		MTK_FUNCTION(3, "SRCLKENAI0"),
		MTK_FUNCTION(4, "TP_UCTS1_VLP"),
		MTK_FUNCTION(5, "KPROW2"),
		MTK_FUNCTION(6, "TP_GPIO1_AO"),
		MTK_FUNCTION(7, "DBG_MON_B13"),
		MTK_FUNCTION(8, "IOBIST105")
	),
	MTK_PIN_NODRV(
		106, "GPIO106",
		MTK_EINT_FUNCTION(0, 106),
		MTK_FUNCTION(0, "GPIO106"),
		MTK_FUNCTION(1, "CMFLASH3"),
		MTK_FUNCTION(2, "MD_INT4"),
		MTK_FUNCTION(3, "SRCLKENAI1"),
		MTK_FUNCTION(5, "KPCOL2"),
		MTK_FUNCTION(6, "TP_GPIO2_AO"),
		MTK_FUNCTION(7, "DBG_MON_B14"),
		MTK_FUNCTION(8, "IOBIST106")
	),
	MTK_PIN_NODRV(
		107, "GPIO107",
		MTK_EINT_FUNCTION(0, 107),
		MTK_FUNCTION(0, "GPIO107"),
		MTK_FUNCTION(1, "I2S_MCK1"),
		MTK_FUNCTION(2, "MD32_0_GPIO0"),
		MTK_FUNCTION(4, "IDDIG"),
		MTK_FUNCTION(6, "TP_GPIO3_AO"),
		MTK_FUNCTION(7, "DBG_MON_B15"),
		MTK_FUNCTION(8, "IOBIST107")
	),
	MTK_PIN_NODRV(
		108, "GPIO108",
		MTK_EINT_FUNCTION(0, 108),
		MTK_FUNCTION(0, "GPIO108"),
		MTK_FUNCTION(1, "I2SIN1_BCK"),
		MTK_FUNCTION(2, "LCM3_RST"),
		MTK_FUNCTION(3, "SPI6_A_CLK"),
		MTK_FUNCTION(4, "USB_DRVVBUS"),
		MTK_FUNCTION(5, "I2SIN4_BCK"),
		MTK_FUNCTION(6, "TP_GPIO4_AO"),
		MTK_FUNCTION(7, "DBG_MON_B16"),
		MTK_FUNCTION(8, "IOBIST108")
	),
	MTK_PIN_NODRV(
		109, "GPIO109",
		MTK_EINT_FUNCTION(0, 109),
		MTK_FUNCTION(0, "GPIO109"),
		MTK_FUNCTION(1, "I2SIN1_LRCK"),
		MTK_FUNCTION(2, "DSI3_TE"),
		MTK_FUNCTION(3, "SPI6_A_CSB"),
		MTK_FUNCTION(4, "VBUSVALID"),
		MTK_FUNCTION(5, "I2SIN4_LRCK"),
		MTK_FUNCTION(6, "TP_GPIO5_AO"),
		MTK_FUNCTION(7, "DBG_MON_B17"),
		MTK_FUNCTION(8, "IOBIST109")
	),
	MTK_PIN_NODRV(
		110, "GPIO110",
		MTK_EINT_FUNCTION(0, 110),
		MTK_FUNCTION(0, "GPIO110"),
		MTK_FUNCTION(1, "I2SIN1_DI"),
		MTK_FUNCTION(2, "MD32_0_RXD"),
		MTK_FUNCTION(3, "SPI6_A_MO"),
		MTK_FUNCTION(5, "I2SIN4_DATA0"),
		MTK_FUNCTION(7, "DBG_MON_B18"),
		MTK_FUNCTION(8, "IOBIST110")
	),
	MTK_PIN_NODRV(
		111, "GPIO111",
		MTK_EINT_FUNCTION(0, 111),
		MTK_FUNCTION(0, "GPIO111"),
		MTK_FUNCTION(1, "I2SOUT1_DO"),
		MTK_FUNCTION(2, "MD32_0_TXD"),
		MTK_FUNCTION(3, "SPI6_A_MI"),
		MTK_FUNCTION(5, "I2SOUT4_DATA0"),
		MTK_FUNCTION(7, "DBG_MON_B19"),
		MTK_FUNCTION(8, "IOBIST111")
	),
	MTK_PIN_NODRV(
		112, "GPIO112",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO112"),
		MTK_FUNCTION(1, "SCL0"),
		MTK_FUNCTION(3, "AUD_DAC_26M_CLK"),
		MTK_FUNCTION(4, "UFS_0_MPHY_SCL"),
		MTK_FUNCTION(8, "IOBIST112")
	),
	MTK_PIN_NODRV(
		113, "GPIO113",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO113"),
		MTK_FUNCTION(1, "SDA0"),
		MTK_FUNCTION(4, "UFS_0_MPHY_SDA"),
		MTK_FUNCTION(8, "IOBIST113")
	),
	MTK_PIN_NODRV(
		114, "GPIO114",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO114"),
		MTK_FUNCTION(1, "SCL6"),
		MTK_FUNCTION(2, "SPU1_SCL"),
		MTK_FUNCTION(3, "AUD_DAC_26M_CLK"),
		MTK_FUNCTION(4, "UFS_1_MPHY_SCL"),
		MTK_FUNCTION(5, "I2S_MCK0"),
		MTK_FUNCTION(8, "IOBIST114")
	),
	MTK_PIN_NODRV(
		115, "GPIO115",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO115"),
		MTK_FUNCTION(1, "SDA6"),
		MTK_FUNCTION(2, "SPU1_SDA"),
		MTK_FUNCTION(4, "UFS_1_MPHY_SDA"),
		MTK_FUNCTION(5, "I2S_MCK1"),
		MTK_FUNCTION(8, "IOBIST115")
	),
	MTK_PIN_NODRV(
		116, "GPIO116",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO116"),
		MTK_FUNCTION(1, "SCL10"),
		MTK_FUNCTION(2, "DMIC1_CLK"),
		MTK_FUNCTION(3, "SCP_DMIC1_CLK"),
		MTK_FUNCTION(4, "SCP_SCL10_OIS"),
		MTK_FUNCTION(8, "IOBIST116")
	),
	MTK_PIN_NODRV(
		117, "GPIO117",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO117"),
		MTK_FUNCTION(1, "SDA10"),
		MTK_FUNCTION(2, "DMIC1_DAT"),
		MTK_FUNCTION(3, "SCP_DMIC1_DAT"),
		MTK_FUNCTION(4, "SCP_SDA10_OIS"),
		MTK_FUNCTION(8, "IOBIST117")
	),
	MTK_PIN_NODRV(
		118, "GPIO118",
		MTK_EINT_FUNCTION(0, 118),
		MTK_FUNCTION(0, "GPIO118"),
		MTK_FUNCTION(1, "DISP_PWM"),
		MTK_FUNCTION(2, "DSI_HSYNC"),
		MTK_FUNCTION(3, "SRCLKENAI1"),
		MTK_FUNCTION(5, "I2S_MCK2"),
		MTK_FUNCTION(7, "DBG_MON_B20"),
		MTK_FUNCTION(8, "IOBIST118")
	),
	MTK_PIN_NODRV(
		119, "GPIO119",
		MTK_EINT_FUNCTION(0, 119),
		MTK_FUNCTION(0, "GPIO119"),
		MTK_FUNCTION(1, "AP_GOOD"),
		MTK_FUNCTION(7, "DBG_MON_B21"),
		MTK_FUNCTION(8, "IOBIST119")
	),
	MTK_PIN_NODRV(
		120, "GPIO120",
		MTK_EINT_FUNCTION(0, 120),
		MTK_FUNCTION(0, "GPIO120"),
		MTK_FUNCTION(1, "MIPI0_D_SCLK"),
		MTK_FUNCTION(2, "BPI_BUS16"),
		MTK_FUNCTION(5, "EXT_FRAME_SYNC"),
		MTK_FUNCTION(7, "DBG_MON_B24"),
		MTK_FUNCTION(8, "IOBIST120")
	),
	MTK_PIN_NODRV(
		121, "GPIO121",
		MTK_EINT_FUNCTION(0, 121),
		MTK_FUNCTION(0, "GPIO121"),
		MTK_FUNCTION(1, "MIPI0_D_SDATA"),
		MTK_FUNCTION(2, "BPI_BUS17"),
		MTK_FUNCTION(4, "PCM0_LRCK"),
		MTK_FUNCTION(7, "DBG_MON_B25"),
		MTK_FUNCTION(8, "IOBIST121")
	),
	MTK_PIN_NODRV(
		122, "GPIO122",
		MTK_EINT_FUNCTION(0, 122),
		MTK_FUNCTION(0, "GPIO122"),
		MTK_FUNCTION(1, "MIPI1_D_SCLK"),
		MTK_FUNCTION(2, "BPI_BUS18"),
		MTK_FUNCTION(4, "MD_UTXD1_CONN"),
		MTK_FUNCTION(5, "MD_GPS_BLANK_EXT"),
		MTK_FUNCTION(7, "DBG_MON_B26"),
		MTK_FUNCTION(8, "IOBIST122")
	),
	MTK_PIN_NODRV(
		123, "GPIO123",
		MTK_EINT_FUNCTION(0, 123),
		MTK_FUNCTION(0, "GPIO123"),
		MTK_FUNCTION(1, "MIPI1_D_SDATA"),
		MTK_FUNCTION(2, "BPI_BUS19"),
		MTK_FUNCTION(4, "MD_URXD1_CONN"),
		MTK_FUNCTION(7, "DBG_MON_B27"),
		MTK_FUNCTION(8, "IOBIST123")
	),
	MTK_PIN_NODRV(
		124, "GPIO124",
		MTK_EINT_FUNCTION(0, 124),
		MTK_FUNCTION(0, "GPIO124"),
		MTK_FUNCTION(1, "MIPI2_D_SCLK"),
		MTK_FUNCTION(2, "BPI_BUS20"),
		MTK_FUNCTION(7, "DBG_MON_B28"),
		MTK_FUNCTION(8, "IOBIST124")
	),
	MTK_PIN_NODRV(
		125, "GPIO125",
		MTK_EINT_FUNCTION(0, 125),
		MTK_FUNCTION(0, "GPIO125"),
		MTK_FUNCTION(1, "MIPI2_D_SDATA"),
		MTK_FUNCTION(2, "BPI_BUS21"),
		MTK_FUNCTION(7, "DBG_MON_B29"),
		MTK_FUNCTION(8, "IOBIST125")
	),
	MTK_PIN_NODRV(
		126, "GPIO126",
		MTK_EINT_FUNCTION(0, 126),
		MTK_FUNCTION(0, "GPIO126"),
		MTK_FUNCTION(1, "MIPI3_D_SCLK"),
		MTK_FUNCTION(2, "BPI_BUS22"),
		MTK_FUNCTION(4, "MD_UTXD1_CONN"),
		MTK_FUNCTION(5, "TP_UTXD_GNSS_VLP"),
		MTK_FUNCTION(7, "DBG_MON_B30"),
		MTK_FUNCTION(8, "IOBIST126")
	),
	MTK_PIN_NODRV(
		127, "GPIO127",
		MTK_EINT_FUNCTION(0, 127),
		MTK_FUNCTION(0, "GPIO127"),
		MTK_FUNCTION(1, "MIPI3_D_SDATA"),
		MTK_FUNCTION(2, "BPI_BUS23"),
		MTK_FUNCTION(4, "MD_URXD1_CONN"),
		MTK_FUNCTION(5, "TP_URXD_GNSS_VLP"),
		MTK_FUNCTION(7, "DBG_MON_B31"),
		MTK_FUNCTION(8, "IOBIST127")
	),
	MTK_PIN_NODRV(
		128, "GPIO128",
		MTK_EINT_FUNCTION(0, 128),
		MTK_FUNCTION(0, "GPIO128"),
		MTK_FUNCTION(1, "MD_UCNT_A_TGL"),
		MTK_FUNCTION(8, "IOBIST128")
	),
	MTK_PIN_NODRV(
		129, "GPIO129",
		MTK_EINT_FUNCTION(0, 129),
		MTK_FUNCTION(0, "GPIO129"),
		MTK_FUNCTION(1, "DIGRF_IRQ"),
		MTK_FUNCTION(8, "IOBIST129")
	),
	MTK_PIN_NODRV(
		130, "GPIO130",
		MTK_EINT_FUNCTION(0, 130),
		MTK_FUNCTION(0, "GPIO130"),
		MTK_FUNCTION(1, "MIPI_M_SCLK"),
		MTK_FUNCTION(8, "IOBIST130")
	),
	MTK_PIN_NODRV(
		131, "GPIO131",
		MTK_EINT_FUNCTION(0, 131),
		MTK_FUNCTION(0, "GPIO131"),
		MTK_FUNCTION(1, "MIPI_M_SDATA"),
		MTK_FUNCTION(8, "IOBIST131")
	),
	MTK_PIN_NODRV(
		132, "GPIO132",
		MTK_EINT_FUNCTION(0, 132),
		MTK_FUNCTION(0, "GPIO132"),
		MTK_FUNCTION(1, "BPI_BUS0"),
		MTK_FUNCTION(2, "PCIE_WAKEN_1P"),
		MTK_FUNCTION(3, "LCM3_RST"),
		MTK_FUNCTION(4, "CLKM3_A"),
		MTK_FUNCTION(8, "IOBIST132")
	),
	MTK_PIN_NODRV(
		133, "GPIO133",
		MTK_EINT_FUNCTION(0, 133),
		MTK_FUNCTION(0, "GPIO133"),
		MTK_FUNCTION(1, "BPI_BUS1"),
		MTK_FUNCTION(2, "PCIE_PERSTN_1P"),
		MTK_FUNCTION(4, "CLKM3_B"),
		MTK_FUNCTION(8, "IOBIST133")
	),
	MTK_PIN_NODRV(
		134, "GPIO134",
		MTK_EINT_FUNCTION(0, 134),
		MTK_FUNCTION(0, "GPIO134"),
		MTK_FUNCTION(1, "BPI_BUS2"),
		MTK_FUNCTION(2, "PCIE_CLKREQN_1P"),
		MTK_FUNCTION(3, "DSI3_TE"),
		MTK_FUNCTION(7, "DBG_MON_B0"),
		MTK_FUNCTION(8, "IOBIST134")
	),
	MTK_PIN_NODRV(
		135, "GPIO135",
		MTK_EINT_FUNCTION(0, 135),
		MTK_FUNCTION(0, "GPIO135"),
		MTK_FUNCTION(1, "BPI_BUS3"),
		MTK_FUNCTION(3, "LCM2_RST"),
		MTK_FUNCTION(4, "CLKM0_A"),
		MTK_FUNCTION(5, "TP_UTXD_MD_VLP"),
		MTK_FUNCTION(7, "DBG_MON_B1"),
		MTK_FUNCTION(8, "IOBIST135")
	),
	MTK_PIN_NODRV(
		136, "GPIO136",
		MTK_EINT_FUNCTION(0, 136),
		MTK_FUNCTION(0, "GPIO136"),
		MTK_FUNCTION(1, "BPI_BUS4"),
		MTK_FUNCTION(3, "DSI2_TE"),
		MTK_FUNCTION(4, "CLKM1_A"),
		MTK_FUNCTION(5, "TP_URXD_MD_VLP"),
		MTK_FUNCTION(7, "DBG_MON_B22"),
		MTK_FUNCTION(8, "IOBIST136")
	),
	MTK_PIN_NODRV(
		137, "GPIO137",
		MTK_EINT_FUNCTION(0, 137),
		MTK_FUNCTION(0, "GPIO137"),
		MTK_FUNCTION(1, "BPI_BUS5"),
		MTK_FUNCTION(3, "EXT_FRAME_SYNC"),
		MTK_FUNCTION(4, "CLKM2_A"),
		MTK_FUNCTION(5, "TP_GPIO6_AO"),
		MTK_FUNCTION(6, "SCP_JTAG_LITTLE_TRSTN_VCORE"),
		MTK_FUNCTION(7, "DBG_MON_B23"),
		MTK_FUNCTION(8, "IOBIST137")
	),
	MTK_PIN_NODRV(
		138, "GPIO138",
		MTK_EINT_FUNCTION(0, 138),
		MTK_FUNCTION(0, "GPIO138"),
		MTK_FUNCTION(1, "BPI_BUS6"),
		MTK_FUNCTION(3, "MD_GPS_BLANK_EXT"),
		MTK_FUNCTION(4, "CLKM3_A"),
		MTK_FUNCTION(5, "TP_GPIO7_AO"),
		MTK_FUNCTION(6, "SCP_JTAG_LITTLE_TCK_VCORE"),
		MTK_FUNCTION(8, "IOBIST138")
	),
	MTK_PIN_NODRV(
		139, "GPIO139",
		MTK_EINT_FUNCTION(0, 139),
		MTK_FUNCTION(0, "GPIO139"),
		MTK_FUNCTION(1, "BPI_BUS7"),
		MTK_FUNCTION(3, "UTXD2"),
		MTK_FUNCTION(4, "CLKM0_B"),
		MTK_FUNCTION(5, "SSPM_UTXD_AO_VCORE"),
		MTK_FUNCTION(6, "SCP_JTAG_LITTLE_TMS_VCORE"),
		MTK_FUNCTION(8, "IOBIST139")
	),
	MTK_PIN_NODRV(
		140, "GPIO140",
		MTK_EINT_FUNCTION(0, 140),
		MTK_FUNCTION(0, "GPIO140"),
		MTK_FUNCTION(1, "BPI_BUS8"),
		MTK_FUNCTION(3, "URXD2"),
		MTK_FUNCTION(4, "CLKM1_B"),
		MTK_FUNCTION(5, "SSPM_URXD_AO_VCORE"),
		MTK_FUNCTION(6, "SCP_JTAG_LITTLE_TDO_VCORE"),
		MTK_FUNCTION(8, "IOBIST140")
	),
	MTK_PIN_NODRV(
		141, "GPIO141",
		MTK_EINT_FUNCTION(0, 141),
		MTK_FUNCTION(0, "GPIO141"),
		MTK_FUNCTION(1, "BPI_BUS9"),
		MTK_FUNCTION(4, "CLKM2_B"),
		MTK_FUNCTION(6, "SCP_JTAG_LITTLE_TDI_VCORE"),
		MTK_FUNCTION(8, "IOBIST141")
	),
	MTK_PIN_NODRV(
		142, "GPIO142",
		MTK_EINT_FUNCTION(0, 142),
		MTK_FUNCTION(0, "GPIO142"),
		MTK_FUNCTION(1, "BPI_BUS10"),
		MTK_FUNCTION(2, "CONN_TCXOENA_REQ"),
		MTK_FUNCTION(3, "DISP_PWM1"),
		MTK_FUNCTION(4, "CLKM3_B"),
		MTK_FUNCTION(5, "TP_GPIO8_AO"),
		MTK_FUNCTION(8, "IOBIST142")
	),
	MTK_PIN_NODRV(
		143, "GPIO143",
		MTK_EINT_FUNCTION(0, 143),
		MTK_FUNCTION(0, "GPIO143"),
		MTK_FUNCTION(1, "KPCOL1"),
		MTK_FUNCTION(6, "SPM_JTAG_TRSTN_VLP"),
		MTK_FUNCTION(7, "JTRSTN_SEL1"),
		MTK_FUNCTION(8, "IOBIST143")
	),
	MTK_PIN_NODRV(
		144, "GPIO144",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO144"),
		MTK_FUNCTION(1, "SPMI_M_SCL"),
		MTK_FUNCTION(8, "IOBIST144")
	),
	MTK_PIN_NODRV(
		145, "GPIO145",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO145"),
		MTK_FUNCTION(1, "SPMI_M_SDA"),
		MTK_FUNCTION(8, "IOBIST145")
	),
	MTK_PIN_NODRV(
		146, "GPIO146",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO146"),
		MTK_FUNCTION(1, "SPMI_P_SCL"),
		MTK_FUNCTION(8, "IOBIST146")
	),
	MTK_PIN_NODRV(
		147, "GPIO147",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO147"),
		MTK_FUNCTION(1, "SPMI_P_SDA"),
		MTK_FUNCTION(8, "IOBIST147")
	),
	MTK_PIN_NODRV(
		148, "GPIO148",
		MTK_EINT_FUNCTION(0, 148),
		MTK_FUNCTION(0, "GPIO148"),
		MTK_FUNCTION(1, "SCP_SPI3_CK"),
		MTK_FUNCTION(2, "SPI3_B_CLK"),
		MTK_FUNCTION(3, "MD_UTXD0"),
		MTK_FUNCTION(4, "TP_UTXD1_VLP"),
		MTK_FUNCTION(5, "CONN_BG_GPS_MCU_UART0_TXD"),
		MTK_FUNCTION(6, "SPU0_UTX"),
		MTK_FUNCTION(8, "IOBIST148")
	),
	MTK_PIN_NODRV(
		149, "GPIO149",
		MTK_EINT_FUNCTION(0, 149),
		MTK_FUNCTION(0, "GPIO149"),
		MTK_FUNCTION(1, "SCP_SPI3_CS"),
		MTK_FUNCTION(2, "SPI3_B_CSB"),
		MTK_FUNCTION(3, "MD_URXD0"),
		MTK_FUNCTION(4, "TP_URXD1_VLP"),
		MTK_FUNCTION(5, "CONN_BG_GPS_MCU_UART0_RXD"),
		MTK_FUNCTION(6, "SPU0_URX"),
		MTK_FUNCTION(8, "IOBIST149")
	),
	MTK_PIN_NODRV(
		150, "GPIO150",
		MTK_EINT_FUNCTION(0, 150),
		MTK_FUNCTION(0, "GPIO150"),
		MTK_FUNCTION(1, "SCP_SPI3_MO"),
		MTK_FUNCTION(2, "SPI3_B_MO"),
		MTK_FUNCTION(3, "MD_UTXD1"),
		MTK_FUNCTION(4, "MD32PCM_UTXD_AO_VLP"),
		MTK_FUNCTION(5, "CONN_BG_GPS_MCU_UART1_TXD"),
		MTK_FUNCTION(6, "SPU1_UTX"),
		MTK_FUNCTION(7, "HFRP_UTXD1"),
		MTK_FUNCTION(8, "IOBIST150")
	),
	MTK_PIN_NODRV(
		151, "GPIO151",
		MTK_EINT_FUNCTION(0, 151),
		MTK_FUNCTION(0, "GPIO151"),
		MTK_FUNCTION(1, "SCP_SPI3_MI"),
		MTK_FUNCTION(2, "SPI3_B_MI"),
		MTK_FUNCTION(3, "MD_URXD1"),
		MTK_FUNCTION(4, "MD32PCM_URXD_AO_VLP"),
		MTK_FUNCTION(5, "CONN_BG_GPS_MCU_UART1_RXD"),
		MTK_FUNCTION(6, "SPU1_URX"),
		MTK_FUNCTION(7, "HFRP_URXD1"),
		MTK_FUNCTION(8, "IOBIST151")
	),
	MTK_PIN_NODRV(
		152, "GPIO152",
		MTK_EINT_FUNCTION(0, 152),
		MTK_FUNCTION(0, "GPIO152"),
		MTK_FUNCTION(1, "SPI1_CLK"),
		MTK_FUNCTION(2, "PWM_0"),
		MTK_FUNCTION(3, "MD_UCTS0"),
		MTK_FUNCTION(5, "CCU0_UTXD"),
		MTK_FUNCTION(6, "SPU0_GPIO_O"),
		MTK_FUNCTION(8, "IOBIST152")
	),
	MTK_PIN_NODRV(
		153, "GPIO153",
		MTK_EINT_FUNCTION(0, 153),
		MTK_FUNCTION(0, "GPIO153"),
		MTK_FUNCTION(1, "SPI1_CSB"),
		MTK_FUNCTION(2, "PWM_1"),
		MTK_FUNCTION(3, "MD_URTS0"),
		MTK_FUNCTION(5, "CCU0_URXD"),
		MTK_FUNCTION(6, "SPU0_GPIO_I"),
		MTK_FUNCTION(8, "IOBIST153")
	),
	MTK_PIN_NODRV(
		154, "GPIO154",
		MTK_EINT_FUNCTION(0, 154),
		MTK_FUNCTION(0, "GPIO154"),
		MTK_FUNCTION(1, "SPI1_MO"),
		MTK_FUNCTION(2, "PWM_2"),
		MTK_FUNCTION(3, "MD_UCTS1"),
		MTK_FUNCTION(5, "CCU0_URTS"),
		MTK_FUNCTION(6, "SPU1_GPIO_O"),
		MTK_FUNCTION(8, "IOBIST154")
	),
	MTK_PIN_NODRV(
		155, "GPIO155",
		MTK_EINT_FUNCTION(0, 155),
		MTK_FUNCTION(0, "GPIO155"),
		MTK_FUNCTION(1, "SPI1_MI"),
		MTK_FUNCTION(2, "PWM_3"),
		MTK_FUNCTION(3, "MD_URTS1"),
		MTK_FUNCTION(5, "CCU0_UCTS"),
		MTK_FUNCTION(6, "SPU1_GPIO_I"),
		MTK_FUNCTION(8, "IOBIST155")
	),
	MTK_PIN_NODRV(
		156, "GPIO156",
		MTK_EINT_FUNCTION(0, 156),
		MTK_FUNCTION(0, "GPIO156"),
		MTK_FUNCTION(1, "SPI0_SPU_CLK"),
		MTK_FUNCTION(2, "SPI4_A_CLK"),
		MTK_FUNCTION(3, "MD_UTXD2"),
		MTK_FUNCTION(4, "CONN_BG_GPS_MCU_DBG_UART_TX"),
		MTK_FUNCTION(5, "CCU1_UTXD"),
		MTK_FUNCTION(6, "SPU0_SCL"),
		MTK_FUNCTION(8, "IOBIST156")
	),
	MTK_PIN_NODRV(
		157, "GPIO157",
		MTK_EINT_FUNCTION(0, 157),
		MTK_FUNCTION(0, "GPIO157"),
		MTK_FUNCTION(1, "SPI0_SPU_CSB"),
		MTK_FUNCTION(2, "SPI4_A_CSB"),
		MTK_FUNCTION(3, "MD_URXD2"),
		MTK_FUNCTION(5, "CCU1_URXD"),
		MTK_FUNCTION(8, "IOBIST157")
	),
	MTK_PIN_NODRV(
		158, "GPIO158",
		MTK_EINT_FUNCTION(0, 158),
		MTK_FUNCTION(0, "GPIO158"),
		MTK_FUNCTION(1, "SPI0_SPU_MO"),
		MTK_FUNCTION(2, "SPI4_A_MO"),
		MTK_FUNCTION(3, "MD_UCTS2"),
		MTK_FUNCTION(4, "EMI_INFRA_RV33_UTXD_AO_VCOR"),
		MTK_FUNCTION(5, "CCU1_URTS"),
		MTK_FUNCTION(6, "SPU0_SDA"),
		MTK_FUNCTION(8, "IOBIST158")
	),
	MTK_PIN_NODRV(
		159, "GPIO159",
		MTK_EINT_FUNCTION(0, 159),
		MTK_FUNCTION(0, "GPIO159"),
		MTK_FUNCTION(1, "SPI0_SPU_MI"),
		MTK_FUNCTION(2, "SPI4_A_MI"),
		MTK_FUNCTION(3, "MD_URTS2"),
		MTK_FUNCTION(4, "EMI_INFRA_RV33_URXD_AO_VCOR"),
		MTK_FUNCTION(5, "CCU1_UCTS"),
		MTK_FUNCTION(8, "IOBIST159")
	),
	MTK_PIN_NODRV(
		160, "GPIO160",
		MTK_EINT_FUNCTION(0, 160),
		MTK_FUNCTION(0, "GPIO160"),
		MTK_FUNCTION(1, "SCP_SCL0"),
		MTK_FUNCTION(2, "SCL11"),
		MTK_FUNCTION(8, "IOBIST160")
	),
	MTK_PIN_NODRV(
		161, "GPIO161",
		MTK_EINT_FUNCTION(0, 161),
		MTK_FUNCTION(0, "GPIO161"),
		MTK_FUNCTION(1, "SCP_SDA0"),
		MTK_FUNCTION(2, "SDA11"),
		MTK_FUNCTION(8, "IOBIST161")
	),
	MTK_PIN_NODRV(
		162, "GPIO162",
		MTK_EINT_FUNCTION(0, 162),
		MTK_FUNCTION(0, "GPIO162"),
		MTK_FUNCTION(1, "SCP_SCL2"),
		MTK_FUNCTION(2, "SCL12"),
		MTK_FUNCTION(8, "IOBIST162")
	),
	MTK_PIN_NODRV(
		163, "GPIO163",
		MTK_EINT_FUNCTION(0, 163),
		MTK_FUNCTION(0, "GPIO163"),
		MTK_FUNCTION(1, "SCP_SDA2"),
		MTK_FUNCTION(2, "SDA12"),
		MTK_FUNCTION(8, "IOBIST163")
	),
	MTK_PIN_NODRV(
		164, "GPIO164",
		MTK_EINT_FUNCTION(0, 164),
		MTK_FUNCTION(0, "GPIO164"),
		MTK_FUNCTION(1, "SCP_SPI2_CK"),
		MTK_FUNCTION(2, "SPI2_B_CLK"),
		MTK_FUNCTION(8, "IOBIST164")
	),
	MTK_PIN_NODRV(
		165, "GPIO165",
		MTK_EINT_FUNCTION(0, 165),
		MTK_FUNCTION(0, "GPIO165"),
		MTK_FUNCTION(1, "SCP_SPI2_CS"),
		MTK_FUNCTION(2, "SPI2_B_CSB"),
		MTK_FUNCTION(8, "IOBIST165")
	),
	MTK_PIN_NODRV(
		166, "GPIO166",
		MTK_EINT_FUNCTION(0, 166),
		MTK_FUNCTION(0, "GPIO166"),
		MTK_FUNCTION(1, "SCP_SPI2_MO"),
		MTK_FUNCTION(2, "SPI2_B_MO"),
		MTK_FUNCTION(8, "IOBIST166")
	),
	MTK_PIN_NODRV(
		167, "GPIO167",
		MTK_EINT_FUNCTION(0, 167),
		MTK_FUNCTION(0, "GPIO167"),
		MTK_FUNCTION(1, "SCP_SPI2_MI"),
		MTK_FUNCTION(2, "SPI2_B_MI"),
		MTK_FUNCTION(8, "IOBIST167")
	),
	MTK_PIN_NODRV(
		168, "GPIO168",
		MTK_EINT_FUNCTION(0, 168),
		MTK_FUNCTION(0, "GPIO168"),
		MTK_FUNCTION(1, "CMFLASH2"),
		MTK_FUNCTION(2, "PWM_2"),
		MTK_FUNCTION(3, "SPI4_B_MI"),
		MTK_FUNCTION(8, "IOBIST168")
	),
	MTK_PIN_NODRV(
		169, "GPIO169",
		MTK_EINT_FUNCTION(0, 169),
		MTK_FUNCTION(0, "GPIO169"),
		MTK_FUNCTION(1, "CMFLASH3"),
		MTK_FUNCTION(2, "PWM_3"),
		MTK_FUNCTION(3, "SPI4_B_MO"),
		MTK_FUNCTION(4, "MD_GPS_BLANK"),
		MTK_FUNCTION(8, "IOBIST169")
	),
	MTK_PIN_NODRV(
		170, "GPIO170",
		MTK_EINT_FUNCTION(0, 170),
		MTK_FUNCTION(0, "GPIO170"),
		MTK_FUNCTION(1, "MD_GPS_BLANK"),
		MTK_FUNCTION(6, "TP_GPIO12_AO"),
		MTK_FUNCTION(8, "IOBIST170")
	),
	MTK_PIN_NODRV(
		171, "GPIO171",
		MTK_EINT_FUNCTION(0, 171),
		MTK_FUNCTION(0, "GPIO171"),
		MTK_FUNCTION(1, "MD_INT0"),
		MTK_FUNCTION(6, "TP_GPIO13_AO"),
		MTK_FUNCTION(8, "IOBIST171")
	),
	MTK_PIN_NODRV(
		172, "GPIO172",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO172"),
		MTK_FUNCTION(1, "SCL2"),
		MTK_FUNCTION(2, "SCP_SCL8"),
		MTK_FUNCTION(6, "TP_GPIO14_AO"),
		MTK_FUNCTION(8, "IOBIST172")
	),
	MTK_PIN_NODRV(
		173, "GPIO173",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO173"),
		MTK_FUNCTION(1, "SDA2"),
		MTK_FUNCTION(2, "SCP_SDA8"),
		MTK_FUNCTION(6, "TP_GPIO15_AO"),
		MTK_FUNCTION(8, "IOBIST173")
	),
	MTK_PIN_NODRV(
		174, "GPIO174",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO174"),
		MTK_FUNCTION(1, "SCL4"),
		MTK_FUNCTION(2, "SCP_SCL9"),
		MTK_FUNCTION(8, "IOBIST174")
	),
	MTK_PIN_NODRV(
		175, "GPIO175",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO175"),
		MTK_FUNCTION(1, "SDA4"),
		MTK_FUNCTION(2, "SCP_SDA9"),
		MTK_FUNCTION(8, "IOBIST175")
	),
	MTK_PIN_NODRV(
		176, "GPIO176",
		MTK_EINT_FUNCTION(0, 176),
		MTK_FUNCTION(0, "GPIO176"),
		MTK_FUNCTION(1, "CMFLASH0"),
		MTK_FUNCTION(2, "PWM_0"),
		MTK_FUNCTION(4, "VBUSVALID"),
		MTK_FUNCTION(5, "MD32_2_TXD"),
		MTK_FUNCTION(8, "IOBIST176")
	),
	MTK_PIN_NODRV(
		177, "GPIO177",
		MTK_EINT_FUNCTION(0, 177),
		MTK_FUNCTION(0, "GPIO177"),
		MTK_FUNCTION(1, "CMFLASH1"),
		MTK_FUNCTION(2, "PWM_1"),
		MTK_FUNCTION(5, "MD32_2_RXD"),
		MTK_FUNCTION(8, "IOBIST177")
	),
	MTK_PIN_NODRV(
		178, "GPIO178",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO178"),
		MTK_FUNCTION(1, "SCL5"),
		MTK_FUNCTION(2, "MD_UCTS2"),
		MTK_FUNCTION(8, "IOBIST178")
	),
	MTK_PIN_NODRV(
		179, "GPIO179",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO179"),
		MTK_FUNCTION(1, "SDA5"),
		MTK_FUNCTION(2, "MD_URTS2"),
		MTK_FUNCTION(8, "IOBIST179")
	),
	MTK_PIN_NODRV(
		180, "GPIO180",
		MTK_EINT_FUNCTION(0, 180),
		MTK_FUNCTION(0, "GPIO180"),
		MTK_FUNCTION(1, "DMIC_CLK"),
		MTK_FUNCTION(2, "SCP_DMIC_CLK"),
		MTK_FUNCTION(3, "SRCLKENAI0"),
		MTK_FUNCTION(5, "SPMI_M_TRIG_FLAG"),
		MTK_FUNCTION(8, "IOBIST180")
	),
	MTK_PIN_NODRV(
		181, "GPIO181",
		MTK_EINT_FUNCTION(0, 181),
		MTK_FUNCTION(0, "GPIO181"),
		MTK_FUNCTION(1, "DMIC_DAT"),
		MTK_FUNCTION(2, "SCP_DMIC_DAT"),
		MTK_FUNCTION(3, "SRCLKENAI1"),
		MTK_FUNCTION(5, "SPMI_P_TRIG_FLAG"),
		MTK_FUNCTION(8, "IOBIST181")
	),
	MTK_PIN_NODRV(
		182, "GPIO182",
		MTK_EINT_FUNCTION(0, 182),
		MTK_FUNCTION(0, "GPIO182"),
		MTK_FUNCTION(1, "SCL14"),
		MTK_FUNCTION(2, "CMVREF0"),
		MTK_FUNCTION(4, "GPS_PPS0"),
		MTK_FUNCTION(5, "MD32_2_GPIO0"),
		MTK_FUNCTION(8, "IOBIST182")
	),
	MTK_PIN_NODRV(
		183, "GPIO183",
		MTK_EINT_FUNCTION(0, 183),
		MTK_FUNCTION(0, "GPIO183"),
		MTK_FUNCTION(1, "SDA14"),
		MTK_FUNCTION(2, "CMVREF1"),
		MTK_FUNCTION(3, "MFG_EB_JTAG_TRSTN"),
		MTK_FUNCTION(4, "ADSP_JTAG1_TRSTN"),
		MTK_FUNCTION(5, "HFRP_JTAG1_TRSTN"),
		MTK_FUNCTION(6, "SPU1_NTRST"),
		MTK_FUNCTION(7, "CONN_BG_GPS_MCU_TRST_B"),
		MTK_FUNCTION(8, "IOBIST183")
	),
	MTK_PIN_NODRV(
		184, "GPIO184",
		MTK_EINT_FUNCTION(0, 184),
		MTK_FUNCTION(0, "GPIO184"),
		MTK_FUNCTION(1, "SCL11"),
		MTK_FUNCTION(2, "CMVREF2"),
		MTK_FUNCTION(3, "MFG_EB_JTAG_TCK"),
		MTK_FUNCTION(4, "ADSP_JTAG1_TCK"),
		MTK_FUNCTION(5, "HFRP_JTAG1_TCK"),
		MTK_FUNCTION(6, "SPU1_TCK"),
		MTK_FUNCTION(7, "CONN_BG_GPS_MCU_TCK"),
		MTK_FUNCTION(8, "IOBIST184")
	),
	MTK_PIN_NODRV(
		185, "GPIO185",
		MTK_EINT_FUNCTION(0, 185),
		MTK_FUNCTION(0, "GPIO185"),
		MTK_FUNCTION(1, "SDA11"),
		MTK_FUNCTION(2, "CMVREF3"),
		MTK_FUNCTION(3, "MFG_EB_JTAG_TMS"),
		MTK_FUNCTION(4, "ADSP_JTAG1_TMS"),
		MTK_FUNCTION(5, "HFRP_JTAG1_TMS"),
		MTK_FUNCTION(6, "SPU1_TMS"),
		MTK_FUNCTION(7, "CONN_BG_GPS_MCU_TMS"),
		MTK_FUNCTION(8, "IOBIST185")
	),
	MTK_PIN_NODRV(
		186, "GPIO186",
		MTK_EINT_FUNCTION(0, 186),
		MTK_FUNCTION(0, "GPIO186"),
		MTK_FUNCTION(1, "SCL12"),
		MTK_FUNCTION(2, "CMVREF4"),
		MTK_FUNCTION(3, "MFG_EB_JTAG_TDO"),
		MTK_FUNCTION(4, "ADSP_JTAG1_TDO"),
		MTK_FUNCTION(5, "HFRP_JTAG1_TDO"),
		MTK_FUNCTION(6, "SPU1_TDO"),
		MTK_FUNCTION(7, "CONN_BG_GPS_MCU_TDO"),
		MTK_FUNCTION(8, "IOBIST186")
	),
	MTK_PIN_NODRV(
		187, "GPIO187",
		MTK_EINT_FUNCTION(0, 187),
		MTK_FUNCTION(0, "GPIO187"),
		MTK_FUNCTION(1, "SDA12"),
		MTK_FUNCTION(2, "CMVREF5"),
		MTK_FUNCTION(3, "MFG_EB_JTAG_TDI"),
		MTK_FUNCTION(4, "ADSP_JTAG1_TDI"),
		MTK_FUNCTION(5, "HFRP_JTAG1_TDI"),
		MTK_FUNCTION(6, "SPU1_TDI"),
		MTK_FUNCTION(7, "CONN_BG_GPS_MCU_TDI"),
		MTK_FUNCTION(8, "IOBIST187")
	),
	MTK_PIN_NODRV(
		188, "GPIO188",
		MTK_EINT_FUNCTION(0, 188),
		MTK_FUNCTION(0, "GPIO188"),
		MTK_FUNCTION(1, "CMMCLK2"),
		MTK_FUNCTION(4, "AD_ILDO_DTEST0"),
		MTK_FUNCTION(8, "IOBIST188")
	),
	MTK_PIN_NODRV(
		189, "GPIO189",
		MTK_EINT_FUNCTION(0, 189),
		MTK_FUNCTION(0, "GPIO189"),
		MTK_FUNCTION(1, "GPS_PPS0"),
		MTK_FUNCTION(4, "AD_ILDO_DTEST1"),
		MTK_FUNCTION(6, "UDI_TDI_1"),
		MTK_FUNCTION(8, "IOBIST189")
	),
	MTK_PIN_NODRV(
		190, "GPIO190",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO190"),
		MTK_FUNCTION(1, "SCL7"),
		MTK_FUNCTION(2, "AGPS_SYNC"),
		MTK_FUNCTION(6, "UDI_TDI_2"),
		MTK_FUNCTION(8, "IOBIST190")
	),
	MTK_PIN_NODRV(
		191, "GPIO191",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO191"),
		MTK_FUNCTION(1, "SDA7"),
		MTK_FUNCTION(6, "UDI_TDI_3"),
		MTK_FUNCTION(8, "IOBIST191")
	),
	MTK_PIN_NODRV(
		192, "GPIO192",
		MTK_EINT_FUNCTION(0, 192),
		MTK_FUNCTION(0, "GPIO192"),
		MTK_FUNCTION(1, "CMMCLK3"),
		MTK_FUNCTION(4, "AD_ILDO_DTEST2"),
		MTK_FUNCTION(8, "IOBIST192")
	),
	MTK_PIN_NODRV(
		193, "GPIO193",
		MTK_EINT_FUNCTION(0, 193),
		MTK_FUNCTION(0, "GPIO193"),
		MTK_FUNCTION(1, "GPS_PPS1"),
		MTK_FUNCTION(2, "AGPS_SYNC"),
		MTK_FUNCTION(3, "MD32_3_GPIO0"),
		MTK_FUNCTION(4, "AD_ILDO_DTEST3"),
		MTK_FUNCTION(6, "UDI_TDI_4"),
		MTK_FUNCTION(8, "IOBIST193")
	),
	MTK_PIN_NODRV(
		194, "GPIO194",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO194"),
		MTK_FUNCTION(1, "SCL8"),
		MTK_FUNCTION(3, "MD32_3_TXD"),
		MTK_FUNCTION(6, "UDI_TDI_5"),
		MTK_FUNCTION(8, "IOBIST194")
	),
	MTK_PIN_NODRV(
		195, "GPIO195",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO195"),
		MTK_FUNCTION(1, "SDA8"),
		MTK_FUNCTION(3, "MD32_3_RXD"),
		MTK_FUNCTION(6, "UDI_TDI_6"),
		MTK_FUNCTION(8, "IOBIST195")
	),
	MTK_PIN_NODRV(
		196, "GPIO196",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO196"),
		MTK_FUNCTION(1, "SCL1"),
		MTK_FUNCTION(8, "IOBIST196")
	),
	MTK_PIN_NODRV(
		197, "GPIO197",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO197"),
		MTK_FUNCTION(1, "SDA1"),
		MTK_FUNCTION(8, "IOBIST197")
	),
	MTK_PIN_NODRV(
		198, "GPIO198",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO198"),
		MTK_FUNCTION(1, "SCP_SCL3"),
		MTK_FUNCTION(2, "SCL13"),
		MTK_FUNCTION(6, "UDI_TDI_7"),
		MTK_FUNCTION(8, "IOBIST198")
	),
	MTK_PIN_NODRV(
		199, "GPIO199",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO199"),
		MTK_FUNCTION(1, "SCP_SDA3"),
		MTK_FUNCTION(2, "SDA13"),
		MTK_FUNCTION(6, "UDI_TDO_7"),
		MTK_FUNCTION(8, "IOBIST199")
	),
	MTK_PIN_NODRV(
		200, "GPIO200",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO200"),
		MTK_FUNCTION(1, "SCL9"),
		MTK_FUNCTION(2, "SCP_SCL7"),
		MTK_FUNCTION(6, "TP_GPIO8_AO"),
		MTK_FUNCTION(8, "IOBIST200")
	),
	MTK_PIN_NODRV(
		201, "GPIO201",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO201"),
		MTK_FUNCTION(1, "SDA9"),
		MTK_FUNCTION(2, "SCP_SDA7"),
		MTK_FUNCTION(6, "TP_GPIO9_AO"),
		MTK_FUNCTION(8, "IOBIST201")
	),
	MTK_PIN_NODRV(
		202, "GPIO202",
		MTK_EINT_FUNCTION(0, 202),
		MTK_FUNCTION(0, "GPIO202"),
		MTK_FUNCTION(1, "SCL13"),
		MTK_FUNCTION(2, "CMVREF6"),
		MTK_FUNCTION(3, "MD_INT3"),
		MTK_FUNCTION(4, "GPS_L1_ELNA_EN"),
		MTK_FUNCTION(6, "TP_GPIO10_AO"),
		MTK_FUNCTION(8, "IOBIST202")
	),
	MTK_PIN_NODRV(
		203, "GPIO203",
		MTK_EINT_FUNCTION(0, 203),
		MTK_FUNCTION(0, "GPIO203"),
		MTK_FUNCTION(1, "SDA13"),
		MTK_FUNCTION(2, "CMVREF7"),
		MTK_FUNCTION(3, "MD_INT4"),
		MTK_FUNCTION(4, "GPS_L5_ELNA_EN"),
		MTK_FUNCTION(6, "TP_GPIO11_AO"),
		MTK_FUNCTION(8, "IOBIST203")
	),
	MTK_PIN_NODRV(
		204, "GPIO204",
		MTK_EINT_FUNCTION(0, 204),
		MTK_FUNCTION(0, "GPIO204"),
		MTK_FUNCTION(1, "MD_GPS_BLANK"),
		MTK_FUNCTION(4, "AD_ILDO_DTEST4"),
		MTK_FUNCTION(6, "UDI_TDO_1"),
		MTK_FUNCTION(8, "IOBIST204")
	),
	MTK_PIN_NODRV(
		205, "GPIO205",
		MTK_EINT_FUNCTION(0, 205),
		MTK_FUNCTION(0, "GPIO205"),
		MTK_FUNCTION(1, "MD_INT0"),
		MTK_FUNCTION(2, "PCIE_CLKREQN_1P"),
		MTK_FUNCTION(3, "PMSR_SMAP"),
		MTK_FUNCTION(4, "AD_ILDO_DTEST5"),
		MTK_FUNCTION(6, "UDI_TDO_2"),
		MTK_FUNCTION(8, "IOBIST205")
	),
	MTK_PIN_NODRV(
		206, "GPIO206",
		MTK_EINT_FUNCTION(0, 206),
		MTK_FUNCTION(0, "GPIO206"),
		MTK_FUNCTION(1, "GPS_L1_ELNA_EN"),
		MTK_FUNCTION(2, "PCIE_WAKEN_1P"),
		MTK_FUNCTION(3, "PMSR_SMAP_MAX"),
		MTK_FUNCTION(4, "AD_ILDO_DTEST6"),
		MTK_FUNCTION(6, "UDI_TDO_3"),
		MTK_FUNCTION(8, "IOBIST206")
	),
	MTK_PIN_NODRV(
		207, "GPIO207",
		MTK_EINT_FUNCTION(0, 207),
		MTK_FUNCTION(0, "GPIO207"),
		MTK_FUNCTION(1, "GPS_L5_ELNA_EN"),
		MTK_FUNCTION(2, "PCIE_PERSTN_1P"),
		MTK_FUNCTION(3, "PMSR_SMAP_MAX_W"),
		MTK_FUNCTION(4, "AD_ILDO_DTEST7"),
		MTK_FUNCTION(6, "UDI_TDO_4"),
		MTK_FUNCTION(8, "IOBIST207")
	),
	MTK_PIN_NODRV(
		208, "GPIO208",
		MTK_EINT_FUNCTION(0, 208),
		MTK_FUNCTION(0, "GPIO208"),
		MTK_FUNCTION(1, "CMMCLK4"),
		MTK_FUNCTION(4, "SCP_ILDO_DTEST1_VLP"),
		MTK_FUNCTION(8, "IOBIST208")
	),
	MTK_PIN_NODRV(
		209, "GPIO209",
		MTK_EINT_FUNCTION(0, 209),
		MTK_FUNCTION(0, "GPIO209"),
		MTK_FUNCTION(1, "CMMCLK5"),
		MTK_FUNCTION(4, "SCP_ILDO_DTEST2_VLP"),
		MTK_FUNCTION(8, "IOBIST209")
	),
	MTK_PIN_NODRV(
		210, "GPIO210",
		MTK_EINT_FUNCTION(0, 210),
		MTK_FUNCTION(0, "GPIO210"),
		MTK_FUNCTION(1, "CMMCLK6"),
		MTK_FUNCTION(3, "LCM1_RST"),
		MTK_FUNCTION(4, "SCP_ILDO_DTEST3_VLP"),
		MTK_FUNCTION(5, "IDDIG"),
		MTK_FUNCTION(6, "UDI_TDO_5"),
		MTK_FUNCTION(8, "IOBIST210")
	),
	MTK_PIN_NODRV(
		211, "GPIO211",
		MTK_EINT_FUNCTION(0, 211),
		MTK_FUNCTION(0, "GPIO211"),
		MTK_FUNCTION(1, "CMMCLK7"),
		MTK_FUNCTION(2, "MD_INT0"),
		MTK_FUNCTION(3, "DSI1_TE"),
		MTK_FUNCTION(4, "SCP_ILDO_DTEST4_VLP"),
		MTK_FUNCTION(5, "USB_DRVVBUS"),
		MTK_FUNCTION(6, "UDI_TDO_6"),
		MTK_FUNCTION(8, "IOBIST211")
	),
	MTK_PIN_NODRV(
		212, "GPIO212",
		MTK_EINT_FUNCTION(0, 212),
		MTK_FUNCTION(0, "GPIO212"),
		MTK_FUNCTION(1, "MSDC2_CLK"),
		MTK_FUNCTION(2, "MD32_1_TXD"),
		MTK_FUNCTION(5, "CLKM0_A"),
		MTK_FUNCTION(8, "IOBIST212")
	),
	MTK_PIN_NODRV(
		213, "GPIO213",
		MTK_EINT_FUNCTION(0, 213),
		MTK_FUNCTION(0, "GPIO213"),
		MTK_FUNCTION(1, "MSDC2_CMD"),
		MTK_FUNCTION(2, "MD32_1_RXD"),
		MTK_FUNCTION(5, "CLKM1_A"),
		MTK_FUNCTION(8, "IOBIST213")
	),
	MTK_PIN_NODRV(
		214, "GPIO214",
		MTK_EINT_FUNCTION(0, 214),
		MTK_FUNCTION(0, "GPIO214"),
		MTK_FUNCTION(1, "MSDC2_DAT0"),
		MTK_FUNCTION(2, "MD32_1_GPIO0"),
		MTK_FUNCTION(5, "CLKM2_A"),
		MTK_FUNCTION(8, "IOBIST214")
	),
	MTK_PIN_NODRV(
		215, "GPIO215",
		MTK_EINT_FUNCTION(0, 215),
		MTK_FUNCTION(0, "GPIO215"),
		MTK_FUNCTION(1, "MSDC2_DAT1"),
		MTK_FUNCTION(5, "CLKM3_A"),
		MTK_FUNCTION(8, "IOBIST215")
	),
	MTK_PIN_NODRV(
		216, "GPIO216",
		MTK_EINT_FUNCTION(0, 216),
		MTK_FUNCTION(0, "GPIO216"),
		MTK_FUNCTION(1, "MSDC2_DAT2"),
		MTK_FUNCTION(2, "CONN_TCXOENA_REQ"),
		MTK_FUNCTION(4, "MD_PSP_STOP"),
		MTK_FUNCTION(5, "CLKM0_B"),
		MTK_FUNCTION(6, "CONN_BG_GPS_MCU_AICE_TCKC"),
		MTK_FUNCTION(8, "IOBIST216")
	),
	MTK_PIN_NODRV(
		217, "GPIO217",
		MTK_EINT_FUNCTION(0, 217),
		MTK_FUNCTION(0, "GPIO217"),
		MTK_FUNCTION(1, "MSDC2_DAT3"),
		MTK_FUNCTION(4, "MD_PSP_FRC"),
		MTK_FUNCTION(5, "CLKM1_B"),
		MTK_FUNCTION(6, "CONN_BG_GPS_MCU_AICE_TMSC"),
		MTK_FUNCTION(8, "IOBIST217")
	),
	MTK_PIN_NODRV(
		218, "GPIO218",
		MTK_EINT_FUNCTION(0, 218),
		MTK_FUNCTION(0, "GPIO218"),
		MTK_FUNCTION(1, "SCP_SCL4_OIS"),
		MTK_FUNCTION(2, "PWM_VLP"),
		MTK_FUNCTION(3, "DSI_ERR_FLG"),
		MTK_FUNCTION(6, "TP_GPIO0_AO"),
		MTK_FUNCTION(8, "IOBIST218")
	),
	MTK_PIN_NODRV(
		219, "GPIO219",
		MTK_EINT_FUNCTION(0, 219),
		MTK_FUNCTION(0, "GPIO219"),
		MTK_FUNCTION(1, "SCP_SDA4_OIS"),
		MTK_FUNCTION(3, "DSI1_ERR_FLG"),
		MTK_FUNCTION(6, "TP_GPIO1_AO"),
		MTK_FUNCTION(8, "IOBIST219")
	),
	MTK_PIN_NODRV(
		220, "GPIO220",
		MTK_EINT_FUNCTION(0, 220),
		MTK_FUNCTION(0, "GPIO220"),
		MTK_FUNCTION(1, "SCP_SCL5_OIS"),
		MTK_FUNCTION(2, "PWM_VLP"),
		MTK_FUNCTION(3, "DSI1_HSYNC"),
		MTK_FUNCTION(4, "UTXD3"),
		MTK_FUNCTION(6, "TP_GPIO2_AO"),
		MTK_FUNCTION(8, "IOBIST220")
	),
	MTK_PIN_NODRV(
		221, "GPIO221",
		MTK_EINT_FUNCTION(0, 221),
		MTK_FUNCTION(0, "GPIO221"),
		MTK_FUNCTION(1, "SCP_SDA5_OIS"),
		MTK_FUNCTION(3, "DSI1_TE"),
		MTK_FUNCTION(4, "URXD3"),
		MTK_FUNCTION(6, "TP_GPIO3_AO"),
		MTK_FUNCTION(8, "IOBIST221")
	),
	MTK_PIN_NODRV(
		222, "GPIO222",
		MTK_EINT_FUNCTION(0, 222),
		MTK_FUNCTION(0, "GPIO222"),
		MTK_FUNCTION(1, "SCP_SCL6"),
		MTK_FUNCTION(2, "PWM_VLP"),
		MTK_FUNCTION(3, "LCM2_RST"),
		MTK_FUNCTION(4, "DMIC2_CLK"),
		MTK_FUNCTION(5, "SCP_DMIC_CLK"),
		MTK_FUNCTION(6, "TP_GPIO4_AO"),
		MTK_FUNCTION(8, "IOBIST222")
	),
	MTK_PIN_NODRV(
		223, "GPIO223",
		MTK_EINT_FUNCTION(0, 223),
		MTK_FUNCTION(0, "GPIO223"),
		MTK_FUNCTION(1, "SCP_SDA6"),
		MTK_FUNCTION(3, "DSI2_TE"),
		MTK_FUNCTION(4, "DMIC2_DAT"),
		MTK_FUNCTION(5, "SCP_DMIC_DAT"),
		MTK_FUNCTION(6, "TP_GPIO5_AO"),
		MTK_FUNCTION(8, "IOBIST223")
	),
	MTK_PIN_NODRV(
		224, "GPIO224",
		MTK_EINT_FUNCTION(0, 224),
		MTK_FUNCTION(0, "GPIO224"),
		MTK_FUNCTION(1, "MD_INT1_C2K_UIM0_HOT_PLUG"),
		MTK_FUNCTION(6, "TP_GPIO6_AO"),
		MTK_FUNCTION(8, "IOBIST224")
	),
	MTK_PIN_NODRV(
		225, "GPIO225",
		MTK_EINT_FUNCTION(0, 225),
		MTK_FUNCTION(0, "GPIO225"),
		MTK_FUNCTION(1, "MD_INT2_C2K_UIM1_HOT_PLUG"),
		MTK_FUNCTION(4, "DSI2_HSYNC"),
		MTK_FUNCTION(6, "TP_GPIO7_AO"),
		MTK_FUNCTION(8, "IOBIST225")
	),
	MTK_PIN_NODRV(
		226, "GPIO226",
		MTK_EINT_FUNCTION(0, 226),
		MTK_FUNCTION(0, "GPIO226"),
		MTK_FUNCTION(1, "UTXD0"),
		MTK_FUNCTION(2, "MD_UTXD1"),
		MTK_FUNCTION(4, "CLKM0_B"),
		MTK_FUNCTION(5, "MBISTREADEN_TRIGGER"),
		MTK_FUNCTION(6, "CONN_BG_GPS_MCU_DBG_UART_TX"),
		MTK_FUNCTION(8, "IOBIST226")
	),
	MTK_PIN_NODRV(
		227, "GPIO227",
		MTK_EINT_FUNCTION(0, 227),
		MTK_FUNCTION(0, "GPIO227"),
		MTK_FUNCTION(1, "URXD0"),
		MTK_FUNCTION(2, "MD_URXD1"),
		MTK_FUNCTION(4, "CLKM1_B"),
		MTK_FUNCTION(5, "MBISTWRITEEN_TRIGGER"),
		MTK_FUNCTION(8, "IOBIST227")
	),
	MTK_PIN_NODRV(
		228, "GPIO228",
		MTK_EINT_FUNCTION(0, 228),
		MTK_FUNCTION(0, "GPIO228"),
		MTK_FUNCTION(1, "UTXD1"),
		MTK_FUNCTION(2, "MD_UTXD0"),
		MTK_FUNCTION(3, "TP_UTXD1_VLP"),
		MTK_FUNCTION(4, "ADSP_UTXD0"),
		MTK_FUNCTION(5, "SSPM_UTXD_AO_VLP"),
		MTK_FUNCTION(7, "CLKM0_A"),
		MTK_FUNCTION(8, "IOBIST228")
	),
	MTK_PIN_NODRV(
		229, "GPIO229",
		MTK_EINT_FUNCTION(0, 229),
		MTK_FUNCTION(0, "GPIO229"),
		MTK_FUNCTION(1, "URXD1"),
		MTK_FUNCTION(2, "MD_URXD0"),
		MTK_FUNCTION(3, "TP_URXD1_VLP"),
		MTK_FUNCTION(4, "ADSP_URXD0"),
		MTK_FUNCTION(5, "SSPM_URXD_AO_VLP"),
		MTK_FUNCTION(7, "CLKM1_A"),
		MTK_FUNCTION(8, "IOBIST229")
	),
	MTK_PIN_NODRV(
		230, "GPIO230",
		MTK_EINT_FUNCTION(0, 230),
		MTK_FUNCTION(0, "GPIO230"),
		MTK_FUNCTION(1, "DSI3_TE"),
		MTK_FUNCTION(4, "CLKM2_B"),
		MTK_FUNCTION(8, "IOBIST230")
	),
	MTK_PIN_NODRV(
		231, "GPIO231",
		MTK_EINT_FUNCTION(0, 231),
		MTK_FUNCTION(0, "GPIO231"),
		MTK_FUNCTION(1, "CONN_TCXOENA_REQ"),
		MTK_FUNCTION(4, "CLKM3_B"),
		MTK_FUNCTION(7, "DBG_MON_A21"),
		MTK_FUNCTION(8, "IOBIST231")
	),
	MTK_PIN_NODRV(
		232, "GPIO232",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO232"),
		MTK_FUNCTION(1, "CONN_TOP_CLK"),
		MTK_FUNCTION(8, "IOBIST232")
	),
	MTK_PIN_NODRV(
		233, "GPIO233",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO233"),
		MTK_FUNCTION(1, "CONN_TOP_DATA"),
		MTK_FUNCTION(8, "IOBIST233")
	),
	MTK_PIN_NODRV(
		234, "GPIO234",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO234"),
		MTK_FUNCTION(1, "CONN_HRST_B"),
		MTK_FUNCTION(8, "IOBIST234")
	),
	MTK_PIN_NODRV(
		235, "GPIO235",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO235"),
		MTK_FUNCTION(1, "PTA_TXD0"),
		MTK_FUNCTION(8, "IOBIST235")
	),
	MTK_PIN_NODRV(
		236, "GPIO236",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO236"),
		MTK_FUNCTION(1, "PTA_RXD0"),
		MTK_FUNCTION(8, "IOBIST236")
	),
	MTK_PIN_NODRV(
		237, "GPIO237",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO237"),
		MTK_FUNCTION(1, "I2SIN6_0_BCK"),
		MTK_FUNCTION(4, "CLKM2_A"),
		MTK_FUNCTION(8, "IOBIST237")
	),
	MTK_PIN_NODRV(
		238, "GPIO238",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO238"),
		MTK_FUNCTION(1, "I2SIN6_0_LRCK"),
		MTK_FUNCTION(4, "CLKM3_A"),
		MTK_FUNCTION(8, "IOBIST238")
	),
	MTK_PIN_NODRV(
		239, "GPIO239",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO239"),
		MTK_FUNCTION(1, "I2SIN6_0_DI"),
		MTK_FUNCTION(4, "CLKM2_B"),
		MTK_FUNCTION(8, "IOBIST239")
	),
	MTK_PIN_NODRV(
		240, "GPIO240",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO240"),
		MTK_FUNCTION(1, "I2SOUT6_0_DO"),
		MTK_FUNCTION(4, "CLKM3_B"),
		MTK_FUNCTION(8, "IOBIST240")
	),
	MTK_PIN_NODRV(
		241, "GPIO241",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO241"),
		MTK_FUNCTION(1, "CONN_UARTHUB_UART_TX"),
		MTK_FUNCTION(2, "UTXD3"),
		MTK_FUNCTION(8, "IOBIST241")
	),
	MTK_PIN_NODRV(
		242, "GPIO242",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO242"),
		MTK_FUNCTION(1, "CONN_UARTHUB_UART_RX"),
		MTK_FUNCTION(2, "URXD3"),
		MTK_FUNCTION(8, "IOBIST242")
	),
	MTK_PIN_NODRV(
		243, "GPIO243",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO243"),
		MTK_FUNCTION(1, "TP_UTXD_CONSYS_VLP"),
		MTK_FUNCTION(2, "TP_URXD_CONSYS_VLP"),
		MTK_FUNCTION(8, "IOBIST243")
	),
	MTK_PIN_NODRV(
		244, "GPIO244",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO244"),
		MTK_FUNCTION(1, "TP_URXD_CONSYS_VLP"),
		MTK_FUNCTION(2, "TP_UTXD_CONSYS_VLP"),
		MTK_FUNCTION(8, "IOBIST244")
	),
	MTK_PIN_NODRV(
		245, "GPIO245",
		MTK_EINT_FUNCTION(0, 245),
		MTK_FUNCTION(0, "GPIO245"),
		MTK_FUNCTION(1, "PCIE_PERSTN"),
		MTK_FUNCTION(8, "IOBIST245")
	),
	MTK_PIN_NODRV(
		246, "GPIO246",
		MTK_EINT_FUNCTION(0, 246),
		MTK_FUNCTION(0, "GPIO246"),
		MTK_FUNCTION(1, "PCIE_WAKEN"),
		MTK_FUNCTION(8, "IOBIST246")
	),
	MTK_PIN_NODRV(
		247, "GPIO247",
		MTK_EINT_FUNCTION(0, 247),
		MTK_FUNCTION(0, "GPIO247"),
		MTK_FUNCTION(1, "PCIE_CLKREQN"),
		MTK_FUNCTION(8, "IOBIST247")
	),
	MTK_PIN_NODRV(
		248, "GPIO248",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO248"),
		MTK_FUNCTION(1, "CONN_RST"),
		MTK_FUNCTION(8, "IOBIST248")
	),
	MTK_PIN_NODRV(
		249, "GPIO249",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO249"),
		MTK_FUNCTION(2, "UCTS3"),
		MTK_FUNCTION(8, "IOBIST249")
	),
	MTK_PIN_NODRV(
		250, "GPIO250",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO250"),
		MTK_FUNCTION(2, "URTS3"),
		MTK_FUNCTION(8, "IOBIST250")
	),
	MTK_PIN_NODRV(
		251, "GPIO251",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO251"),
		MTK_FUNCTION(8, "IOBIST251")
	),
	MTK_PIN_EINT(252, 252),
	MTK_PIN_EINT(253, 253),
	MTK_PIN_EINT(254, 254),
	MTK_PIN_EINT(255, 255),
	MTK_PIN_EINT(256, 256),
	MTK_PIN_EINT(257, 257),
	MTK_PIN_EINT(258, 258),
	MTK_PIN_EINT(259, 259),
	MTK_PIN_EINT(260, 260),
	MTK_PIN_EINT(261, 261),
	MTK_PIN_EINT(262, 262),
	MTK_PIN_EINT(263, 263),
	MTK_PIN_EINT(264, 264),
	MTK_PIN_EINT(265, 265),
	MTK_PIN_EINT(266, 266),
	MTK_PIN_EINT(267, 267),
	MTK_PIN_EINT(268, 268),
	MTK_PIN_EINT(269, 269),
	MTK_PIN_EINT(270, 270),
	MTK_PIN_EINT(271, 271),
	MTK_PIN_EINT(272, 272),
	MTK_PIN_EINT(273, 273),
	MTK_PIN_EINT(274, 274),
	MTK_PIN_EINT(275, 275),
};

#endif /* __PINCTRL_MTK_MT6993_H */
