load("//build/bazel_mgk_rules:mgk_ddk_ko.bzl", "define_mgk_ddk_ko")
load("//build/kernel/kleaf:kernel.bzl", "ddk_headers")
load("@mgk_info//:kernel_version.bzl", "kernel_version")

package(
    default_visibility = [
        "//visibility:public",
    ],
)

filegroup(
    name = "ddk_kconfigs",
    srcs = glob([
        "**/Kconfig",
    ]),
)

filegroup(
    name = "srcs",
    srcs = glob([
          "**/Makefile",
          "**/Kbuild",
          "**/*.c",
          "**/*.h",
    ]),
)

define_mgk_ddk_ko(
    name = "snd-soc-audiodsp-common",
    srcs = [
        "audio_buf.c",
        "mtk-dsp-dai.c",
        "mtk-dsp-pcm.c",
        "mtk-dsp-common.c",
        "mtk-dsp-platform-driver.c",
        "mtk-dsp-mem-control.c",
    ],
    conditional_srcs = {
        "CONFIG_DEVICE_MODULES_VHOST_ADSP": {
            True: ["mtk-dsp-platform-driver-auto.c"],
        },
    },
    includes = [
        ".",
    ],
    hdrs = glob([
        "*.h",
    ]),
    local_defines = [
        "CONFIG_OPLUS_FEATURE_MM_FEEDBACK",
    ],
    copts = [
        "-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include/",
    ],
    header_deps = [
        "//kernel_device_modules-{}/sound/soc/mediatek/common:ddk_public_headers".format(kernel_version),
    ],
    ko_deps = [
        "//kernel_device_modules-{}/drivers/misc/mediatek/adsp:adsp".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/aee/aed:aee_aed".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/audio_ipi:audio_ipi".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/irq_monitor:irq_monitor".format(kernel_version),
        "//kernel_device_modules-{}/sound/soc/mediatek/common:mtk-afe-external".format(kernel_version),
        "//kernel_device_modules-{}/sound/soc/codecs/multimedia/feedback/bazel:oplus_mm_kevent_fb".format(kernel_version),
    ],
)

define_mgk_ddk_ko(
    name = "mtk-soc-offload-common",
    srcs = [
        "mtk-soc-offload-common.c",
        "mtk-auddrv-offloadcommon.h",
    ],
    includes = [
        ".",
    ],
    copts = [
        "-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/audio_ipi/include",
        "-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include",
        "-I$(DEVICE_MODULES_PATH)/sound/soc/mediatek/audio_dsp",
    ],
    header_deps = [
        "//kernel_device_modules-{}/sound/soc/mediatek/common:ddk_public_headers".format(kernel_version),
    ],
    ko_deps = [
        "//kernel_device_modules-{}/drivers/misc/mediatek/adsp:adsp".format(kernel_version),
		"//kernel_device_modules-{}/drivers/misc/mediatek/audio_ipi:audio_ipi".format(kernel_version),
		"//kernel_device_modules-{}/sound/soc/mediatek/audio_dsp:snd-soc-audiodsp-common".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/slbc:mtk_slbc".format(kernel_version),
        "//kernel_device_modules-{}/sound/soc/mediatek/common:mtk-afe-external".format(kernel_version),
	],
)
