// SPDX-License-Identifier: GPL-2.0
/*
 * Copyright (c) 2024 MediaTek Inc.
 */

#include <linux/io.h>

#include <mt6993_dcm_internal.h>
#include <mt6993_dcm_autogen.h>
#include <mtk_dcm.h>
#define MCUSYS_PAR_WRAP_MCU_L3C_DCM_REG0_MASK ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_L3C_DCM_REG0_ON ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_L3C_DCM_REG0_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_l3c_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(CLUSTER0_MCUSYS_MST_VLP_L3_SHARE_DCM_CTRL) &
		MCUSYS_PAR_WRAP_MCU_L3C_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_L3C_DCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_l3c_dcm(int on)
{
	if (on) {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_L3_SHARE_DCM_CTRL,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_L3_SHARE_DCM_CTRL) &
			~MCUSYS_PAR_WRAP_MCU_L3C_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_L3C_DCM_REG0_ON);
	} else {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_L3_SHARE_DCM_CTRL,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_L3_SHARE_DCM_CTRL) &
			~MCUSYS_PAR_WRAP_MCU_L3C_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_L3C_DCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_STALLDCM_REG0_MASK ((0x3fffU << 0))
#define MCUSYS_PAR_WRAP_MCU_STALLDCM_REG0_ON ((0xffU << 0))
#define MCUSYS_PAR_WRAP_MCU_STALLDCM_REG0_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_stalldcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(CLUSTER0_MCUSYS_MST_VLP_DSU_DCM_CFG) &
		MCUSYS_PAR_WRAP_MCU_STALLDCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_STALLDCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_stalldcm(int on)
{
	if (on) {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_DSU_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_DSU_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_STALLDCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_STALLDCM_REG0_ON);
	} else {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_DSU_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_DSU_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_STALLDCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_STALLDCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG0_MASK ((0x1U << 14))
#define MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG1_MASK ((0xfU << 3))
#define MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG2_MASK ((0xffU << 2))
#define MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG3_MASK ((0xe07ffU << 0))
#define MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG4_MASK ((0x3U << 0))
#define MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG0_ON ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG1_ON ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG2_ON ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG3_ON ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG4_ON ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG0_OFF ((0x1U << 14))
#define MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG1_OFF ((0xfU << 3))
#define MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG2_OFF ((0xffU << 2))
#define MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG3_OFF ((0xe07ffU << 0))
#define MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG4_OFF ((0x3U << 0))

bool dcm_mcusys_par_wrap_mcu_vdnr_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(CLUSTER0_MCUSYS_MST_VLP_DSU_DCM_CFG) &
		MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG0_ON);
	ret &= ((reg_read(CLUSTER0_MCUSYS_MST_VLP_MPSYS_DCM_CFG) &
		MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG1_MASK) ==
		MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG1_ON);
	ret &= ((reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_SLV_VPS_DCM_CFG) &
		MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG2_MASK) ==
		MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG2_ON);
	ret &= ((reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_AO_DCM_CFG) &
		MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG3_MASK) ==
		MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG3_ON);
	ret &= ((reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_DCM_CFG) &
		MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG4_MASK) ==
		MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG4_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_vdnr_dcm(int on)
{
	if (on) {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_DSU_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_DSU_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG0_ON);
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MPSYS_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MPSYS_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG1_ON);
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_SLV_VPS_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_SLV_VPS_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG2_MASK) |
			MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG2_ON);
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_AO_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_AO_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG3_MASK) |
			MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG3_ON);
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG4_MASK) |
			MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG4_ON);
	} else {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_DSU_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_DSU_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG0_OFF);
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MPSYS_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MPSYS_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG1_OFF);
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_SLV_VPS_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_SLV_VPS_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG2_MASK) |
			MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG2_OFF);
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_AO_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_AO_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG3_MASK) |
			MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG3_OFF);
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG4_MASK) |
			MCUSYS_PAR_WRAP_MCU_VDNR_DCM_REG4_OFF);
	}
}

#define MCUSYS_PAR_WRAP_DSU_BUS_DCM_REG0_MASK ((0x1U << 15))
#define MCUSYS_PAR_WRAP_DSU_BUS_DCM_REG0_ON ((0x1U << 15))
#define MCUSYS_PAR_WRAP_DSU_BUS_DCM_REG0_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_dsu_bus_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(CLUSTER0_MCUSYS_MST_VLP_DSU_DCM_CFG) &
		MCUSYS_PAR_WRAP_DSU_BUS_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_DSU_BUS_DCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_dsu_bus_dcm(int on)
{
	if (on) {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_DSU_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_DSU_DCM_CFG) &
			~MCUSYS_PAR_WRAP_DSU_BUS_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_DSU_BUS_DCM_REG0_ON);
	} else {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_DSU_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_DSU_DCM_CFG) &
			~MCUSYS_PAR_WRAP_DSU_BUS_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_DSU_BUS_DCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_APB_DCM_REG0_MASK ((0x1U << 16))
#define MCUSYS_PAR_WRAP_MCU_APB_DCM_REG1_MASK ((0x2001U << 0))
#define MCUSYS_PAR_WRAP_MCU_APB_DCM_REG2_MASK ((0x1U << 11))
#define MCUSYS_PAR_WRAP_MCU_APB_DCM_REG3_MASK ((0x1U << 12))
#define MCUSYS_PAR_WRAP_MCU_APB_DCM_REG0_ON ((0x1U << 16))
#define MCUSYS_PAR_WRAP_MCU_APB_DCM_REG1_ON ((0x2001U << 0))
#define MCUSYS_PAR_WRAP_MCU_APB_DCM_REG2_ON ((0x1U << 11))
#define MCUSYS_PAR_WRAP_MCU_APB_DCM_REG3_ON ((0x1U << 12))
#define MCUSYS_PAR_WRAP_MCU_APB_DCM_REG0_OFF ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_APB_DCM_REG1_OFF ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_APB_DCM_REG2_OFF ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_APB_DCM_REG3_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_apb_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(CLUSTER0_MCUSYS_MST_VLP_DSU_DCM_CFG) &
		MCUSYS_PAR_WRAP_MCU_APB_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_APB_DCM_REG0_ON);
	ret &= ((reg_read(CLUSTER0_MCUSYS_MST_VLP_MPSYS_DCM_CFG) &
		MCUSYS_PAR_WRAP_MCU_APB_DCM_REG1_MASK) ==
		MCUSYS_PAR_WRAP_MCU_APB_DCM_REG1_ON);
	ret &= ((reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_SLV_VPS_DCM_CFG) &
		MCUSYS_PAR_WRAP_MCU_APB_DCM_REG2_MASK) ==
		MCUSYS_PAR_WRAP_MCU_APB_DCM_REG2_ON);
	ret &= ((reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_AO_DCM_CFG) &
		MCUSYS_PAR_WRAP_MCU_APB_DCM_REG3_MASK) ==
		MCUSYS_PAR_WRAP_MCU_APB_DCM_REG3_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_apb_dcm(int on)
{
	if (on) {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_DSU_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_DSU_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_APB_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_APB_DCM_REG0_ON);
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MPSYS_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MPSYS_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_APB_DCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_MCU_APB_DCM_REG1_ON);
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_SLV_VPS_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_SLV_VPS_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_APB_DCM_REG2_MASK) |
			MCUSYS_PAR_WRAP_MCU_APB_DCM_REG2_ON);
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_AO_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_AO_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_APB_DCM_REG3_MASK) |
			MCUSYS_PAR_WRAP_MCU_APB_DCM_REG3_ON);
	} else {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_DSU_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_DSU_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_APB_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_APB_DCM_REG0_OFF);
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MPSYS_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MPSYS_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_APB_DCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_MCU_APB_DCM_REG1_OFF);
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_SLV_VPS_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_SLV_VPS_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_APB_DCM_REG2_MASK) |
			MCUSYS_PAR_WRAP_MCU_APB_DCM_REG2_OFF);
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_AO_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_AO_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_APB_DCM_REG3_MASK) |
			MCUSYS_PAR_WRAP_MCU_APB_DCM_REG3_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_CDB_DCM_REG0_MASK ((0x3U << 1))
#define MCUSYS_PAR_WRAP_MCU_CDB_DCM_REG0_ON ((0x3U << 1))
#define MCUSYS_PAR_WRAP_MCU_CDB_DCM_REG0_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_cdb_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(CLUSTER0_MCUSYS_MST_VLP_MPSYS_DCM_CFG) &
		MCUSYS_PAR_WRAP_MCU_CDB_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_CDB_DCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_cdb_dcm(int on)
{
	if (on) {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MPSYS_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MPSYS_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_CDB_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_CDB_DCM_REG0_ON);
	} else {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MPSYS_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MPSYS_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_CDB_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_CDB_DCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG0_MASK ((0x3fU << 7))
#define MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG1_MASK ((0x3U << 0))
#define MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG2_MASK ((0x7U << 13))
#define MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG0_ON ((0x3fU << 7))
#define MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG1_ON ((0x3U << 0))
#define MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG2_ON ((0x7U << 13))
#define MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG0_OFF ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG1_OFF ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG2_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_adb_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(CLUSTER0_MCUSYS_MST_VLP_MPSYS_DCM_CFG) &
		MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG0_ON);
	ret &= ((reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_SLV_VPS_DCM_CFG) &
		MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG1_MASK) ==
		MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG1_ON);
	ret &= ((reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_AO_DCM_CFG) &
		MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG2_MASK) ==
		MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG2_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_adb_dcm(int on)
{
	if (on) {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MPSYS_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MPSYS_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG0_ON);
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_SLV_VPS_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_SLV_VPS_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG1_ON);
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_AO_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_AO_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG2_MASK) |
			MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG2_ON);
	} else {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MPSYS_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MPSYS_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG0_OFF);
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_SLV_VPS_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_SLV_VPS_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG1_OFF);
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_AO_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_AO_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG2_MASK) |
			MCUSYS_PAR_WRAP_MCU_ADB_DCM_REG2_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_SLV_VC_BUS_DCM_REG0_MASK ((0x7U << 0))
#define MCUSYS_PAR_WRAP_MCU_SLV_VC_BUS_DCM_REG0_ON ((0x7U << 0))
#define MCUSYS_PAR_WRAP_MCU_SLV_VC_BUS_DCM_REG0_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_slv_vc_bus_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_SLV_VC_DCM_CFG) &
		MCUSYS_PAR_WRAP_MCU_SLV_VC_BUS_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_SLV_VC_BUS_DCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_slv_vc_bus_dcm(int on)
{
	if (on) {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_SLV_VC_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_SLV_VC_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_SLV_VC_BUS_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_SLV_VC_BUS_DCM_REG0_ON);
	} else {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_SLV_VC_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_SLV_VC_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_SLV_VC_BUS_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_SLV_VC_BUS_DCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_SLV_VPS_BUS_DCM_REG0_MASK ((0x1U << 10))
#define MCUSYS_PAR_WRAP_MCU_SLV_VPS_BUS_DCM_REG0_ON ((0x1U << 10))
#define MCUSYS_PAR_WRAP_MCU_SLV_VPS_BUS_DCM_REG0_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_slv_vps_bus_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_SLV_VPS_DCM_CFG) &
		MCUSYS_PAR_WRAP_MCU_SLV_VPS_BUS_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_SLV_VPS_BUS_DCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_slv_vps_bus_dcm(int on)
{
	if (on) {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_SLV_VPS_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_SLV_VPS_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_SLV_VPS_BUS_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_SLV_VPS_BUS_DCM_REG0_ON);
	} else {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_SLV_VPS_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_SLV_VPS_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_SLV_VPS_BUS_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_SLV_VPS_BUS_DCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_DBGNW_DCM_REG0_MASK ((0x1U << 12))
#define MCUSYS_PAR_WRAP_MCU_DBGNW_DCM_REG1_MASK ((0x1U << 16))
#define MCUSYS_PAR_WRAP_MCU_DBGNW_DCM_REG2_MASK ((0x1U << 2))
#define MCUSYS_PAR_WRAP_MCU_DBGNW_DCM_REG0_ON ((0x1U << 12))
#define MCUSYS_PAR_WRAP_MCU_DBGNW_DCM_REG1_ON ((0x1U << 16))
#define MCUSYS_PAR_WRAP_MCU_DBGNW_DCM_REG2_ON ((0x1U << 2))
#define MCUSYS_PAR_WRAP_MCU_DBGNW_DCM_REG0_OFF ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_DBGNW_DCM_REG1_OFF ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_DBGNW_DCM_REG2_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_dbgnw_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_SLV_VPS_DCM_CFG) &
		MCUSYS_PAR_WRAP_MCU_DBGNW_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_DBGNW_DCM_REG0_ON);
	ret &= ((reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_AO_DCM_CFG) &
		MCUSYS_PAR_WRAP_MCU_DBGNW_DCM_REG1_MASK) ==
		MCUSYS_PAR_WRAP_MCU_DBGNW_DCM_REG1_ON);
	ret &= ((reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_DCM_CFG) &
		MCUSYS_PAR_WRAP_MCU_DBGNW_DCM_REG2_MASK) ==
		MCUSYS_PAR_WRAP_MCU_DBGNW_DCM_REG2_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_dbgnw_dcm(int on)
{
	if (on) {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_SLV_VPS_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_SLV_VPS_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_DBGNW_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_DBGNW_DCM_REG0_ON);
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_AO_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_AO_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_DBGNW_DCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_MCU_DBGNW_DCM_REG1_ON);
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_DBGNW_DCM_REG2_MASK) |
			MCUSYS_PAR_WRAP_MCU_DBGNW_DCM_REG2_ON);
	} else {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_SLV_VPS_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_SLV_VPS_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_DBGNW_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_DBGNW_DCM_REG0_OFF);
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_AO_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_AO_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_DBGNW_DCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_MCU_DBGNW_DCM_REG1_OFF);
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_DBGNW_DCM_REG2_MASK) |
			MCUSYS_PAR_WRAP_MCU_DBGNW_DCM_REG2_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_MST_VPS_BUS_DCM_REG0_MASK ((0x1U << 11))
#define MCUSYS_PAR_WRAP_MCU_MST_VPS_BUS_DCM_REG0_ON ((0x1U << 11))
#define MCUSYS_PAR_WRAP_MCU_MST_VPS_BUS_DCM_REG0_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_mst_vps_bus_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_AO_DCM_CFG) &
		MCUSYS_PAR_WRAP_MCU_MST_VPS_BUS_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_MST_VPS_BUS_DCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_mst_vps_bus_dcm(int on)
{
	if (on) {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_AO_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_AO_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_MST_VPS_BUS_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_MST_VPS_BUS_DCM_REG0_ON);
	} else {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_AO_DCM_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_MCUSYS_MST_VPS_AO_DCM_CFG) &
			~MCUSYS_PAR_WRAP_MCU_MST_VPS_BUS_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_MST_VPS_BUS_DCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MPSYS_BUS_QDCM_REG0_MASK ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MPSYS_BUS_QDCM_REG0_ON ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MPSYS_BUS_QDCM_REG0_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mpsys_bus_qdcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG0) &
		MCUSYS_PAR_WRAP_MPSYS_BUS_QDCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MPSYS_BUS_QDCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mpsys_bus_qdcm(int on)
{
	if (on) {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG0,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG0) &
			~MCUSYS_PAR_WRAP_MPSYS_BUS_QDCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MPSYS_BUS_QDCM_REG0_ON);
	} else {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG0,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG0) &
			~MCUSYS_PAR_WRAP_MPSYS_BUS_QDCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MPSYS_BUS_QDCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MPSYS_DBG_QDCM_REG0_MASK ((0x1U << 3))
#define MCUSYS_PAR_WRAP_MPSYS_DBG_QDCM_REG0_ON ((0x1U << 3))
#define MCUSYS_PAR_WRAP_MPSYS_DBG_QDCM_REG0_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mpsys_dbg_qdcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG0) &
		MCUSYS_PAR_WRAP_MPSYS_DBG_QDCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MPSYS_DBG_QDCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mpsys_dbg_qdcm(int on)
{
	if (on) {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG0,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG0) &
			~MCUSYS_PAR_WRAP_MPSYS_DBG_QDCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MPSYS_DBG_QDCM_REG0_ON);
	} else {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG0,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG0) &
			~MCUSYS_PAR_WRAP_MPSYS_DBG_QDCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MPSYS_DBG_QDCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_GIC_QDCM_REG0_MASK ((0x49U << 7))
#define MCUSYS_PAR_WRAP_MCU_GIC_QDCM_REG0_ON ((0x49U << 7))
#define MCUSYS_PAR_WRAP_MCU_GIC_QDCM_REG0_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_gic_qdcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG0) &
		MCUSYS_PAR_WRAP_MCU_GIC_QDCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_GIC_QDCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_gic_qdcm(int on)
{
	if (on) {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG0,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG0) &
			~MCUSYS_PAR_WRAP_MCU_GIC_QDCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_GIC_QDCM_REG0_ON);
	} else {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG0,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG0) &
			~MCUSYS_PAR_WRAP_MCU_GIC_QDCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_GIC_QDCM_REG0_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_DSU_QDCM_REG0_MASK ((0x111U << 16))
#define MCUSYS_PAR_WRAP_MCU_DSU_QDCM_REG1_MASK ((0x111U << 0))
#define MCUSYS_PAR_WRAP_MCU_DSU_QDCM_REG0_ON ((0x111U << 16))
#define MCUSYS_PAR_WRAP_MCU_DSU_QDCM_REG1_ON ((0x111U << 0))
#define MCUSYS_PAR_WRAP_MCU_DSU_QDCM_REG0_OFF ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_DSU_QDCM_REG1_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_dsu_qdcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG0) &
		MCUSYS_PAR_WRAP_MCU_DSU_QDCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_DSU_QDCM_REG0_ON);
	ret &= ((reg_read(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG1) &
		MCUSYS_PAR_WRAP_MCU_DSU_QDCM_REG1_MASK) ==
		MCUSYS_PAR_WRAP_MCU_DSU_QDCM_REG1_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_dsu_qdcm(int on)
{
	if (on) {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG0,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG0) &
			~MCUSYS_PAR_WRAP_MCU_DSU_QDCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_DSU_QDCM_REG0_ON);
		reg_write(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG1,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG1) &
			~MCUSYS_PAR_WRAP_MCU_DSU_QDCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_MCU_DSU_QDCM_REG1_ON);
	} else {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG0,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG0) &
			~MCUSYS_PAR_WRAP_MCU_DSU_QDCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_DSU_QDCM_REG0_OFF);
		reg_write(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG1,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG1) &
			~MCUSYS_PAR_WRAP_MCU_DSU_QDCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_MCU_DSU_QDCM_REG1_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG0_MASK ((0x11111111U << 0))
#define MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG1_MASK ((0x111111U << 0))
#define MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG2_MASK ((0x1111U << 0))
#define MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG0_ON ((0x11111111U << 0))
#define MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG1_ON ((0x111111U << 0))
#define MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG2_ON ((0x1111U << 0))
#define MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG0_OFF ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG1_OFF ((0x0U << 0))
#define MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG2_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_core_qdcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG2) &
		MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG0_ON);
	ret &= ((reg_read(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG3) &
		MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG1_MASK) ==
		MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG1_ON);
	ret &= ((reg_read(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG4) &
		MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG2_MASK) ==
		MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG2_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_core_qdcm(int on)
{
	if (on) {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG2,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG2) &
			~MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG0_ON);
		reg_write(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG3,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG3) &
			~MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG1_ON);
		reg_write(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG4,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG4) &
			~MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG2_MASK) |
			MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG2_ON);
	} else {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG2,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG2) &
			~MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG0_OFF);
		reg_write(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG3,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG3) &
			~MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG1_MASK) |
			MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG1_OFF);
		reg_write(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG4,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_QDCM_CONFIG4) &
			~MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG2_MASK) |
			MCUSYS_PAR_WRAP_MCU_CORE_QDCM_REG2_OFF);
	}
}

#define MCUSYS_PAR_WRAP_MCU_GIC_SPI_DCM_REG0_MASK ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_GIC_SPI_DCM_REG0_ON ((0x1U << 0))
#define MCUSYS_PAR_WRAP_MCU_GIC_SPI_DCM_REG0_OFF ((0x0U << 0))

bool dcm_mcusys_par_wrap_mcu_gic_spi_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(CLUSTER0_MCUSYS_MST_VLP_GIC_SPI_SLOW_CK_CFG) &
		MCUSYS_PAR_WRAP_MCU_GIC_SPI_DCM_REG0_MASK) ==
		MCUSYS_PAR_WRAP_MCU_GIC_SPI_DCM_REG0_ON);

	return ret;
}

void dcm_mcusys_par_wrap_mcu_gic_spi_dcm(int on)
{
	if (on) {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_GIC_SPI_SLOW_CK_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_GIC_SPI_SLOW_CK_CFG) &
			~MCUSYS_PAR_WRAP_MCU_GIC_SPI_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_GIC_SPI_DCM_REG0_ON);
	} else {
		reg_write(CLUSTER0_MCUSYS_MST_VLP_GIC_SPI_SLOW_CK_CFG,
			(reg_read(CLUSTER0_MCUSYS_MST_VLP_GIC_SPI_SLOW_CK_CFG) &
			~MCUSYS_PAR_WRAP_MCU_GIC_SPI_DCM_REG0_MASK) |
			MCUSYS_PAR_WRAP_MCU_GIC_SPI_DCM_REG0_OFF);
	}
}

#define BCRM_APINFRA_IO_CTRL_AO_APINFRA_FAXI_OFF_REG0_MASK ((0x5U << 2))
#define BCRM_APINFRA_IO_CTRL_AO_APINFRA_FAXI_OFF_REG0_ON ((0x5U << 2))
#define BCRM_APINFRA_IO_CTRL_AO_APINFRA_FAXI_OFF_REG0_OFF ((0x0U << 0))

bool dcm_bcrm_apinfra_io_ctrl_ao_apinfra_faxi_off_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(CLK_AXI_VDNR_DCM_TOP_APINFRA_IO_INTX_BUS_u_APINFRA_IO_INTX_BUS_CTRL_0) &
		BCRM_APINFRA_IO_CTRL_AO_APINFRA_FAXI_OFF_REG0_MASK) ==
		BCRM_APINFRA_IO_CTRL_AO_APINFRA_FAXI_OFF_REG0_ON);

	return ret;
}

void dcm_bcrm_apinfra_io_ctrl_ao_apinfra_faxi_off(int on)
{
	if (on) {
		reg_write(CLK_AXI_VDNR_DCM_TOP_APINFRA_IO_INTX_BUS_u_APINFRA_IO_INTX_BUS_CTRL_0,
			(reg_read(CLK_AXI_VDNR_DCM_TOP_APINFRA_IO_INTX_BUS_u_APINFRA_IO_INTX_BUS_CTRL_0) &
			~BCRM_APINFRA_IO_CTRL_AO_APINFRA_FAXI_OFF_REG0_MASK) |
			BCRM_APINFRA_IO_CTRL_AO_APINFRA_FAXI_OFF_REG0_ON);
	} else {
		reg_write(CLK_AXI_VDNR_DCM_TOP_APINFRA_IO_INTX_BUS_u_APINFRA_IO_INTX_BUS_CTRL_0,
			(reg_read(CLK_AXI_VDNR_DCM_TOP_APINFRA_IO_INTX_BUS_u_APINFRA_IO_INTX_BUS_CTRL_0) &
			~BCRM_APINFRA_IO_CTRL_AO_APINFRA_FAXI_OFF_REG0_MASK) |
			BCRM_APINFRA_IO_CTRL_AO_APINFRA_FAXI_OFF_REG0_OFF);
	}
}

#define BCRM_APINFRA_IO_NOC_AO_APINFRA_IO_NOC_OFF_REG0_MASK ((0x5U << 2))
#define BCRM_APINFRA_IO_NOC_AO_APINFRA_IO_NOC_OFF_REG0_ON ((0x5U << 2))
#define BCRM_APINFRA_IO_NOC_AO_APINFRA_IO_NOC_OFF_REG0_OFF ((0x0U << 0))

bool dcm_bcrm_apinfra_io_noc_ao_apinfra_io_noc_off_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(CLK_IO_NOC_VDNR_DCM_TOP_APINFRA_IO_INTF_PAR_BUS_u_APINFRA_IO_INTF_PAR_BUS_CTRL_0) &
		BCRM_APINFRA_IO_NOC_AO_APINFRA_IO_NOC_OFF_REG0_MASK) ==
		BCRM_APINFRA_IO_NOC_AO_APINFRA_IO_NOC_OFF_REG0_ON);

	return ret;
}

void dcm_bcrm_apinfra_io_noc_ao_apinfra_io_noc_off(int on)
{
	if (on) {
		reg_write(CLK_IO_NOC_VDNR_DCM_TOP_APINFRA_IO_INTF_PAR_BUS_u_APINFRA_IO_INTF_PAR_BUS_CTRL_0,
			(reg_read(CLK_IO_NOC_VDNR_DCM_TOP_APINFRA_IO_INTF_PAR_BUS_u_APINFRA_IO_INTF_PAR_BUS_CTRL_0) &
			~BCRM_APINFRA_IO_NOC_AO_APINFRA_IO_NOC_OFF_REG0_MASK) |
			BCRM_APINFRA_IO_NOC_AO_APINFRA_IO_NOC_OFF_REG0_ON);
	} else {
		reg_write(CLK_IO_NOC_VDNR_DCM_TOP_APINFRA_IO_INTF_PAR_BUS_u_APINFRA_IO_INTF_PAR_BUS_CTRL_0,
			(reg_read(CLK_IO_NOC_VDNR_DCM_TOP_APINFRA_IO_INTF_PAR_BUS_u_APINFRA_IO_INTF_PAR_BUS_CTRL_0) &
			~BCRM_APINFRA_IO_NOC_AO_APINFRA_IO_NOC_OFF_REG0_MASK) |
			BCRM_APINFRA_IO_NOC_AO_APINFRA_IO_NOC_OFF_REG0_OFF);
	}
}

#define BCRM_APINFRA_MEM_INTF_NOC_AO_INFRA_BUS_DCM_REG0_MASK ((0x5U << 2))
#define BCRM_APINFRA_MEM_INTF_NOC_AO_INFRA_BUS_DCM_REG0_ON ((0x5U << 2))
#define BCRM_APINFRA_MEM_INTF_NOC_AO_INFRA_BUS_DCM_REG0_OFF ((0x0U << 0))

bool dcm_bcrm_apinfra_mem_intf_noc_ao_infra_bus_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(VDNR_DCM_TOP_APINFRA_MEM_INTF_PAR_BUS_u_APINFRA_MEM_INTF_PAR_BUS_CTRL_0) &
		BCRM_APINFRA_MEM_INTF_NOC_AO_INFRA_BUS_DCM_REG0_MASK) ==
		BCRM_APINFRA_MEM_INTF_NOC_AO_INFRA_BUS_DCM_REG0_ON);

	return ret;
}

void dcm_bcrm_apinfra_mem_intf_noc_ao_infra_bus_dcm(int on)
{
	if (on) {
		reg_write(VDNR_DCM_TOP_APINFRA_MEM_INTF_PAR_BUS_u_APINFRA_MEM_INTF_PAR_BUS_CTRL_0,
			(reg_read(VDNR_DCM_TOP_APINFRA_MEM_INTF_PAR_BUS_u_APINFRA_MEM_INTF_PAR_BUS_CTRL_0) &
			~BCRM_APINFRA_MEM_INTF_NOC_AO_INFRA_BUS_DCM_REG0_MASK) |
			BCRM_APINFRA_MEM_INTF_NOC_AO_INFRA_BUS_DCM_REG0_ON);
	} else {
		reg_write(VDNR_DCM_TOP_APINFRA_MEM_INTF_PAR_BUS_u_APINFRA_MEM_INTF_PAR_BUS_CTRL_0,
			(reg_read(VDNR_DCM_TOP_APINFRA_MEM_INTF_PAR_BUS_u_APINFRA_MEM_INTF_PAR_BUS_CTRL_0) &
			~BCRM_APINFRA_MEM_INTF_NOC_AO_INFRA_BUS_DCM_REG0_MASK) |
			BCRM_APINFRA_MEM_INTF_NOC_AO_INFRA_BUS_DCM_REG0_OFF);
	}
}

#define BCRM_APINFRA_HASH_CTRL_AO_INFRA_BUS_DCM_REG0_MASK ((0x5U << 2))
#define BCRM_APINFRA_HASH_CTRL_AO_INFRA_BUS_DCM_REG1_MASK ((0x5U << 2))
#define BCRM_APINFRA_HASH_CTRL_AO_INFRA_BUS_DCM_REG2_MASK ((0x5U << 2))
#define BCRM_APINFRA_HASH_CTRL_AO_INFRA_BUS_DCM_REG0_ON ((0x5U << 2))
#define BCRM_APINFRA_HASH_CTRL_AO_INFRA_BUS_DCM_REG1_ON ((0x5U << 2))
#define BCRM_APINFRA_HASH_CTRL_AO_INFRA_BUS_DCM_REG2_ON ((0x5U << 2))
#define BCRM_APINFRA_HASH_CTRL_AO_INFRA_BUS_DCM_REG0_OFF ((0x0U << 0))
#define BCRM_APINFRA_HASH_CTRL_AO_INFRA_BUS_DCM_REG1_OFF ((0x0U << 0))
#define BCRM_APINFRA_HASH_CTRL_AO_INFRA_BUS_DCM_REG2_OFF ((0x0U << 0))

bool dcm_bcrm_apinfra_hash_ctrl_ao_infra_bus_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(CLK_FHASH_CFG_VDNR_DCM_TOP_APINFRA_HASH_INTX_BUS_u_APINFRA_HASH_INTX_BUS_CTRL_0) &
		BCRM_APINFRA_HASH_CTRL_AO_INFRA_BUS_DCM_REG0_MASK) ==
		BCRM_APINFRA_HASH_CTRL_AO_INFRA_BUS_DCM_REG0_ON);
	ret &= ((reg_read(CLK_FHASH_VDNR_DCM_TOP_APINFRA_HASH_INTX_BUS_u_APINFRA_HASH_INTX_BUS_CTRL_0) &
		BCRM_APINFRA_HASH_CTRL_AO_INFRA_BUS_DCM_REG1_MASK) ==
		BCRM_APINFRA_HASH_CTRL_AO_INFRA_BUS_DCM_REG1_ON);
	ret &= ((reg_read(CLK_FHASH_NOC_VDNR_DCM_TOP_APINFRA_HASH_INTX_BUS_u_APINFRA_HASH_INTX_BUS_CTRL_0) &
		BCRM_APINFRA_HASH_CTRL_AO_INFRA_BUS_DCM_REG2_MASK) ==
		BCRM_APINFRA_HASH_CTRL_AO_INFRA_BUS_DCM_REG2_ON);

	return ret;
}

void dcm_bcrm_apinfra_hash_ctrl_ao_infra_bus_dcm(int on)
{
	if (on) {
		reg_write(CLK_FHASH_CFG_VDNR_DCM_TOP_APINFRA_HASH_INTX_BUS_u_APINFRA_HASH_INTX_BUS_CTRL_0,
			(reg_read(CLK_FHASH_CFG_VDNR_DCM_TOP_APINFRA_HASH_INTX_BUS_u_APINFRA_HASH_INTX_BUS_CTRL_0) &
			~BCRM_APINFRA_HASH_CTRL_AO_INFRA_BUS_DCM_REG0_MASK) |
			BCRM_APINFRA_HASH_CTRL_AO_INFRA_BUS_DCM_REG0_ON);
		reg_write(CLK_FHASH_VDNR_DCM_TOP_APINFRA_HASH_INTX_BUS_u_APINFRA_HASH_INTX_BUS_CTRL_0,
			(reg_read(CLK_FHASH_VDNR_DCM_TOP_APINFRA_HASH_INTX_BUS_u_APINFRA_HASH_INTX_BUS_CTRL_0) &
			~BCRM_APINFRA_HASH_CTRL_AO_INFRA_BUS_DCM_REG1_MASK) |
			BCRM_APINFRA_HASH_CTRL_AO_INFRA_BUS_DCM_REG1_ON);
		reg_write(CLK_FHASH_NOC_VDNR_DCM_TOP_APINFRA_HASH_INTX_BUS_u_APINFRA_HASH_INTX_BUS_CTRL_0,
			(reg_read(CLK_FHASH_NOC_VDNR_DCM_TOP_APINFRA_HASH_INTX_BUS_u_APINFRA_HASH_INTX_BUS_CTRL_0) &
			~BCRM_APINFRA_HASH_CTRL_AO_INFRA_BUS_DCM_REG2_MASK) |
			BCRM_APINFRA_HASH_CTRL_AO_INFRA_BUS_DCM_REG2_ON);
	} else {
		reg_write(CLK_FHASH_CFG_VDNR_DCM_TOP_APINFRA_HASH_INTX_BUS_u_APINFRA_HASH_INTX_BUS_CTRL_0,
			(reg_read(CLK_FHASH_CFG_VDNR_DCM_TOP_APINFRA_HASH_INTX_BUS_u_APINFRA_HASH_INTX_BUS_CTRL_0) &
			~BCRM_APINFRA_HASH_CTRL_AO_INFRA_BUS_DCM_REG0_MASK) |
			BCRM_APINFRA_HASH_CTRL_AO_INFRA_BUS_DCM_REG0_OFF);
		reg_write(CLK_FHASH_VDNR_DCM_TOP_APINFRA_HASH_INTX_BUS_u_APINFRA_HASH_INTX_BUS_CTRL_0,
			(reg_read(CLK_FHASH_VDNR_DCM_TOP_APINFRA_HASH_INTX_BUS_u_APINFRA_HASH_INTX_BUS_CTRL_0) &
			~BCRM_APINFRA_HASH_CTRL_AO_INFRA_BUS_DCM_REG1_MASK) |
			BCRM_APINFRA_HASH_CTRL_AO_INFRA_BUS_DCM_REG1_OFF);
		reg_write(CLK_FHASH_NOC_VDNR_DCM_TOP_APINFRA_HASH_INTX_BUS_u_APINFRA_HASH_INTX_BUS_CTRL_0,
			(reg_read(CLK_FHASH_NOC_VDNR_DCM_TOP_APINFRA_HASH_INTX_BUS_u_APINFRA_HASH_INTX_BUS_CTRL_0) &
			~BCRM_APINFRA_HASH_CTRL_AO_INFRA_BUS_DCM_REG2_MASK) |
			BCRM_APINFRA_HASH_CTRL_AO_INFRA_BUS_DCM_REG2_OFF);
	}
}

#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG0_MASK ((0x5U << 2))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG1_MASK ((0x9U << 4))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG2_MASK ((0x1U << 17))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG3_MASK ((0x1U << 21))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG4_MASK ((0x1U << 24))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG5_MASK ((0x1U << 31))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG0_ON ((0x5U << 2))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG1_ON ((0x9U << 4))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG2_ON ((0x1U << 17))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG3_ON ((0x1U << 21))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG4_ON ((0x1U << 24))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG5_ON ((0x1U << 31))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG0_OFF ((0x0U << 0))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG1_OFF ((0x0U << 0))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG2_OFF ((0x0U << 0))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG3_OFF ((0x0U << 0))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG4_OFF ((0x0U << 0))
#define BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG5_OFF ((0x0U << 0))

bool dcm_bcrm_apinfra_mem_ctrl_ao_infra_bus_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(CLK_FMEM_SUB_CFG_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_0) &
		BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG0_MASK) ==
		BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG0_ON);
	ret &= ((reg_read(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_0) &
		BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG1_MASK) ==
		BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG1_ON);
	ret &= ((reg_read(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_1) &
		BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG2_MASK) ==
		BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG2_ON);
	ret &= ((reg_read(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_2) &
		BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG3_MASK) ==
		BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG3_ON);
	ret &= ((reg_read(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_3) &
		BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG4_MASK) ==
		BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG4_ON);
	ret &= ((reg_read(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_4) &
		BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG5_MASK) ==
		BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG5_ON);

	return ret;
}

void dcm_bcrm_apinfra_mem_ctrl_ao_infra_bus_dcm(int on)
{
	if (on) {
		reg_write(CLK_FMEM_SUB_CFG_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_0,
			(reg_read(CLK_FMEM_SUB_CFG_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_0) &
			~BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG0_MASK) |
			BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG0_ON);
		reg_write(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_0,
			(reg_read(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_0) &
			~BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG1_MASK) |
			BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG1_ON);
		reg_write(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_1,
			(reg_read(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_1) &
			~BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG2_MASK) |
			BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG2_ON);
		reg_write(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_2,
			(reg_read(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_2) &
			~BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG3_MASK) |
			BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG3_ON);
		reg_write(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_3,
			(reg_read(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_3) &
			~BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG4_MASK) |
			BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG4_ON);
		reg_write(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_4,
			(reg_read(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_4) &
			~BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG5_MASK) |
			BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG5_ON);
	} else {
		reg_write(CLK_FMEM_SUB_CFG_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_0,
			(reg_read(CLK_FMEM_SUB_CFG_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_0) &
			~BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG0_MASK) |
			BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG0_OFF);
		reg_write(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_0,
			(reg_read(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_0) &
			~BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG1_MASK) |
			BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG1_OFF);
		reg_write(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_1,
			(reg_read(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_1) &
			~BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG2_MASK) |
			BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG2_OFF);
		reg_write(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_2,
			(reg_read(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_2) &
			~BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG3_MASK) |
			BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG3_OFF);
		reg_write(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_3,
			(reg_read(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_3) &
			~BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG4_MASK) |
			BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG4_OFF);
		reg_write(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_4,
			(reg_read(CLK_FMEM_SUB_VDNR_DCM_TOP_APINFRA_MEM_INTX_BUS_u_APINFRA_MEM_INTX_BUS_CTRL_4) &
			~BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG5_MASK) |
			BCRM_APINFRA_MEM_CTRL_AO_INFRA_BUS_DCM_REG5_OFF);
	}
}

#define BCRM_APINFRA_IO_EAST_AO_APINFRA_IO_EST_FAXI_OFF_REG0_MASK ((0x5U << 2))
#define BCRM_APINFRA_IO_EAST_AO_APINFRA_IO_EST_FAXI_OFF_REG0_ON ((0x5U << 2))
#define BCRM_APINFRA_IO_EAST_AO_APINFRA_IO_EST_FAXI_OFF_REG0_OFF ((0x0U << 0))

bool dcm_bcrm_apinfra_io_east_ao_apinfra_io_est_faxi_off_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(BCRM_APINFRA_IO_EAST_AO_APINFRA_IO_EST_FAXI_OFF_REG0) &
		BCRM_APINFRA_IO_EAST_AO_APINFRA_IO_EST_FAXI_OFF_REG0_MASK) ==
		BCRM_APINFRA_IO_EAST_AO_APINFRA_IO_EST_FAXI_OFF_REG0_ON);

	return ret;
}

void dcm_bcrm_apinfra_io_east_ao_apinfra_io_est_faxi_off(int on)
{
	if (on) {
		reg_write(BCRM_APINFRA_IO_EAST_AO_APINFRA_IO_EST_FAXI_OFF_REG0,
			(reg_read(BCRM_APINFRA_IO_EAST_AO_APINFRA_IO_EST_FAXI_OFF_REG0) &
			~BCRM_APINFRA_IO_EAST_AO_APINFRA_IO_EST_FAXI_OFF_REG0_MASK) |
			BCRM_APINFRA_IO_EAST_AO_APINFRA_IO_EST_FAXI_OFF_REG0_ON);
	} else {
		reg_write(BCRM_APINFRA_IO_EAST_AO_APINFRA_IO_EST_FAXI_OFF_REG0,
			(reg_read(BCRM_APINFRA_IO_EAST_AO_APINFRA_IO_EST_FAXI_OFF_REG0) &
			~BCRM_APINFRA_IO_EAST_AO_APINFRA_IO_EST_FAXI_OFF_REG0_MASK) |
			BCRM_APINFRA_IO_EAST_AO_APINFRA_IO_EST_FAXI_OFF_REG0_OFF);
	}
}

#define PERI_AO_BCRM_PERI_BUS_DCM_REG0_MASK ((0xa49U << 5))
#define PERI_AO_BCRM_PERI_BUS_DCM_REG1_MASK ((0x1U << 13))
#define PERI_AO_BCRM_PERI_BUS_DCM_REG2_MASK ((0x1U << 13))
#define PERI_AO_BCRM_PERI_BUS_DCM_REG3_MASK ((0x1U << 13))
#define PERI_AO_BCRM_PERI_BUS_DCM_REG0_ON ((0xa49U << 5))
#define PERI_AO_BCRM_PERI_BUS_DCM_REG1_ON ((0x1U << 13))
#define PERI_AO_BCRM_PERI_BUS_DCM_REG2_ON ((0x1U << 13))
#define PERI_AO_BCRM_PERI_BUS_DCM_REG3_ON ((0x1U << 13))
#define PERI_AO_BCRM_PERI_BUS_DCM_REG0_OFF ((0x0U << 0))
#define PERI_AO_BCRM_PERI_BUS_DCM_REG1_OFF ((0x0U << 0))
#define PERI_AO_BCRM_PERI_BUS_DCM_REG2_OFF ((0x0U << 0))
#define PERI_AO_BCRM_PERI_BUS_DCM_REG3_OFF ((0x0U << 0))

bool dcm_peri_ao_bcrm_peri_bus_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_0) &
		PERI_AO_BCRM_PERI_BUS_DCM_REG0_MASK) ==
		PERI_AO_BCRM_PERI_BUS_DCM_REG0_ON);
	ret &= ((reg_read(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_1) &
		PERI_AO_BCRM_PERI_BUS_DCM_REG1_MASK) ==
		PERI_AO_BCRM_PERI_BUS_DCM_REG1_ON);
	ret &= ((reg_read(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_2) &
		PERI_AO_BCRM_PERI_BUS_DCM_REG2_MASK) ==
		PERI_AO_BCRM_PERI_BUS_DCM_REG2_ON);
	ret &= ((reg_read(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_3) &
		PERI_AO_BCRM_PERI_BUS_DCM_REG3_MASK) ==
		PERI_AO_BCRM_PERI_BUS_DCM_REG3_ON);

	return ret;
}

void dcm_peri_ao_bcrm_peri_bus_dcm(int on)
{
	if (on) {
		reg_write(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_0,
			(reg_read(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_0) &
			~PERI_AO_BCRM_PERI_BUS_DCM_REG0_MASK) |
			PERI_AO_BCRM_PERI_BUS_DCM_REG0_ON);
		reg_write(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_1,
			(reg_read(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_1) &
			~PERI_AO_BCRM_PERI_BUS_DCM_REG1_MASK) |
			PERI_AO_BCRM_PERI_BUS_DCM_REG1_ON);
		reg_write(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_2,
			(reg_read(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_2) &
			~PERI_AO_BCRM_PERI_BUS_DCM_REG2_MASK) |
			PERI_AO_BCRM_PERI_BUS_DCM_REG2_ON);
		reg_write(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_3,
			(reg_read(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_3) &
			~PERI_AO_BCRM_PERI_BUS_DCM_REG3_MASK) |
			PERI_AO_BCRM_PERI_BUS_DCM_REG3_ON);
	} else {
		reg_write(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_0,
			(reg_read(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_0) &
			~PERI_AO_BCRM_PERI_BUS_DCM_REG0_MASK) |
			PERI_AO_BCRM_PERI_BUS_DCM_REG0_OFF);
		reg_write(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_1,
			(reg_read(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_1) &
			~PERI_AO_BCRM_PERI_BUS_DCM_REG1_MASK) |
			PERI_AO_BCRM_PERI_BUS_DCM_REG1_OFF);
		reg_write(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_2,
			(reg_read(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_2) &
			~PERI_AO_BCRM_PERI_BUS_DCM_REG2_MASK) |
			PERI_AO_BCRM_PERI_BUS_DCM_REG2_OFF);
		reg_write(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_3,
			(reg_read(VDNR_DCM_TOP_PERI_PAR_BUS_u_PERI_PAR_BUS_CTRL_3) &
			~PERI_AO_BCRM_PERI_BUS_DCM_REG3_MASK) |
			PERI_AO_BCRM_PERI_BUS_DCM_REG3_OFF);
	}
}

#define PERICFG_AO_REG_PERI_BUS_DCM_REG0_MASK ((0x3U << 1))
#define PERICFG_AO_REG_PERI_BUS_DCM_REG0_ON ((0x0U << 0))
#define PERICFG_AO_REG_PERI_BUS_DCM_REG0_OFF ((0x3U << 1))

bool dcm_pericfg_ao_reg_peri_bus_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(PERICFG_AO_REG_PERI_MASK_IDLE_TO_CKSYS) &
		PERICFG_AO_REG_PERI_BUS_DCM_REG0_MASK) ==
		PERICFG_AO_REG_PERI_BUS_DCM_REG0_ON);

	return ret;
}

void dcm_pericfg_ao_reg_peri_bus_dcm(int on)
{
	if (on) {
		reg_write(PERICFG_AO_REG_PERI_MASK_IDLE_TO_CKSYS,
			(reg_read(PERICFG_AO_REG_PERI_MASK_IDLE_TO_CKSYS) &
			~PERICFG_AO_REG_PERI_BUS_DCM_REG0_MASK) |
			PERICFG_AO_REG_PERI_BUS_DCM_REG0_ON);
	} else {
		reg_write(PERICFG_AO_REG_PERI_MASK_IDLE_TO_CKSYS,
			(reg_read(PERICFG_AO_REG_PERI_MASK_IDLE_TO_CKSYS) &
			~PERICFG_AO_REG_PERI_BUS_DCM_REG0_MASK) |
			PERICFG_AO_REG_PERI_BUS_DCM_REG0_OFF);
	}
}

#define VLP_AO_BCRM_VLP_BUS_DCM_REG0_MASK ((0x3e013U << 1))
#define VLP_AO_BCRM_VLP_BUS_DCM_REG0_ON ((0x13U << 1))
#define VLP_AO_BCRM_VLP_BUS_DCM_REG0_OFF ((0x3U << 1))

bool dcm_vlp_ao_bcrm_vlp_bus_dcm_is_on(void)
{
	bool ret = true;

	ret &= ((reg_read(VDNR_DCM_TOP_VLP_PAR_BUS_TOP_u_VLP_PAR_BUS_TOP_CTRL_0) &
		VLP_AO_BCRM_VLP_BUS_DCM_REG0_MASK) ==
		VLP_AO_BCRM_VLP_BUS_DCM_REG0_ON);

	return ret;
}

void dcm_vlp_ao_bcrm_vlp_bus_dcm(int on)
{
	if (on) {
		reg_write(VDNR_DCM_TOP_VLP_PAR_BUS_TOP_u_VLP_PAR_BUS_TOP_CTRL_0,
			(reg_read(VDNR_DCM_TOP_VLP_PAR_BUS_TOP_u_VLP_PAR_BUS_TOP_CTRL_0) &
			~VLP_AO_BCRM_VLP_BUS_DCM_REG0_MASK) |
			VLP_AO_BCRM_VLP_BUS_DCM_REG0_ON);
	} else {
		reg_write(VDNR_DCM_TOP_VLP_PAR_BUS_TOP_u_VLP_PAR_BUS_TOP_CTRL_0,
			(reg_read(VDNR_DCM_TOP_VLP_PAR_BUS_TOP_u_VLP_PAR_BUS_TOP_CTRL_0) &
			~VLP_AO_BCRM_VLP_BUS_DCM_REG0_MASK) |
			VLP_AO_BCRM_VLP_BUS_DCM_REG0_OFF);
	}
}

