/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2023 MediaTek Inc.
 */

#ifndef __MTK_DISP_OVL_OUTPUTPROC_REG_H__
#define __MTK_DISP_OVL_OUTPUTPROC_REG_H__

enum disp_ovl_outproc_register {
	OVL_OUTPROC_STA,
	OVL_OUTPROC_INTEN,
	OVL_OUTPROC_INTSTA,
	OVL_OUTPROC_TRIG,
	OVL_OUTPROC_DATAPATH_CON,
	OVL_OUTPROC_EN,
	OVL_OUTPROC_RST,
	OVL_OUTPROC_SHADOW_CTRL,
	OVL_OUTPROC_ROI_SIZE,
	OVL_OUTPROC_CRC,
	OVL_OUTPROC_OVLDTH_CTRL,
	OVL_OUTPROC_FLOW_CTRL_DBG,
	OVL_OUTPROC_FUNC_DCM0,
	OVL_OUTPROC_FUNC_DCM1,
	OVL_OUTPROC_MODE,
	OVL_OUTPROC_OUT_R2R_PARA_R0,
	OVL_OUTPROC_OUT_R2R_PARA_R1,
	OVL_OUTPROC_OUT_R2R_PARA_R2,
	OVL_OUTPROC_OUT_R2R_PARA_G0,
	OVL_OUTPROC_OUT_R2R_PARA_G1,
	OVL_OUTPROC_OUT_R2R_PARA_G2,
	OVL_OUTPROC_OUT_R2R_PARA_B0,
	OVL_OUTPROC_OUT_R2R_PARA_B1,
	OVL_OUTPROC_OUT_R2R_PARA_B2,
	OVL_OUTPROC_OUT_R2R_PARA_POST_RGB_A_0,
	OVL_OUTPROC_OUT_R2R_PARA_POST_RGB_A_1,
	OVL_OUTPROC_OUT_R2R_PARA_POST_RGB_A_2,
	OVL_OUTPROC_INTEN_2ND,
	OVL_OUTPROC_INTSTA_2ND,
	OVL_OUTPROC_INRELAY_DBG1,
	OVL_OUTPROC_INRELAY_DBG2,
	OVL_OUTPROC_DBG1,
	OVL_INT_OUTPROC_DBG1,
	OVL_OUTPROC_REG_TOTAL
};

static const u16 ovl_outproc_regs_mt6991[OVL_OUTPROC_REG_TOTAL] = {
	[OVL_OUTPROC_STA] = 0x000,
	[OVL_OUTPROC_INTEN] = 0x004,
	[OVL_OUTPROC_INTSTA] = 0x008,
	[OVL_OUTPROC_TRIG] = 0x00C,
	[OVL_OUTPROC_DATAPATH_CON] = 0x010,
	[OVL_OUTPROC_EN] = 0x020,
	[OVL_OUTPROC_RST] = 0x024,
	[OVL_OUTPROC_SHADOW_CTRL] = 0x028,
	[OVL_OUTPROC_ROI_SIZE] = 0x030,
	[OVL_OUTPROC_CRC] = 0x100,
	[OVL_OUTPROC_OVLDTH_CTRL] = 0x104,
	[OVL_OUTPROC_FLOW_CTRL_DBG] = 0x108,
	[OVL_OUTPROC_FUNC_DCM0] = 0x10C,
	[OVL_OUTPROC_FUNC_DCM1] = 0x110,
	[OVL_OUTPROC_MODE] = 0x114,
	[OVL_OUTPROC_OUT_R2R_PARA_R0] = 0x118,
	[OVL_OUTPROC_OUT_R2R_PARA_R1] = 0x11C,
	[OVL_OUTPROC_OUT_R2R_PARA_R2] = 0x120,
	[OVL_OUTPROC_OUT_R2R_PARA_G0] = 0x124,
	[OVL_OUTPROC_OUT_R2R_PARA_G1] = 0x128,
	[OVL_OUTPROC_OUT_R2R_PARA_G2] = 0x12C,
	[OVL_OUTPROC_OUT_R2R_PARA_B0] = 0x130,
	[OVL_OUTPROC_OUT_R2R_PARA_B1] = 0x134,
	[OVL_OUTPROC_OUT_R2R_PARA_B2] = 0x138,
	[OVL_OUTPROC_OUT_R2R_PARA_POST_RGB_A_0] = 0x13C,
	[OVL_OUTPROC_OUT_R2R_PARA_POST_RGB_A_1] = 0x140,
	[OVL_OUTPROC_OUT_R2R_PARA_POST_RGB_A_2] = 0x144,
	[OVL_OUTPROC_INTEN_2ND] = 0x148,
	[OVL_OUTPROC_INTSTA_2ND] = 0x14C,
	[OVL_OUTPROC_INRELAY_DBG1] = 0x150,
	[OVL_OUTPROC_INRELAY_DBG2] = 0x154,
	[OVL_OUTPROC_DBG1] = 0x158,
	[OVL_INT_OUTPROC_DBG1] = 0x15C,
};


enum disp_ovl_outproc_fld {
	/*OVL_OUTPROC_INTEN*/
	FLD_OVL_OUTPROC_REG_CMT_INTEN,
	FLD_OVL_OUTPROC_FME_CPL_INTEN,
	FLD_OVL_OUTPROC_FME_UND_INTEN,
	FLD_OVL_OUTPROC_ABNORMAL_SOF_INTEN,
	FLD_OVL_OUTPROC_START_INTEN,

	/*OVL_OUTPROC_DATAPATH_CON*/
	FLD_OVL_OUTPROC_OUTPUT_CLAMP,

	/*OVL_OUTPROC_EN*/
	FLD_OVL_OUTPROC_EN,
	FLD_OVL_OUTPROC_RELAY_MODE_EN,

	/*OVL_OUTPROC_FUNC_DCM0*/
	FLD_OVL_OUTPROC_FUNC_DCM0,
	OVL_OUTPROC_FLD_TOTAL
};

static const u32 ovl_outproc_fld_mt6991[OVL_OUTPROC_REG_TOTAL] = {
	/*OVL_OUTPROC_INTEN*/
	[FLD_OVL_OUTPROC_REG_CMT_INTEN] = REG_FLD_MSB_LSB(0, 0),
	[FLD_OVL_OUTPROC_FME_CPL_INTEN] = REG_FLD_MSB_LSB(1, 1),
	[FLD_OVL_OUTPROC_FME_UND_INTEN] = REG_FLD_MSB_LSB(2, 2),
	[FLD_OVL_OUTPROC_ABNORMAL_SOF_INTEN] = REG_FLD_MSB_LSB(5, 5),
	[FLD_OVL_OUTPROC_START_INTEN] = REG_FLD_MSB_LSB(6, 6),

	/*OVL_OUTPROC_DATAPATH_CON*/
	[FLD_OVL_OUTPROC_OUTPUT_CLAMP] = REG_FLD_MSB_LSB(26, 26),

	/*OVL_OUTPROC_EN*/
	[FLD_OVL_OUTPROC_EN] = REG_FLD_MSB_LSB(0, 0),
	[FLD_OVL_OUTPROC_RELAY_MODE_EN] = REG_FLD_MSB_LSB(5, 5),

	/*OVL_OUTPROC_FUNC_DCM0*/
	[FLD_OVL_OUTPROC_FUNC_DCM0] =  REG_FLD_MSB_LSB(31, 0),
};

#endif
