# Copyright (C) 2024 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/performance/game/include \
# 	-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/performance/game/engine_cooler \
# 	-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/performance/game/frame_interpolate \
# 	-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/performance/fpsgo_v8/base/include \
# 	-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/performance/game/kernel_core_ctrl \
# 	-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/ \
# 	-I$(srctree)/kernel/ \

# mtk_game_objs += game.o \
# 	game_base.o \
# 	game_sysfs.o \
# 	engine_cooler/game_ec.o \
# 	kernel_core_ctrl/kernel_core_ctrl.o \
# 	frame_interpolate/fi_base.o \
# 	frame_interpolate/frame_interpolate.o \

# obj-$(CONFIG_MTK_GAME) += mtk_game.o
# mtk_game-objs += $(mtk_game_objs)
