/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2025 MediaTek Inc.
 */

#ifndef __SENINF_TA_H__
#define __SENINF_TA_H__

typedef enum {
	SENINF_RETURN_SUCCESS = 0,
	SENINF_RETURN_ERROR = -1,
	SENINF_RETURN_ERROR_MAPPING_FAIL = -2,
} SENINF_RETURN;

typedef enum {
	SENINF_TEE_CMD_SYNC_TO_PA = 0x10,
	SENINF_TEE_CMD_SYNC_TO_VA,
	SENINF_TEE_CMD_CHECKPIPE,
	SENINF_TEE_CMD_FREE,
} SENINF_TEE_CMD;

typedef enum {
	SENINF_TA_DRV_SYNC_TO_PA = 0x10,
	SENINF_TA_DRV_SYNC_TO_VA,
	SENINF_TA_DRV_CHECKPIPE,
	SENINF_TA_DRV_FREE,
} SENINF_TA_DRV_CMD;

#endif
