// SPDX-License-Identifier: GPL-2.0
/*
 * Copyright (c) 2025 MediaTek Inc.
 */

#include "secure_port.h"
#include "seninf_drv_csi_info.h"

#define SENINF_CSI_TYPE_MIPI(port, seninf)     {port, seninf, MIPI_SENSOR}
#define SENINF_CSI_TYPE_SERIAL(port, seninf)   {port, seninf, SERIAL_SENSOR}
#define SENINF_CSI_TYPE_PARALLEL(port, seninf) {port, seninf, PARALLEL_SENSOR}

SENINF_CSI_INFO seninfCSITypeInfo[CUSTOM_CFG_CSI_PORT_MAX_NUM] = {
	SENINF_CSI_TYPE_MIPI(CUSTOM_CFG_CSI_PORT_0,  SENINF_ASYNC_0),
	SENINF_CSI_TYPE_MIPI(CUSTOM_CFG_CSI_PORT_1,  SENINF_ASYNC_1),
	SENINF_CSI_TYPE_MIPI(CUSTOM_CFG_CSI_PORT_2,  SENINF_ASYNC_2),
	SENINF_CSI_TYPE_MIPI(CUSTOM_CFG_CSI_PORT_3,  SENINF_ASYNC_3),
	SENINF_CSI_TYPE_MIPI(CUSTOM_CFG_CSI_PORT_4,  SENINF_ASYNC_4),
	SENINF_CSI_TYPE_MIPI(CUSTOM_CFG_CSI_PORT_5,  SENINF_ASYNC_5),
	SENINF_CSI_TYPE_MIPI(CUSTOM_CFG_CSI_PORT_0A, SENINF_ASYNC_0),
	SENINF_CSI_TYPE_MIPI(CUSTOM_CFG_CSI_PORT_0B, SENINF_ASYNC_0),
	SENINF_CSI_TYPE_MIPI(CUSTOM_CFG_CSI_PORT_1A, SENINF_ASYNC_1),
	SENINF_CSI_TYPE_MIPI(CUSTOM_CFG_CSI_PORT_1B, SENINF_ASYNC_1),
	SENINF_CSI_TYPE_MIPI(CUSTOM_CFG_CSI_PORT_2A, SENINF_ASYNC_2),
	SENINF_CSI_TYPE_MIPI(CUSTOM_CFG_CSI_PORT_2B, SENINF_ASYNC_2),
	SENINF_CSI_TYPE_MIPI(CUSTOM_CFG_CSI_PORT_3A, SENINF_ASYNC_3),
	SENINF_CSI_TYPE_MIPI(CUSTOM_CFG_CSI_PORT_3B, SENINF_ASYNC_3),
	SENINF_CSI_TYPE_MIPI(CUSTOM_CFG_CSI_PORT_4A, SENINF_ASYNC_4),
	SENINF_CSI_TYPE_MIPI(CUSTOM_CFG_CSI_PORT_4B, SENINF_ASYNC_4),
	SENINF_CSI_TYPE_MIPI(CUSTOM_CFG_CSI_PORT_5A, SENINF_ASYNC_5),
	SENINF_CSI_TYPE_MIPI(CUSTOM_CFG_CSI_PORT_5B, SENINF_ASYNC_5),
};
