/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2025 MediaTek Inc.
 */

#ifndef __SENINF_TEE_COMMON_H__
#define __SENINF_TEE_COMMON_H__

#include <linux/types.h>

#define SENINF_OUTMUX_MAX_NUM 10

typedef enum {
	// base addr: 0x3A300000
	SENINF_TEE_REG_ADDR_SENINF_TOP_OUTMUX_CG_EN  = 0x000C,
	// base addr: 0x3A301000
	SENINF_TEE_REG_ADDR_SENINF_ASYTOP_ASYNC_CFG  = 0x0000,
	// base addr: 0x3A100000
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX0_SRC_SEL         = 0x0018,
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX1_SRC_SEL         = 0x0018,
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX2_SRC_SEL         = 0x0018,
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX3_SRC_SEL         = 0x0018,
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX4_SRC_SEL         = 0x0018,
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX5_SRC_SEL         = 0x0018,
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX6_SRC_SEL         = 0x0018,
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX7_SRC_SEL         = 0x0018,
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX8_SRC_SEL         = 0x0018,
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX9_SRC_SEL         = 0x0018,

	SENINF_TEE_REG_ADDR_SENINF_OUTMUX0_CAM_RDY_GRP_SEL = 0x00A8,
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX1_CAM_RDY_GRP_SEL = 0x00A8,
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX2_CAM_RDY_GRP_SEL = 0x00A8,
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX3_CAM_RDY_GRP_SEL = 0x00A8,
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX4_CAM_RDY_GRP_SEL = 0x00A8,
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX5_CAM_RDY_GRP_SEL = 0x00A8,
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX6_CAM_RDY_GRP_SEL = 0x00A8,
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX7_CAM_RDY_GRP_SEL = 0x00A8,
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX8_CAM_RDY_GRP_SEL = 0x00A8,
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX9_CAM_RDY_GRP_SEL = 0x00A8,

	SENINF_TEE_REG_ADDR_SENINF_OUTMUX0_CSR_CFG_CTRL = 0x0020,
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX1_CSR_CFG_CTRL = 0x0020,
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX2_CSR_CFG_CTRL = 0x0020,
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX3_CSR_CFG_CTRL = 0x0020,
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX4_CSR_CFG_CTRL = 0x0020,
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX5_CSR_CFG_CTRL = 0x0020,
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX6_CSR_CFG_CTRL = 0x0020,
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX7_CSR_CFG_CTRL = 0x0020,
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX8_CSR_CFG_CTRL = 0x0020,
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX9_CSR_CFG_CTRL = 0x0020,
	/* SENSOR base addr: 0x3A002000 */
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SENSOR_CID_0   = 0x0000,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SENSOR_CID_1   = 0x0004,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SENSOR_CID_2   = 0x0008,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SENSOR_CID_3   = 0x000C,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SENSOR_CID_4   = 0x0010,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SENSOR_CID_5   = 0x0014,
	/* CID base addr: 0x3A002000 */
	SENINF_TEE_REG_ADDR_SENINF_ROOT_OUTMUX_CID_0   = 0x0020,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_OUTMUX_CID_1   = 0x0024,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_OUTMUX_CID_2   = 0x0028,
	/* RDY MASK CID base addr: 0x3A002000 */
	SENINF_TEE_REG_ADDR_SENINF_ROOT_RDY_MASK_CID_0   = 0x0100,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_RDY_MASK_CID_1   = 0x0104,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_RDY_MASK_CID_2   = 0x0108,
	/* Seninf outmux tag VCDT base addr: 0x3A002000 */
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_0_TAG_VCDT_FILT_0   = 0x0220,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_0_TAG_VCDT_FILT_1   = 0x0224,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_0_TAG_VCDT_FILT_2   = 0x0228,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_0_TAG_VCDT_FILT_3   = 0x022C,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_0_TAG_VCDT_FILT_4   = 0x0230,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_0_TAG_VCDT_FILT_5   = 0x0234,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_0_TAG_VCDT_FILT_6   = 0x0238,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_0_TAG_VCDT_FILT_7   = 0x023C,

	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_1_TAG_VCDT_FILT_0   = 0x02A0,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_1_TAG_VCDT_FILT_1   = 0x02A4,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_1_TAG_VCDT_FILT_2   = 0x02A8,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_1_TAG_VCDT_FILT_3   = 0x02AC,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_1_TAG_VCDT_FILT_4   = 0x02B0,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_1_TAG_VCDT_FILT_5   = 0x02B4,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_1_TAG_VCDT_FILT_6   = 0x02B8,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_1_TAG_VCDT_FILT_7   = 0x02BC,

	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_2_TAG_VCDT_FILT_0   = 0x0320,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_2_TAG_VCDT_FILT_1   = 0x0324,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_2_TAG_VCDT_FILT_2   = 0x0328,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_2_TAG_VCDT_FILT_3   = 0x032C,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_2_TAG_VCDT_FILT_4   = 0x0330,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_2_TAG_VCDT_FILT_5   = 0x0334,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_2_TAG_VCDT_FILT_6   = 0x0338,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_2_TAG_VCDT_FILT_7   = 0x033C,

	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_3_TAG_VCDT_FILT_0   = 0x03A0,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_3_TAG_VCDT_FILT_1   = 0x03A4,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_3_TAG_VCDT_FILT_2   = 0x03A8,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_3_TAG_VCDT_FILT_3   = 0x03AC,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_3_TAG_VCDT_FILT_4   = 0x03B0,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_3_TAG_VCDT_FILT_5   = 0x03B4,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_3_TAG_VCDT_FILT_6   = 0x03B8,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_3_TAG_VCDT_FILT_7   = 0x03BC,

	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_4_TAG_VCDT_FILT_0   = 0x0420,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_4_TAG_VCDT_FILT_1   = 0x0424,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_4_TAG_VCDT_FILT_2   = 0x0428,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_4_TAG_VCDT_FILT_3   = 0x042C,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_4_TAG_VCDT_FILT_4   = 0x0430,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_4_TAG_VCDT_FILT_5   = 0x0434,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_4_TAG_VCDT_FILT_6   = 0x0438,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_4_TAG_VCDT_FILT_7   = 0x043C,

	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_5_TAG_VCDT_FILT_0   = 0x04A0,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_5_TAG_VCDT_FILT_1   = 0x04A4,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_5_TAG_VCDT_FILT_2   = 0x04A8,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_5_TAG_VCDT_FILT_3   = 0x04AC,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_5_TAG_VCDT_FILT_4   = 0x04B0,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_5_TAG_VCDT_FILT_5   = 0x04B4,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_5_TAG_VCDT_FILT_6   = 0x04B8,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_5_TAG_VCDT_FILT_7   = 0x04BC,

	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_6_TAG_VCDT_FILT_0   = 0x0520,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_6_TAG_VCDT_FILT_1   = 0x0524,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_6_TAG_VCDT_FILT_2   = 0x0528,
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_6_TAG_VCDT_FILT_3   = 0x052C,
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_6_TAG_VCDT_FILT_4   = 0x0530,
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_6_TAG_VCDT_FILT_5   = 0x0534,
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_6_TAG_VCDT_FILT_6   = 0x0538,
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_6_TAG_VCDT_FILT_7   = 0x053C,

	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_7_TAG_VCDT_FILT_0   = 0x05A0,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_7_TAG_VCDT_FILT_1   = 0x05A4,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_7_TAG_VCDT_FILT_2   = 0x05A8,
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_7_TAG_VCDT_FILT_3   = 0x05AC,
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_7_TAG_VCDT_FILT_4   = 0x05B0,
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_7_TAG_VCDT_FILT_5   = 0x05B4,
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_7_TAG_VCDT_FILT_6   = 0x05B8,
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_7_TAG_VCDT_FILT_7   = 0x05BC,

	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_8_TAG_VCDT_FILT_0   = 0x0620,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_8_TAG_VCDT_FILT_1   = 0x0624,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_8_TAG_VCDT_FILT_2   = 0x0628,
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_8_TAG_VCDT_FILT_3   = 0x062C,
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_8_TAG_VCDT_FILT_4   = 0x0630,
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_8_TAG_VCDT_FILT_5   = 0x0634,
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_8_TAG_VCDT_FILT_6   = 0x0638,
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_8_TAG_VCDT_FILT_7   = 0x063C,

	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_9_TAG_VCDT_FILT_0   = 0x06A0,
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_9_TAG_VCDT_FILT_1   = 0x06A4,
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_9_TAG_VCDT_FILT_2   = 0x06A8,
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_9_TAG_VCDT_FILT_3   = 0x06AC,
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_9_TAG_VCDT_FILT_4   = 0x06B0,
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_9_TAG_VCDT_FILT_5   = 0x06B4,
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_9_TAG_VCDT_FILT_6   = 0x06B8,
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_9_TAG_VCDT_FILT_7   = 0x06BC,

	SENINF_TEE_REG_ADDR_SENINF_ROOT_TSREC_CID_0   = 0x0040,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_TSREC_CID_1   = 0x0044,
	SENINF_TEE_REG_ADDR_SENINF_ROOT_TSREC_CID_2   = 0x0048,
} SENINF_TEE_REG_ADDR;

typedef struct {
	uint32_t           SENINF_TEE_OUTMUX_SRC_SEL;
} SENINF_TEE_REG_OUTMUX;

typedef struct {
	uint32_t           SENINF_TEE_OUTMUX_CAM_RDY_GRP_SEL;
} SENINF_TEE_REG_OUTMUX_RDY_GRP_SEL;

typedef struct {
	uint32_t           SENINF_TEE_OUTMUX_CSR_CFG_CTRL;
} SENINF_TEE_REG_OUTMUX_CSR_CFG_CTRL;

typedef struct {
	uint32_t REG_SENINF_TOP_OUTMUX_CG_EN;
	uint32_t REG_SENINF_ASYTOP_ASYNC_CFG;
	SENINF_TEE_REG_OUTMUX seninf_outmux[SENINF_OUTMUX_MAX_NUM];
	SENINF_TEE_REG_OUTMUX_RDY_GRP_SEL seninf_outmux_rdy_grp_sel[SENINF_OUTMUX_MAX_NUM];
	SENINF_TEE_REG_OUTMUX_CSR_CFG_CTRL seninf_outmux_csr_cfg_ctrl[SENINF_OUTMUX_MAX_NUM];
	uint32_t REG_SENINF_ROOT_SENSOR_CID_0;
	uint32_t REG_SENINF_ROOT_SENSOR_CID_1;
	uint32_t REG_SENINF_ROOT_SENSOR_CID_2;
	uint32_t REG_SENINF_ROOT_SENSOR_CID_3;
	uint32_t REG_SENINF_ROOT_SENSOR_CID_4;
	uint32_t REG_SENINF_ROOT_SENSOR_CID_5;
	uint32_t REG_SENINF_ROOT_OUTMUX_CID_0;
	uint32_t REG_SENINF_ROOT_OUTMUX_CID_1;
	uint32_t REG_SENINF_ROOT_OUTMUX_CID_2;
	uint32_t REG_SENINF_ROOT_RDY_MASK_CID_0;
	uint32_t REG_SENINF_ROOT_RDY_MASK_CID_1;
	uint32_t REG_SENINF_ROOT_RDY_MASK_CID_2;

	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_0_TAG_VCDT_FILT_0;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_0_TAG_VCDT_FILT_1;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_0_TAG_VCDT_FILT_2;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_0_TAG_VCDT_FILT_3;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_0_TAG_VCDT_FILT_4;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_0_TAG_VCDT_FILT_5;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_0_TAG_VCDT_FILT_6;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_0_TAG_VCDT_FILT_7;

	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_1_TAG_VCDT_FILT_0;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_1_TAG_VCDT_FILT_1;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_1_TAG_VCDT_FILT_2;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_1_TAG_VCDT_FILT_3;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_1_TAG_VCDT_FILT_4;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_1_TAG_VCDT_FILT_5;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_1_TAG_VCDT_FILT_6;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_1_TAG_VCDT_FILT_7;

	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_2_TAG_VCDT_FILT_0;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_2_TAG_VCDT_FILT_1;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_2_TAG_VCDT_FILT_2;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_2_TAG_VCDT_FILT_3;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_2_TAG_VCDT_FILT_4;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_2_TAG_VCDT_FILT_5;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_2_TAG_VCDT_FILT_6;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_2_TAG_VCDT_FILT_7;

	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_3_TAG_VCDT_FILT_0;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_3_TAG_VCDT_FILT_1;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_3_TAG_VCDT_FILT_2;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_3_TAG_VCDT_FILT_3;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_3_TAG_VCDT_FILT_4;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_3_TAG_VCDT_FILT_5;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_3_TAG_VCDT_FILT_6;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_3_TAG_VCDT_FILT_7;

	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_4_TAG_VCDT_FILT_0;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_4_TAG_VCDT_FILT_1;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_4_TAG_VCDT_FILT_2;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_4_TAG_VCDT_FILT_3;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_4_TAG_VCDT_FILT_4;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_4_TAG_VCDT_FILT_5;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_4_TAG_VCDT_FILT_6;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_4_TAG_VCDT_FILT_7;

	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_5_TAG_VCDT_FILT_0;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_5_TAG_VCDT_FILT_1;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_5_TAG_VCDT_FILT_2;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_5_TAG_VCDT_FILT_3;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_5_TAG_VCDT_FILT_4;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_5_TAG_VCDT_FILT_5;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_5_TAG_VCDT_FILT_6;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_5_TAG_VCDT_FILT_7;

	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_6_TAG_VCDT_FILT_0;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_6_TAG_VCDT_FILT_1;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_6_TAG_VCDT_FILT_2;
	// uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_6_TAG_VCDT_FILT_3,
	// uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_6_TAG_VCDT_FILT_4,
	// uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_6_TAG_VCDT_FILT_5,
	// uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_6_TAG_VCDT_FILT_6,
	// uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_6_TAG_VCDT_FILT_7,

	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_7_TAG_VCDT_FILT_0;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_7_TAG_VCDT_FILT_1;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_7_TAG_VCDT_FILT_2;
	// uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_7_TAG_VCDT_FILT_3,
	// uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_7_TAG_VCDT_FILT_4,
	// uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_7_TAG_VCDT_FILT_5,
	// uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_7_TAG_VCDT_FILT_6,
	// uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_7_TAG_VCDT_FILT_7,

	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_8_TAG_VCDT_FILT_0;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_8_TAG_VCDT_FILT_1;
	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_8_TAG_VCDT_FILT_2;
	// uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_8_TAG_VCDT_FILT_3,
	// uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_8_TAG_VCDT_FILT_4,
	// uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_8_TAG_VCDT_FILT_5,
	// uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_8_TAG_VCDT_FILT_6,
	// uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_8_TAG_VCDT_FILT_7,

	uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_9_TAG_VCDT_FILT_0;
	// uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_9_TAG_VCDT_FILT_1,
	// uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_9_TAG_VCDT_FILT_2,
	// uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_9_TAG_VCDT_FILT_3,
	// uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_9_TAG_VCDT_FILT_4,
	// uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_9_TAG_VCDT_FILT_5,
	// uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_9_TAG_VCDT_FILT_6,
	// uint32_t REG_SENINF_ROOT_SECURE_OUTMUX_9_TAG_VCDT_FILT_7,

	uint32_t REG_SENINF_ROOT_TSREC_CID_0;
	uint32_t REG_SENINF_ROOT_TSREC_CID_1;
	uint32_t REG_SENINF_ROOT_TSREC_CID_2;
} SENINF_TEE_REG;

extern SENINF_TEE_REG *g_preg_va;
extern int g_seninf_mux_vr;
extern int g_seninf_lock_flag;

extern int g_multi_sensor_individual_flag;
extern int g_multi_sensor_current_port;
extern unsigned int g_multi_secure_csi_port_front;
extern unsigned int g_multi_secure_csi_port_rear;

#endif
