/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2025 MediaTek Inc.
 */

#ifndef __SENINF_UTIL_H__
#define __SENINF_UTIL_H__

#include <linux/types.h>

#include "seninf_tee_reg.h"
#include "sys.h"

#define OUTMUX_INDEX_START 2
#define OUTMUX_INDEX_END 11

#define SENINF_TOP_OUTMUX_CG_EN 0

#define SENINF_ASYTOP_ASYNC_CFG 1

#define SENINF_OUTMUX0_SRC_SEL 2
#define SENINF_OUTMUX1_SRC_SEL 3
#define SENINF_OUTMUX2_SRC_SEL 4
#define SENINF_OUTMUX3_SRC_SEL 5
#define SENINF_OUTMUX4_SRC_SEL 6
#define SENINF_OUTMUX5_SRC_SEL 7
#define SENINF_OUTMUX6_SRC_SEL 8
#define SENINF_OUTMUX7_SRC_SEL 9
#define SENINF_OUTMUX8_SRC_SEL 10
#define SENINF_OUTMUX9_SRC_SEL 11

#define SENINF_OUTMUX0_CAM_RDY_GRP_SEL 12
#define SENINF_OUTMUX1_CAM_RDY_GRP_SEL 13
#define SENINF_OUTMUX2_CAM_RDY_GRP_SEL 14
#define SENINF_OUTMUX3_CAM_RDY_GRP_SEL 15
#define SENINF_OUTMUX4_CAM_RDY_GRP_SEL 16
#define SENINF_OUTMUX5_CAM_RDY_GRP_SEL 17
#define SENINF_OUTMUX6_CAM_RDY_GRP_SEL 18
#define SENINF_OUTMUX7_CAM_RDY_GRP_SEL 19
#define SENINF_OUTMUX8_CAM_RDY_GRP_SEL 20
#define SENINF_OUTMUX9_CAM_RDY_GRP_SEL 21

#define SENINF_OUTMUX0_CSR_CFG_CTRL 22
#define SENINF_OUTMUX1_CSR_CFG_CTRL 23
#define SENINF_OUTMUX2_CSR_CFG_CTRL 24
#define SENINF_OUTMUX3_CSR_CFG_CTRL 25
#define SENINF_OUTMUX4_CSR_CFG_CTRL 26
#define SENINF_OUTMUX5_CSR_CFG_CTRL 27
#define SENINF_OUTMUX6_CSR_CFG_CTRL 28
#define SENINF_OUTMUX7_CSR_CFG_CTRL 29
#define SENINF_OUTMUX8_CSR_CFG_CTRL 30
#define SENINF_OUTMUX9_CSR_CFG_CTRL 31

#define SENINF_ROOT_SENSOR_CID_0 32
#define SENINF_ROOT_SENSOR_CID_1 33
#define SENINF_ROOT_SENSOR_CID_2 34
#define SENINF_ROOT_SENSOR_CID_3 35
#define SENINF_ROOT_SENSOR_CID_4 36
#define SENINF_ROOT_SENSOR_CID_5 37

#define SENINF_ROOT_OUTMUX_CID_0 38
#define SENINF_ROOT_OUTMUX_CID_1 39
#define SENINF_ROOT_OUTMUX_CID_2 40

#define SENINF_ROOT_RDY_MASK_CID_0 41
#define SENINF_ROOT_RDY_MASK_CID_1 42
#define SENINF_ROOT_RDY_MASK_CID_2 43

#define SENINF_ROOT_SECURE_OUTMUX_0_TAG_VCDT_FILT_0 44
#define SENINF_ROOT_SECURE_OUTMUX_0_TAG_VCDT_FILT_1 45
#define SENINF_ROOT_SECURE_OUTMUX_0_TAG_VCDT_FILT_2 46
#define SENINF_ROOT_SECURE_OUTMUX_0_TAG_VCDT_FILT_3 47
#define SENINF_ROOT_SECURE_OUTMUX_0_TAG_VCDT_FILT_4 48
#define SENINF_ROOT_SECURE_OUTMUX_0_TAG_VCDT_FILT_5 49
#define SENINF_ROOT_SECURE_OUTMUX_0_TAG_VCDT_FILT_6 50
#define SENINF_ROOT_SECURE_OUTMUX_0_TAG_VCDT_FILT_7 51

#define SENINF_ROOT_SECURE_OUTMUX_1_TAG_VCDT_FILT_0 52
#define SENINF_ROOT_SECURE_OUTMUX_1_TAG_VCDT_FILT_1 53
#define SENINF_ROOT_SECURE_OUTMUX_1_TAG_VCDT_FILT_2 54
#define SENINF_ROOT_SECURE_OUTMUX_1_TAG_VCDT_FILT_3 55
#define SENINF_ROOT_SECURE_OUTMUX_1_TAG_VCDT_FILT_4 56
#define SENINF_ROOT_SECURE_OUTMUX_1_TAG_VCDT_FILT_5 57
#define SENINF_ROOT_SECURE_OUTMUX_1_TAG_VCDT_FILT_6 58
#define SENINF_ROOT_SECURE_OUTMUX_1_TAG_VCDT_FILT_7 59

#define SENINF_ROOT_SECURE_OUTMUX_2_TAG_VCDT_FILT_0 60
#define SENINF_ROOT_SECURE_OUTMUX_2_TAG_VCDT_FILT_1 61
#define SENINF_ROOT_SECURE_OUTMUX_2_TAG_VCDT_FILT_2 62
#define SENINF_ROOT_SECURE_OUTMUX_2_TAG_VCDT_FILT_3 63
#define SENINF_ROOT_SECURE_OUTMUX_2_TAG_VCDT_FILT_4 64
#define SENINF_ROOT_SECURE_OUTMUX_2_TAG_VCDT_FILT_5 65
#define SENINF_ROOT_SECURE_OUTMUX_2_TAG_VCDT_FILT_6 66
#define SENINF_ROOT_SECURE_OUTMUX_2_TAG_VCDT_FILT_7 67

#define SENINF_ROOT_SECURE_OUTMUX_3_TAG_VCDT_FILT_0 68
#define SENINF_ROOT_SECURE_OUTMUX_3_TAG_VCDT_FILT_1 69
#define SENINF_ROOT_SECURE_OUTMUX_3_TAG_VCDT_FILT_2 70
#define SENINF_ROOT_SECURE_OUTMUX_3_TAG_VCDT_FILT_3 71
#define SENINF_ROOT_SECURE_OUTMUX_3_TAG_VCDT_FILT_4 72
#define SENINF_ROOT_SECURE_OUTMUX_3_TAG_VCDT_FILT_5 73
#define SENINF_ROOT_SECURE_OUTMUX_3_TAG_VCDT_FILT_6 74
#define SENINF_ROOT_SECURE_OUTMUX_3_TAG_VCDT_FILT_7 75

#define SENINF_ROOT_SECURE_OUTMUX_4_TAG_VCDT_FILT_0 76
#define SENINF_ROOT_SECURE_OUTMUX_4_TAG_VCDT_FILT_1 77
#define SENINF_ROOT_SECURE_OUTMUX_4_TAG_VCDT_FILT_2 78
#define SENINF_ROOT_SECURE_OUTMUX_4_TAG_VCDT_FILT_3 79
#define SENINF_ROOT_SECURE_OUTMUX_4_TAG_VCDT_FILT_4 80
#define SENINF_ROOT_SECURE_OUTMUX_4_TAG_VCDT_FILT_5 81
#define SENINF_ROOT_SECURE_OUTMUX_4_TAG_VCDT_FILT_6 82
#define SENINF_ROOT_SECURE_OUTMUX_4_TAG_VCDT_FILT_7 83

#define SENINF_ROOT_SECURE_OUTMUX_5_TAG_VCDT_FILT_0 84
#define SENINF_ROOT_SECURE_OUTMUX_5_TAG_VCDT_FILT_1 85
#define SENINF_ROOT_SECURE_OUTMUX_5_TAG_VCDT_FILT_2 86
#define SENINF_ROOT_SECURE_OUTMUX_5_TAG_VCDT_FILT_3 87
#define SENINF_ROOT_SECURE_OUTMUX_5_TAG_VCDT_FILT_4 88
#define SENINF_ROOT_SECURE_OUTMUX_5_TAG_VCDT_FILT_5 89
#define SENINF_ROOT_SECURE_OUTMUX_5_TAG_VCDT_FILT_6 90
#define SENINF_ROOT_SECURE_OUTMUX_5_TAG_VCDT_FILT_7 91

#define SENINF_ROOT_SECURE_OUTMUX_6_TAG_VCDT_FILT_0 92
#define SENINF_ROOT_SECURE_OUTMUX_6_TAG_VCDT_FILT_1 93
#define SENINF_ROOT_SECURE_OUTMUX_6_TAG_VCDT_FILT_2 94

#define SENINF_ROOT_SECURE_OUTMUX_7_TAG_VCDT_FILT_0 95
#define SENINF_ROOT_SECURE_OUTMUX_7_TAG_VCDT_FILT_1 96
#define SENINF_ROOT_SECURE_OUTMUX_7_TAG_VCDT_FILT_2 97

#define SENINF_ROOT_SECURE_OUTMUX_8_TAG_VCDT_FILT_0 98
#define SENINF_ROOT_SECURE_OUTMUX_8_TAG_VCDT_FILT_1 99
#define SENINF_ROOT_SECURE_OUTMUX_8_TAG_VCDT_FILT_2 100

#define SENINF_ROOT_SECURE_OUTMUX_9_TAG_VCDT_FILT_0 101

#define SENINF_ROOT_TSREC_CID_0 102
#define SENINF_ROOT_TSREC_CID_1 103
#define SENINF_ROOT_TSREC_CID_2 104


#define SENINF_CID_EN 1

static const uint32_t gseninf_drv_reg_addr[] = {
	SENINF_TEE_REG_ADDR_SENINF_TOP_OUTMUX_CG_EN,//0
	SENINF_TEE_REG_ADDR_SENINF_ASYTOP_ASYNC_CFG,//1

	SENINF_TEE_REG_ADDR_SENINF_OUTMUX0_SRC_SEL,//2
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX1_SRC_SEL,//3
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX2_SRC_SEL,//4
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX3_SRC_SEL,//5
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX4_SRC_SEL,//6
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX5_SRC_SEL,//7
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX6_SRC_SEL,//8
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX7_SRC_SEL,//9
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX8_SRC_SEL,//10
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX9_SRC_SEL,//11

	SENINF_TEE_REG_ADDR_SENINF_OUTMUX0_CAM_RDY_GRP_SEL,//12
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX1_CAM_RDY_GRP_SEL,//13
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX2_CAM_RDY_GRP_SEL,//14
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX3_CAM_RDY_GRP_SEL,//15
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX4_CAM_RDY_GRP_SEL,//16
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX5_CAM_RDY_GRP_SEL,//17
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX6_CAM_RDY_GRP_SEL,//18
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX7_CAM_RDY_GRP_SEL,//19
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX8_CAM_RDY_GRP_SEL,//20
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX9_CAM_RDY_GRP_SEL,//21

	SENINF_TEE_REG_ADDR_SENINF_OUTMUX0_CSR_CFG_CTRL,//22
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX1_CSR_CFG_CTRL,//23
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX2_CSR_CFG_CTRL,//24
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX3_CSR_CFG_CTRL,//25
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX4_CSR_CFG_CTRL,//26
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX5_CSR_CFG_CTRL,//27
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX6_CSR_CFG_CTRL,//28
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX7_CSR_CFG_CTRL,//29
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX8_CSR_CFG_CTRL,//30
	SENINF_TEE_REG_ADDR_SENINF_OUTMUX9_CSR_CFG_CTRL,//31
	/* SENSOR CID base addr: 0x3A002000 */
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SENSOR_CID_0,//32
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SENSOR_CID_1,//33
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SENSOR_CID_2,//34
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SENSOR_CID_3,//35
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SENSOR_CID_4,//36
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SENSOR_CID_5,//37
	/* CID base addr: 0x3A002000 */
	SENINF_TEE_REG_ADDR_SENINF_ROOT_OUTMUX_CID_0,//38
	SENINF_TEE_REG_ADDR_SENINF_ROOT_OUTMUX_CID_1,//39
	SENINF_TEE_REG_ADDR_SENINF_ROOT_OUTMUX_CID_2,//40
	/* RDY MASK CID base addr: 0x3A002000 */
	SENINF_TEE_REG_ADDR_SENINF_ROOT_RDY_MASK_CID_0,//41
	SENINF_TEE_REG_ADDR_SENINF_ROOT_RDY_MASK_CID_1,//42
	SENINF_TEE_REG_ADDR_SENINF_ROOT_RDY_MASK_CID_2,//43
	/* Seninf outmux tag VCDT base addr: 0x3A002000 */
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_0_TAG_VCDT_FILT_0,//44
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_0_TAG_VCDT_FILT_1,//45
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_0_TAG_VCDT_FILT_2,//46
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_0_TAG_VCDT_FILT_3,//47
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_0_TAG_VCDT_FILT_4,//48
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_0_TAG_VCDT_FILT_5,//49
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_0_TAG_VCDT_FILT_6,//50
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_0_TAG_VCDT_FILT_7,//51

	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_1_TAG_VCDT_FILT_0,//52
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_1_TAG_VCDT_FILT_1,//53
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_1_TAG_VCDT_FILT_2,//54
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_1_TAG_VCDT_FILT_3,//55
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_1_TAG_VCDT_FILT_4,//56
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_1_TAG_VCDT_FILT_5,//57
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_1_TAG_VCDT_FILT_6,//58
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_1_TAG_VCDT_FILT_7,//59

	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_2_TAG_VCDT_FILT_0,//60
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_2_TAG_VCDT_FILT_1,//61
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_2_TAG_VCDT_FILT_2,//62
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_2_TAG_VCDT_FILT_3,//63
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_2_TAG_VCDT_FILT_4,//64
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_2_TAG_VCDT_FILT_5,//65
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_2_TAG_VCDT_FILT_6,//66
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_2_TAG_VCDT_FILT_7,//67

	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_3_TAG_VCDT_FILT_0,//68
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_3_TAG_VCDT_FILT_1,//69
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_3_TAG_VCDT_FILT_2,//70
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_3_TAG_VCDT_FILT_3,//71
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_3_TAG_VCDT_FILT_4,//72
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_3_TAG_VCDT_FILT_5,//73
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_3_TAG_VCDT_FILT_6,//74
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_3_TAG_VCDT_FILT_7,//75

	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_4_TAG_VCDT_FILT_0,//76
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_4_TAG_VCDT_FILT_1,//77
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_4_TAG_VCDT_FILT_2,//78
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_4_TAG_VCDT_FILT_3,//79
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_4_TAG_VCDT_FILT_4,//80
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_4_TAG_VCDT_FILT_5,//81
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_4_TAG_VCDT_FILT_6,//82
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_4_TAG_VCDT_FILT_7,//83

	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_5_TAG_VCDT_FILT_0,//84
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_5_TAG_VCDT_FILT_1,//85
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_5_TAG_VCDT_FILT_2,//86
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_5_TAG_VCDT_FILT_3,//87
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_5_TAG_VCDT_FILT_4,//88
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_5_TAG_VCDT_FILT_5,//89
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_5_TAG_VCDT_FILT_6,//90
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_5_TAG_VCDT_FILT_7,//91

	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_6_TAG_VCDT_FILT_0,//92
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_6_TAG_VCDT_FILT_1,//93
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_6_TAG_VCDT_FILT_2,//94
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_6_TAG_VCDT_FILT_3,//31
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_6_TAG_VCDT_FILT_4,//32
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_6_TAG_VCDT_FILT_5,//33
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_6_TAG_VCDT_FILT_6,//31
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_6_TAG_VCDT_FILT_7,//32

	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_7_TAG_VCDT_FILT_0,//95
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_7_TAG_VCDT_FILT_1,//96
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_7_TAG_VCDT_FILT_2,//97
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_7_TAG_VCDT_FILT_3,//31
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_7_TAG_VCDT_FILT_4,//32
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_7_TAG_VCDT_FILT_5,//33
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_7_TAG_VCDT_FILT_6,//31
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_7_TAG_VCDT_FILT_7,//32

	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_8_TAG_VCDT_FILT_0,//98
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_8_TAG_VCDT_FILT_1,//99
	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_8_TAG_VCDT_FILT_2,//100
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_8_TAG_VCDT_FILT_3,//31
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_8_TAG_VCDT_FILT_4,//32
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_8_TAG_VCDT_FILT_5,//33
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_8_TAG_VCDT_FILT_6,//31
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_8_TAG_VCDT_FILT_7,//32

	SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_9_TAG_VCDT_FILT_0,//101
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_9_TAG_VCDT_FILT_1,//32
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_9_TAG_VCDT_FILT_2,//33
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_9_TAG_VCDT_FILT_3,//31
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_9_TAG_VCDT_FILT_4,//32
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_9_TAG_VCDT_FILT_5,//33
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_9_TAG_VCDT_FILT_6,//31
	// SENINF_TEE_REG_ADDR_SENINF_ROOT_SECURE_OUTMUX_9_TAG_VCDT_FILT_7,//32

	SENINF_TEE_REG_ADDR_SENINF_ROOT_TSREC_CID_0,//102
	SENINF_TEE_REG_ADDR_SENINF_ROOT_TSREC_CID_1,//103
	SENINF_TEE_REG_ADDR_SENINF_ROOT_TSREC_CID_2,//104
};

#define SECIO_SENINF_ROOT SECIO_SENINF_MUX20
#define SECIO_SENINF_TOP SECIO_SENINF_MUX21
#define SECIO_SENINF_ASYTOP SECIO_SENINF_MUX22

static const uint32_t gseninf_drv_reg_base[] = {
	SECIO_SENINF_TOP,

	SECIO_SENINF_ASYTOP,

	SECIO_SENINF_MUX1,
	SECIO_SENINF_MUX2,
	SECIO_SENINF_MUX3,
	SECIO_SENINF_MUX4,
	SECIO_SENINF_MUX5,
	SECIO_SENINF_MUX6,
	SECIO_SENINF_MUX7,
	SECIO_SENINF_MUX8,
	SECIO_SENINF_MUX9,
	SECIO_SENINF_MUX10,

	SECIO_SENINF_MUX1,
	SECIO_SENINF_MUX2,
	SECIO_SENINF_MUX3,
	SECIO_SENINF_MUX4,
	SECIO_SENINF_MUX5,
	SECIO_SENINF_MUX6,
	SECIO_SENINF_MUX7,
	SECIO_SENINF_MUX8,
	SECIO_SENINF_MUX9,
	SECIO_SENINF_MUX10,

	SECIO_SENINF_MUX1,
	SECIO_SENINF_MUX2,
	SECIO_SENINF_MUX3,
	SECIO_SENINF_MUX4,
	SECIO_SENINF_MUX5,
	SECIO_SENINF_MUX6,
	SECIO_SENINF_MUX7,
	SECIO_SENINF_MUX8,
	SECIO_SENINF_MUX9,
	SECIO_SENINF_MUX10,

	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,

	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,

	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	/* OUTMUX_0_TAG */
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	/* OUTMUX_1_TAG */
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	/* OUTMUX_2_TAG */
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	/* OUTMUX_3_TAG */
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	/* OUTMUX_4_TAG */
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	/* OUTMUX_5_TAG */
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	/* OUTMUX_6_TAG */
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	// SECIO_SENINF_ROOT,
	// SECIO_SENINF_ROOT,
	// SECIO_SENINF_ROOT,
	// SECIO_SENINF_ROOT,
	// SECIO_SENINF_ROOT,
	/* OUTMUX_7_TAG */
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	// SECIO_SENINF_ROOT,
	// SECIO_SENINF_ROOT,
	// SECIO_SENINF_ROOT,
	// SECIO_SENINF_ROOT,
	// SECIO_SENINF_ROOT,
	/* OUTMUX_8_TAG */
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	// SECIO_SENINF_ROOT,
	// SECIO_SENINF_ROOT,
	// SECIO_SENINF_ROOT,
	// SECIO_SENINF_ROOT,
	// SECIO_SENINF_ROOT,
	/* OUTMUX_9_TAG */
	SECIO_SENINF_ROOT,
	// SECIO_SENINF_ROOT,
	// SECIO_SENINF_ROOT,
	// SECIO_SENINF_ROOT,
	// SECIO_SENINF_ROOT,
	// SECIO_SENINF_ROOT,
	// SECIO_SENINF_ROOT,
	// SECIO_SENINF_ROOT,

	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
	SECIO_SENINF_ROOT,
};

static const uint32_t gseninf_drv_reg_base_addr[] = {
	0x3A400000, /* SENINF_TOP */

	0x3A401000, /* SENINF_ASYTOP */

	0x3A200000, /* SENINF_OUTMUX0 */
	0x3A210000, /* SENINF_OUTMUX1 */
	0x3A220000, /* SENINF_OUTMUX2 */
	0x3A230000, /* SENINF_OUTMUX3 */
	0x3A240000, /* SENINF_OUTMUX4 */
	0x3A250000, /* SENINF_OUTMUX5 */
	0x3A260000, /* SENINF_OUTMUX6 */
	0x3A270000, /* SENINF_OUTMUX7 */
	0x3A280000, /* SENINF_OUTMUX8 */
	0x3A290000, /* SENINF_OUTMUX9 */

	0x3A200000, /* SENINF_OUTMUX0 */
	0x3A210000, /* SENINF_OUTMUX1 */
	0x3A220000, /* SENINF_OUTMUX2 */
	0x3A230000, /* SENINF_OUTMUX3 */
	0x3A240000, /* SENINF_OUTMUX4 */
	0x3A250000, /* SENINF_OUTMUX5 */
	0x3A260000, /* SENINF_OUTMUX6 */
	0x3A270000, /* SENINF_OUTMUX7 */
	0x3A280000, /* SENINF_OUTMUX8 */
	0x3A290000, /* SENINF_OUTMUX9 */

	0x3A200000, /* SENINF_OUTMUX0 */
	0x3A210000, /* SENINF_OUTMUX1 */
	0x3A220000, /* SENINF_OUTMUX2 */
	0x3A230000, /* SENINF_OUTMUX3 */
	0x3A240000, /* SENINF_OUTMUX4 */
	0x3A250000, /* SENINF_OUTMUX5 */
	0x3A260000, /* SENINF_OUTMUX6 */
	0x3A270000, /* SENINF_OUTMUX7 */
	0x3A280000, /* SENINF_OUTMUX8 */
	0x3A290000, /* SENINF_OUTMUX9 */

	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */

	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */

	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */

	/* OUTMUX_0_TAG */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	/* OUTMUX_1_TAG */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	/* OUTMUX_2_TAG */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	/* OUTMUX_3_TAG */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	/* OUTMUX_4_TAG */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	/* OUTMUX_5_TAG */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	/* OUTMUX_6_TAG */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	// 0x3A002000,/* SENINF_ROOT */
	// 0x3A002000,/* SENINF_ROOT */
	// 0x3A002000,/* SENINF_ROOT */
	// 0x3A002000,/* SENINF_ROOT */
	// 0x3A002000,/* SENINF_ROOT */
	/* OUTMUX_7_TAG */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	// 0x3A002000,/* SENINF_ROOT */
	// 0x3A002000,/* SENINF_ROOT */
	// 0x3A002000,/* SENINF_ROOT */
	// 0x3A002000,/* SENINF_ROOT */
	// 0x3A002000,/* SENINF_ROOT */
	/* OUTMUX_8_TAG */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	// 0x3A002000,/* SENINF_ROOT */
	// 0x3A002000,/* SENINF_ROOT */
	// 0x3A002000,/* SENINF_ROOT */
	// 0x3A002000,/* SENINF_ROOT */
	// 0x3A002000,/* SENINF_ROOT */
	/* OUTMUX_9_TAG */
	0x3A002000,/* SENINF_ROOT */
	// 0x3A002000,/* SENINF_ROOT */
	// 0x3A002000,/* SENINF_ROOT */
	// 0x3A002000,/* SENINF_ROOT */
	// 0x3A002000,/* SENINF_ROOT */
	// 0x3A002000,/* SENINF_ROOT */
	// 0x3A002000,/* SENINF_ROOT */
	// 0x3A002000,/* SENINF_ROOT */

	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
	0x3A002000,/* SENINF_ROOT */
};

#endif
