/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2025 MediaTek Inc.
 */

#ifndef __SYS_H
#define __SYS_H

#include <linux/types.h>

#include "trustzone.h"

/* SECURE_IO usage */
enum SECIO_TYPE {
	SECIO_INVALID = 0,
	SECIO_GCE = 1,
	SECIO_ISP_CAM_A = 2,
	SECIO_ISP_CAM_B = 3,
	SECIO_DIP_TOP = 4,
	SECIO_DAPC_AO_MM0 = 5,
	SECIO_DAPC_AO_MM1 = 6,
	SECIO_DIP_DMA = 7,
	SECIO_SENINF_MUX1 = 8,
	SECIO_SENINF_MUX2 = 9,
	SECIO_SENINF_MUX3 = 10,
	SECIO_SENINF_MUX4 = 11,
	SECIO_SENINF_MUX5 = 12,
	SECIO_SENINF_MUX6 = 13,
	SECIO_SENINF_MUX7 = 14,
	SECIO_SENINF_MUX8 = 15,
	SECIO_ISP_CAM_C = 16,
	SECIO_FD_TOP = 17,
	SECIO_GCE_M = 18,
	SECIO_ISP_CAM_A2 = 19,
	SECIO_ISP_CAM_B2 = 20,
	SECIO_ISP_CAM_C2 = 21,
	SECIO_ISP_CAM_SYS = 22,
	SECIO_M4U_CAM_SMI_LARB0 = 23,
	SECIO_M4U_CAM_SMI_LARB1 = 24,
	SECIO_M4U_CAM_SMI_LARB2 = 25,
	SECIO_M4U_CAM_SMI_LARB3 = 26,
	SECIO_M4U_CAM_SMI_LARB4 = 27,
	SECIO_M4U_CAM_SMI_LARB5 = 28,
	SECIO_M4U_CAM_SMI_LARB6 = 29,
	SECIO_ISP_YUV_CAM_A = 30,
	SECIO_ISP_YUV_CAM_B = 31,
	SECIO_ISP_YUV_CAM_C = 32,
	SECIO_SENINF_MUX9 = 33,
	SECIO_SENINF_MUX10 = 34,
	SECIO_SENINF_MUX11 = 35,
	SECIO_SENINF_MUX12 = 36,
	SECIO_SENINF_MUX13 = 37,
	SECIO_SENINF_MUX14 = 38,
	SECIO_SENINF_MUX15 = 39,
	SECIO_SENINF_MUX16 = 40,
	SECIO_SENINF_MUX17 = 41,
	SECIO_SENINF_MUX18 = 42,
	SECIO_SENINF_MUX19 = 43,
	SECIO_SENINF_MUX20 = 44,
	SECIO_SENINF_MUX21 = 45,
	SECIO_SENINF_MUX22 = 46,
	SECIO_ISP_INFRA_S = 47,
	SECIO_SENINF_CAMMUX = 48,
	SECIO_GCE_SECURITY = 49,
	SECIO_GCE_M_SECURITY = 50,
	SECIO_GCE_D2 = 51,
	SECIO_GCE_M2 = 52,
	SECIO_GCE_D2_SECURITY = 53,
	SECIO_GCE_M2_SECURITY = 54,

	SECIO_MAX = 55,
};

TZ_RESULT SECIO_WRITE(uint32_t io_type, uint32_t reg_offset, uint32_t write_val);
TZ_RESULT SECIO_READ(uint32_t io_type, uint32_t reg_offset, uint32_t *read_val);

#endif
