# SPDX-License-Identifier: GPL-2.0

ccflags-$(CONFIG_MTK_SRCLKEN_RC_V1) += -D SRCLKEN_RC_SUPPORT
ccflags-y += -I$(DEVICES_MODULES_PATH)/drivers/pci/controller/
ccflags-y += -I$(srctree)/drivers/pci/controller/
