load("//build/bazel_mgk_rules:mgk_ddk_ko.bzl", "define_mgk_ddk_ko")
load("@mgk_info//:kernel_version.bzl", "kernel_version")

package(
    default_visibility = [
        "//visibility:public",
    ],
)

filegroup(
    name = "ddk_kconfigs",
    srcs = glob([
        "**/Kconfig",
    ]),
)

filegroup(
    name = "ddk_makefile",
    srcs = glob([
        "**/Makefile",
        "**/Kbuild",
        "**/*.c",
        "**/*.h",
    ]),
)

define_mgk_ddk_ko(
    name = "ktz8866",
    srcs = [
        "ktz8866.c",
    ],
    hdrs = [
        "ktz8866.h",
    ],
    includes = ["."],
)

define_mgk_ddk_ko(
    name = "panel-aw37501-i2c",
    srcs = [
        "panel-aw37501-i2c.c",
    ],
    includes = ["."],
)

define_mgk_ddk_ko(
    name = "rt4831a",
    srcs = [
        "rt4831a.c",
    ],
    hdrs = [
        "rt4831a.h",
    ],
    includes = ["."],
)

PANELS = [
    "panel-hx83112b-auo-cmd-60hz-rt5081",
    "panel-hx83112b-auo-vdo-60hz-rt5081",
    "panel-nt35521_hd_dsi_vdo_truly_rt5081",
    "panel-nt35695b-auo-vdo",
    "panel-sc-nt36672c-vdo-90hz-6382",
    "panel-td4320-fhdp-dsi-vdo-auo-rt5081",
    "panel-alpha-jdi-nt36672e-cphy-vdo",
    "panel-alpha-jdi-nt36672e-vdo-144hz",
    "panel-nt35695b-auo-cmd",
    "panel-nt37707-c2v-arp",
    "panel-rm692h5-cmd",
    "panel-rm692h5-alpha-cmd-spr",
    "panel-rm692h5-alpha-cmd-spr-mipichg",
    "panel-rm692h5-alpha-cmd-spr-144hz",
    "panel-tianma-r66451-cmd-120hz",
    "panel-tianma-r66451-cmd-120hz-wa",
    "panel-truly-nt35595-cmd",
    "panel-truly-td4330-vdo",
    "panel-nt36672c-fhdp-dsi-vdo-dsc-txd-boe",
    "panel-alpha-jdi-nt36672e-vdo-120hz-frameratev5",
    "panel-samsung-op-cmd",
    "panel-samsung-op-cmd-msync2",
    "panel-alpha-samsung-s6e3hae-wqhd-dphy-cmd-120hz",
    "panel-tianma-nt36672e-vdo-120hz-hfp",
    "panel-tianma-nt36672e-vdo-120hz-vfp",
    "panel-tianma-nt36672e-vdo-120hz-vfp-6382",
    "panel-tianma-hx83102j-vdo",
    "panel-nt36672a-rt4801-vdo",
    "panel-alpha-jdi-nt36672e-vdo-120hz",
    "panel-alpha-jdi-nt36672e-vdo-120hz-hfp",
    "panel-alpha-jdi-nt36672e-vdo-120hz-threshold",
    "panel-alpha-jdi-nt36672e-vdo-144hz-hfp",
    "panel-alpha-jdi-nt36672e-vdo-60hz",
    "panel-boe-hx83102j-vdo",
    "panel-nt37801-cmd-120hz",
    "panel-nt37801-cmd-fhd",
    "panel-nt37801-cmd-fhd-plus",
    "panel-nt37801-cmd-fhd-10bit",
    "panel-nt37801-cmd-ltpo",
    "panel-nt37801-cmd-spr",
    "panel-truly-td4330-cmd",
    "panel-samsung-s68fc01-vdo-aod",
    "panel_ac180_p_3_a0020_dsi_cmd",
    "oplus_panel/oplus_display_dsi_primary",
    "panel-hx-nt37701-dphy-cmd",
    "panel-hx-nt37701-dphy-cmd-120hz",
]

PANELS_V1 = [
    "ac242_p_1_a0017_fhd_vdo",
    "AC160_P_3_A0004_cmd_panel",
    "AC160_P_7_A0001_cmd_panel",
    "ac124_p_3_a0004_cmd_panel",
    "ac124_p_b_a0012_cmd_panel",
    "oplus24928_hx_nt36523n_vdo_90hz",
    "ac386_p_3_a0025_vdo_panel",
]

[define_mgk_ddk_ko(
    name = "{}".format(p.replace("oplus_panel/", "")),
    srcs = [
        "{}.c".format(p),
    ],
    header_deps = [
        "//kernel_device_modules-{}/drivers/gpu/drm/mediatek/mediatek_v2:ddk_public_headers".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/mtk-interconnect:mtk_interconnect".format(kernel_version),
        "//kernel_device_modules-{}/drivers/gpu/drm/mediatek/mml:mml_public_headers".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/slbc:headers".format(kernel_version),
        "//kernel_device_modules-{}/drivers/gpu/drm/mediatek/dpc:ddk_public_headers".format(kernel_version),
    ],
    hdrs = glob([
        "**/*.h".format(p),
    ]),
    includes = [
        ".",
        "oplus_panel",
    ],
    local_defines = [
        "OPLUS_FEATURE_DISPLAY",
        "OPLUS_FEATURE_DISPLAY_ADFR",
        "OPLUS_FEATURE_DISPLAY_HPWM",
        "OPLUS_FEATURE_DISPLAY_APOLLO",
        "OPLUS_FEATURE_DISPLAY_ONSCREENFINGERPRINT",
        "OPLUS_FEATURE_DISPLAY_MAINLINE",

    ],
    copts = [
        "-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include/mt-plat",
        "-I$(DEVICE_MODULES_PATH)/drivers/gpu/drm/mediatek/mediatek_v2/oplus_drm",
    ],
    ko_deps = [
        "panel-aw37501-i2c",
        "ktz8866",
        "//kernel_device_modules-{}/drivers/gpu/drm/mediatek/mediatek_v2:mtk_panel_ext".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/gate_ic:rt4831a_drv".format(kernel_version),
        "//kernel_device_modules-{}/drivers/gpu/drm/mediatek/mediatek_v2:mediatek-drm".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/boot_common:mtk_boot_common".format(kernel_version),
        "//kernel_device_modules-{}/drivers/soc/oplus/device_info:device_info".format(kernel_version),
        "//kernel_device_modules-{}/drivers/leds:leds-mtk".format(kernel_version),
    ],
) for p in PANELS]

[define_mgk_ddk_ko(
    name = "{}".format(p.replace("oplus_panel/", "")),
    srcs = [
        "{}.c".format(p),
    ],
    header_deps = [
        "//kernel_device_modules-{}/drivers/gpu/drm/mediatek/mediatek_v2:ddk_public_headers".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/mtk-interconnect:mtk_interconnect".format(kernel_version),
        "//kernel_device_modules-{}/drivers/gpu/drm/mediatek/mml:mml_public_headers".format(kernel_version),
        "//kernel_device_modules-{}/drivers/gpu/drm/mediatek/mediatek_v2/v1:ddk_public_headers".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/slbc:headers".format(kernel_version),
        "//kernel_device_modules-{}/drivers/gpu/drm/mediatek/dpc:ddk_public_headers".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/lpm_legacy:ddk_public_headers".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/lpm_legacy/modules/debug/k6895:ddk_public_headers".format(kernel_version),
    ],
    hdrs = glob([
        "**/*.h".format(p),
    ]),
    includes = [
        ".",
        "oplus_panel",
    ],
    local_defines = [
        "OPLUS_FEATURE_DISPLAY",
        "OPLUS_FEATURE_DISPLAY_ADFR",
        "OPLUS_FEATURE_DISPLAY_HPWM",
        "OPLUS_FEATURE_DISPLAY_APOLLO",
        "OPLUS_FEATURE_DISPLAY_ONSCREENFINGERPRINT",
        "OPLUS_FEATURE_DISPLAY_TEMP_COMPENSATION",
        "CONFIG_TOUCHPANEL_NOTIFY",
        "CONFIG_OPLUS_MTK_DRM_GKI_NOTIFY",
    ],
    copts = [
        "-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include/mt-plat",
        "-I$(DEVICE_MODULES_PATH)/drivers/gpu/drm/mediatek/mediatek_v2/v1/oplus_drm_v1",
        "-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/lpm_legacy/modules/debug/k6895/inc",
    ],
    ko_deps = [
        "panel-aw37501-i2c",
        "ktz8866",
        "//kernel_device_modules-{}/drivers/gpu/drm/mediatek/mediatek_v2:mtk_panel_ext".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/gate_ic:rt4831a_drv".format(kernel_version),
        "//kernel_device_modules-{}/drivers/gpu/drm/mediatek/mediatek_v2:mediatek-drm".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/boot_common:mtk_boot_common".format(kernel_version),
        "//kernel_device_modules-{}/drivers/soc/oplus/device_info:device_info".format(kernel_version),
        "//kernel_device_modules-{}/drivers/gpu/drm/mediatek/mediatek_v2/v1:mediatek_drm_v1".format(kernel_version),
        "//kernel_device_modules-{}/drivers/misc/mediatek/cmdq/mailbox:mtk-cmdq-drv-ext".format(kernel_version),
        "//kernel_device_modules-{}/drivers/leds:leds-mtk".format(kernel_version),
        "//kernel_device_modules-{}/drivers/soc/oplus/boot:oplus_bsp_boot_projectinfo".format(kernel_version),
        "//kernel_device_modules-{}/drivers/pinctrl/mediatek:pinctrl-mtk-common-v2_debug".format(kernel_version),
        "//kernel_device_modules-{}/drivers/gpu/drm/mediatek/mediatek_v2:mtk_disp_notify".format(kernel_version),
        "//kernel_device_modules-{}/drivers/base/touchpanel_notify:oplus_bsp_tp_notify".format(kernel_version),
    ],
) for p in PANELS_V1]
