/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2024 MediaTek Inc.
 * Author: Yc Li <yc.li@mediatek.com>
 */
#ifndef MT6991_SMI_HWCCF_H
#define MT6991_SMI_HWCCF_H

#include <dt-bindings/memory/mtk-smi-hwccf.h>

/* Subsys domain */
#define MT6991_SMI_PD_OVL0             MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 0)
#define MT6991_SMI_PD_OVL1             MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 1)
#define MT6991_SMI_PD_DIS0             MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 2)
#define MT6991_SMI_PD_DIS1             MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 3)
#define MT6991_SMI_PD_DISP_VCORE       MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 4)
#define MT6991_SMI_PD_MML0             MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 5)
#define MT6991_SMI_PD_MML1             MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 6)
#define MT6991_SMI_PD_VDE1             MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 7)
#define MT6991_SMI_PD_VDE0             MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 8)
#define MT6991_SMI_PD_VEN0             MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 9)
#define MT6991_SMI_PD_VEN1             MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 10)
#define MT6991_SMI_PD_VEN2             MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 11)
#define MT6991_SMI_PD_ISP_VCORE        MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 12)
#define MT6991_SMI_PD_ISP_MAIN         MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 13)
#define MT6991_SMI_PD_ISP_DIP          MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 14)
#define MT6991_SMI_PD_ISP_WPE_EIS      MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 15)
#define MT6991_SMI_PD_ISP_WPE_TNR      MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 16)
#define MT6991_SMI_PD_ISP_WPE_LITE     MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 17)
#define MT6991_SMI_PD_ISP_TRAW         MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 18)
#define MT6991_SMI_PD_CAM_VCORE        MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 19)
#define MT6991_SMI_PD_CAM_MAIN         MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 20)
#define MT6991_SMI_PD_CAM_CCU          MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 21)
#define MT6991_SMI_PD_CAM_RAWA         MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 22)
#define MT6991_SMI_PD_CAM_RAWB         MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 23)
#define MT6991_SMI_PD_CAM_RAWC         MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 24)
#define MT6991_SMI_PD_CAM_MRAW         MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 25)
#define MT6991_SMI_PD_MMINFRA0         MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 26)
#define MT6991_SMI_PD_MMINFRA1         MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 27)

#endif
