/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2024 MediaTek Inc.
 * Author: Yc Li <yc.li@mediatek.com>
 */
#ifndef MT6993_SMI_PD_H
#define MT6993_SMI_PD_H

#include <dt-bindings/memory/mtk-smi-hwccf.h>

/* disp */
#define MT6993_SMI_PD_OVL0              MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 0)
#define MT6993_SMI_PD_OVL1              MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 1)
#define MT6993_SMI_PD_OVL2              MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 2)
#define MT6993_SMI_PD_DIS0_A            MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 3)
#define MT6993_SMI_PD_DIS0_B            MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 4)
#define MT6993_SMI_PD_DIS1_A            MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 5)
#define MT6993_SMI_PD_DIS1_B            MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 6)
#define MT6993_SMI_PD_VDISP_PERI        MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 7)
#define MT6993_SMI_PD_DISP_VCORE        MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 8)
#define MT6993_SMI_PD_MML0              MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 9)
#define MT6993_SMI_PD_MML1              MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 10)
#define MT6993_SMI_PD_MML2              MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 11)

/* vdec */
#define MT6993_SMI_PD_VDE1              MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 12)
#define MT6993_SMI_PD_VDE0              MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 13)

/* venc */
#define MT6993_SMI_PD_VEN0              MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 14)
#define MT6993_SMI_PD_VEN1              MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 15)
#define MT6993_SMI_PD_VEN2              MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 16)
#define MT6993_SMI_PD_VEN3              MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 17)
#define MT6993_SMI_PD_VEN_MDP           MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 18)

/* img */
#define MT6993_SMI_PD_ISP_VCORE         MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 19)
#define MT6993_SMI_PD_ISP_MAIN          MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 20)
#define MT6993_SMI_PD_ISP_DIP           MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 21)
#define MT6993_SMI_PD_ISP_WPE_EIS       MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 22)
#define MT6993_SMI_PD_ISP_WPE_TNR       MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 23)
#define MT6993_SMI_PD_ISP_WPE_LITE      MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 24)
#define MT6993_SMI_PD_ISP_TRAW          MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 25)

/* cam*/
#define MT6993_SMI_PD_CAM_VCORE         MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 26)
#define MT6993_SMI_PD_CAM_MAIN          MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 27)
#define MT6993_SMI_PD_CAM_CCU           MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 28)
#define MT6993_SMI_PD_CAM_RAWA          MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 29)
#define MT6993_SMI_PD_CAM_RAWB          MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 30)
#define MT6993_SMI_PD_CAM_RAWC          MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 31)
#define MT6993_SMI_PD_CAM_MRAW          MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 32)

/* mminfra */
#define MT6993_SMI_PD_MMINFRA0          MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 33)
#define MT6993_SMI_PD_MMINFRA1          MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 34)
#define MT6993_SMI_PD_MMINFRA2          MTK_SMI_PD_CTRL(MTK_SMI_HWCCF_DOM_SKIP, 35)

#endif
