/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2024 MediaTek Inc.
 * Author: Anthony Huang <anthony.huang@mediatek.com>
 */

#ifndef __MMDVFS_MT6993_H__
#define __MMDVFS_MT6993_H__

#include <dt-bindings/mmdvfs/mmdvfs-clk-mt6993.h>
#include "mtk-mmdvfs-v5.h"

#define VMMRC_APB_BASE			0x31D00000
#define VDISPRC_APB_BASE		0x31E00000
#define MMRC_APB_BASE			0x31F00000

#define RC_XPU0_MUX_SEL_CLR		0x0110C
#define RC_XPU1_MUX_SEL_CLR		0x111FC
#define RC_XPU2_MUX_SEL_CLR		0x20000
#define RC_XPU3_MUX_SEL_CLR		0x30000
#define RC_XPU9_MUX_SEL_CLR		0x72000
#define RC_XPU10_MUX_SEL_CLR		0x73000
#define RC_XPU11_MUX_SEL_CLR		0x74000
#define RC_XPU12_MUX_SEL_CLR		0x75000

#define RC_XPU0_MUX_SEL			0x10000
#define RC_XPU0_MUX_SEL_PRE		0x100D0

#define RC_CURRENT_LEVEL		0x005C4
#define RC_LEVEL_HEX			0x005F0
#define RC_MUX_SEL_ENABLE		0x10234
#define RC_MUX_SEL_CURR_ENABLE		0x10264

#define RC_DVS_RECORD_0_0		0x113B8
#define RC_DVS_RECORD_0_1		0x113BC
#define RC_DVS_RECORD_0_3		0x113C4
#define RC_DFS_RECORD_0_0		0x115B8
#define RC_RECORD_COUNT			8

//dummy rg
#define VMM_DVFSRC_SIGNAL_MAP0		0x00080

static const u8 vmm_force_user[] = {MMDVFS_FORCE_CAM, MMDVFS_FORCE_VDE};
static const u8 vdisp_force_user[] = {MMDVFS_FORCE_DIS};
static const u8 vcore_force_user[] = {MMDVFS_FORCE_SMI};
static struct mmdvfs_rc mmdvfs_rc[MMDVFS_PWR_NUM] = {
	[MMDVFS_PWR_VMM] = {MMDVFS_PWR_VMM, VMMRC_APB_BASE, 6, vmm_force_user, ARRAY_SIZE(vmm_force_user)},
	[MMDVFS_PWR_VDISP] = {MMDVFS_PWR_VDISP, VDISPRC_APB_BASE, 6, vdisp_force_user, ARRAY_SIZE(vdisp_force_user)},
	[MMDVFS_PWR_VCORE] = {MMDVFS_PWR_VCORE, MMRC_APB_BASE, 7, vcore_force_user, ARRAY_SIZE(vcore_force_user)},
};

static struct mmdvfs_mux mmdvfs_mux[MMDVFS_MUX_NUM] = {
	[MMDVFS_MUX_CAM] = {MMDVFS_MUX_CAM, MMDVFS_PWR_VMM, 0},
	[MMDVFS_MUX_CAMTM] = {MMDVFS_MUX_CAMTM, MMDVFS_PWR_VMM, 1},
	[MMDVFS_MUX_VDE] = {MMDVFS_MUX_VDE, MMDVFS_PWR_VMM, 9},
	[MMDVFS_MUX_IMG] = {MMDVFS_MUX_IMG, MMDVFS_PWR_VMM, 10},
	[MMDVFS_MUX_IPE] = {MMDVFS_MUX_IPE, MMDVFS_PWR_VMM, 11},

	[MMDVFS_MUX_DIS] = {MMDVFS_MUX_DIS, MMDVFS_PWR_VDISP, 0},
	[MMDVFS_MUX_MDP] = {MMDVFS_MUX_MDP, MMDVFS_PWR_VDISP, 1},

	[MMDVFS_MUX_SMI] = {MMDVFS_MUX_SMI, MMDVFS_PWR_VCORE, 0},
	[MMDVFS_MUX_VEN] = {MMDVFS_MUX_VEN, MMDVFS_PWR_VCORE, 1},
	[MMDVFS_MUX_VEN_MDP] = {MMDVFS_MUX_VEN_MDP, MMDVFS_PWR_VCORE, 2},
};

static struct mmdvfs_user mmdvfs_user[MMDVFS_USER_NUM] = {
	[MMDVFS_USER_CAM] = {MMDVFS_USER_CAM, "user-cam", MMDVFS_MUX_CAM, 0, RC_XPU0_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_USER_IMG] = {MMDVFS_USER_IMG, "user-img", MMDVFS_MUX_IMG, 0, RC_XPU0_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_USER_VDEC] = {MMDVFS_USER_VDEC, "user-vdec", MMDVFS_MUX_VDE, 3, RC_XPU3_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_USER_CPC] = {MMDVFS_USER_CPC, "user-cpc", MMDVFS_MUX_CAM, 12, RC_XPU12_MUX_SEL_CLR, MAX_LEVEL},

	[MMDVFS_USER_DISP] = {MMDVFS_USER_DISP, "user-disp", MMDVFS_MUX_DIS, 0, RC_XPU0_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_USER_MML] = {MMDVFS_USER_MML, "user-mml", MMDVFS_MUX_MDP, 0, RC_XPU0_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_USER_DPC] = {MMDVFS_USER_DPC, "user-dpc", MMDVFS_MUX_DIS, 0, RC_XPU12_MUX_SEL_CLR, MAX_LEVEL},

	[MMDVFS_USER_SMI] = {MMDVFS_USER_SMI, "user-smi", MMDVFS_MUX_SMI, 0, RC_XPU0_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_USER_IMG_SMI] = {MMDVFS_USER_IMG_SMI, "user-img-smi", MMDVFS_MUX_SMI, 1, RC_XPU1_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_USER_VCP_SMI] = {MMDVFS_USER_VCP_SMI, "user-vcp-smi", MMDVFS_MUX_SMI, 3, RC_XPU3_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_USER_MDP] = {MMDVFS_USER_MDP, "user-mdp", MMDVFS_MUX_VEN_MDP, 0, RC_XPU0_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_USER_JPEGDEC] = {MMDVFS_USER_JPEGDEC, "user-jpegdec", MMDVFS_MUX_VEN_MDP, 1, RC_XPU1_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_USER_JPEGENC] = {MMDVFS_USER_JPEGENC, "user-jpegenc", MMDVFS_MUX_VEN_MDP, 2, RC_XPU2_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_USER_ADAB] = {MMDVFS_USER_ADAB, "user-adab", MMDVFS_MUX_VEN_MDP, 3, RC_XPU3_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_USER_VENC] = {MMDVFS_USER_VENC, "user-venc", MMDVFS_MUX_VEN, 3, RC_XPU3_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_USER_MMPC] = {MMDVFS_USER_MMPC, "user-mmpc", MMDVFS_MUX_SMI, 12, RC_XPU12_MUX_SEL_CLR, MAX_LEVEL},


	[MMDVFS_AP_CAM] = {MMDVFS_AP_CAM, "mmdvfs-ap-cam", MMDVFS_MUX_CAM, 9, RC_XPU9_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_AP_CAMTM] = {MMDVFS_AP_CAMTM, "mmdvfs-ap-camtm", MMDVFS_MUX_CAMTM, 9, RC_XPU9_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_AP_VDE] = {MMDVFS_AP_VDE, "mmdvfs-ap-vde", MMDVFS_MUX_VDE, 9, RC_XPU9_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_AP_IMG] = {MMDVFS_AP_IMG, "mmdvfs-ap-img", MMDVFS_MUX_IMG, 9, RC_XPU9_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_AP_IPE] = {MMDVFS_AP_IPE, "mmdvfs-ap-ipe", MMDVFS_MUX_IPE, 9, RC_XPU9_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_VCP_CAM] = {MMDVFS_VCP_CAM, "mmdvfs-vcp-cam", MMDVFS_MUX_CAM, 10, RC_XPU10_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_VCP_CAMTM] = {MMDVFS_VCP_CAMTM, "mmdvfs-vcp-camtm", MMDVFS_MUX_CAMTM, 10, RC_XPU10_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_VCP_VDE] = {MMDVFS_VCP_VDE, "mmdvfs-vcp-vde", MMDVFS_MUX_VDE, 10, RC_XPU10_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_VCP_IMG] = {MMDVFS_VCP_IMG, "mmdvfs-vcp-img", MMDVFS_MUX_IMG, 10, RC_XPU10_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_VCP_IPE] = {MMDVFS_VCP_IPE, "mmdvfs-vcp-ipe", MMDVFS_MUX_IPE, 10, RC_XPU10_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_FORCE_CAM] = {MMDVFS_FORCE_CAM, "mmdvfs-force-cam", MMDVFS_MUX_CAM, 10, RC_XPU11_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_FORCE_CAMTM] = {MMDVFS_FORCE_CAMTM, "mmdvfs-force-camtm", MMDVFS_MUX_CAMTM, 11, RC_XPU11_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_FORCE_VDE] = {MMDVFS_FORCE_VDE, "mmdvfs-force-vde", MMDVFS_MUX_VDE, 11, RC_XPU11_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_FORCE_IMG] = {MMDVFS_FORCE_IMG, "mmdvfs-force-img", MMDVFS_MUX_IMG, 11, RC_XPU11_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_FORCE_IPE] = {MMDVFS_FORCE_IPE, "mmdvfs-force-ipe", MMDVFS_MUX_IPE, 11, RC_XPU11_MUX_SEL_CLR, MAX_LEVEL},

	[MMDVFS_AP_DIS] = {MMDVFS_AP_DIS, "mmdvfs-ap-dis", MMDVFS_MUX_DIS, 9, RC_XPU9_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_AP_MML] = {MMDVFS_AP_MML, "mmdvfs-ap-mml", MMDVFS_MUX_MDP, 9, RC_XPU9_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_VCP_DIS] = {MMDVFS_VCP_DIS, "mmdvfs-vcp-dis", MMDVFS_MUX_DIS, 10, RC_XPU10_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_VCP_MML] = {MMDVFS_VCP_MML, "mmdvfs-vcp-mml", MMDVFS_MUX_MDP, 10, RC_XPU10_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_FORCE_DIS] = {MMDVFS_FORCE_DIS, "mmdvfs-force-dis", MMDVFS_MUX_DIS, 11, RC_XPU11_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_FORCE_MML] = {MMDVFS_FORCE_MML, "mmdvfs-force-mml", MMDVFS_MUX_MDP, 11, RC_XPU11_MUX_SEL_CLR, MAX_LEVEL},

	[MMDVFS_AP_SMI] = {MMDVFS_AP_SMI, "mmdvfs-ap-smi", MMDVFS_MUX_SMI, 9, RC_XPU9_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_AP_VEN] = {MMDVFS_AP_VEN, "mmdvfs-ap-ven", MMDVFS_MUX_VEN, 9, RC_XPU9_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_AP_MDP] = {MMDVFS_AP_MDP, "mmdvfs-ap-mdp", MMDVFS_MUX_VEN_MDP, 9, RC_XPU9_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_VCP_SMI] = {MMDVFS_VCP_SMI, "mmdvfs-vcp-smi", MMDVFS_MUX_SMI, 10, RC_XPU10_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_VCP_VEN] = {MMDVFS_VCP_VEN, "mmdvfs-vcp-ven", MMDVFS_MUX_VEN, 10, RC_XPU10_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_VCP_MDP] = {MMDVFS_VCP_MDP, "mmdvfs-vcp-mdp", MMDVFS_MUX_VEN_MDP, 10, RC_XPU10_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_FORCE_SMI] = {MMDVFS_VCP_SMI, "mmdvfs-force-smi", MMDVFS_MUX_SMI, 11, RC_XPU11_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_FORCE_VEN] = {MMDVFS_VCP_VEN, "mmdvfs-force-ven", MMDVFS_MUX_VEN, 11, RC_XPU11_MUX_SEL_CLR, MAX_LEVEL},
	[MMDVFS_FORCE_MDP] = {MMDVFS_VCP_MDP, "mmdvfs-force-mdp", MMDVFS_MUX_VEN_MDP, 11, RC_XPU11_MUX_SEL_CLR, MAX_LEVEL},
};

int mmdvfs_mt6993_dfs_vote_by_xpu(const u8 user_id, const u8 level);
int mmdvfs_mt6993_dvfsrc_rg_dump(void);
int mmdvfs_mt6993_dvfsrc_record_dump(void);
u32 mmdvfs_mt6993_get_mmup_sram_offset(void);

static struct mmdvfs_ops mmdvfs_mt6993_ops = {
	.dfs_vote_by_xpu = mmdvfs_mt6993_dfs_vote_by_xpu,
	.dvfsrc_rg_dump = mmdvfs_mt6993_dvfsrc_rg_dump,
	.dvfsrc_record_dump = mmdvfs_mt6993_dvfsrc_record_dump,
	.get_mmup_sram_offset = mmdvfs_mt6993_get_mmup_sram_offset,
};

static struct mmdvfs_data mmdvfs_data_mt6993 = {
	.rc = mmdvfs_rc,
	.rc_num = MMDVFS_PWR_NUM,
	.mux = mmdvfs_mux,
	.mux_num = MMDVFS_MUX_NUM,
	.user = mmdvfs_user,
	.user_num = MMDVFS_USER_NUM,
	.ops = &mmdvfs_mt6993_ops,
};

#endif
