# SPDX-License-Identifier: GPL-2.0

ifdef CONFIG_GRT_HYPERVISOR
obj-$(CONFIG_MFD_MT6685)	+= hyp-mt6685-core.o
obj-$(CONFIG_MFD_MTK_SPMI_PMIC)	+= hyp-mtk-spmi-pmic.o
endif

obj-$(CONFIG_REGULATOR_MT6362)	+= mt6362-core.o
