load("//build/bazel_mgk_rules:mgk_ddk_ko.bzl", "define_mgk_ddk_ko")
load("//build/kernel/kleaf:kernel.bzl", "ddk_headers")
load("@mgk_info//:kernel_version.bzl","kernel_version",)

package(
    default_visibility = [
        "//visibility:public",
    ],
)

ddk_headers(
    name = "ddk_public_headers",
    includes = ["."],
    hdrs = glob(["**/*.h"]), # export all headers for other modules to use
)

filegroup(
    name = "ddk_kconfigs",
    srcs = glob([
        "**/Kconfig",
    ]),
)

filegroup(
    name = "ddk_src",
    srcs = glob([
        "**/Makefile",
        "**/Kbuild",
        "**/*.c",
        "**/*.h",
    ]),
)

define_mgk_ddk_ko(
    name = "fusb304",
    srcs = [
        "fusb304.c",
        "mux_switch.h",
    ],
    includes = ["."],
    ko_deps = [":mux_switch"],
    copts = [
        "-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/typec/tcpc/inc",
        "-I$(srctree)/drivers/usb/typec",
    ],
)

define_mgk_ddk_ko(
    name = "mux_switch",
    srcs = [
        "mux_switch.c",
        "mux_switch.h",
    ],
    includes = ["."],
    copts = [
        "-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/typec/tcpc/inc",
        "-I$(srctree)/drivers/usb/typec",
    ],
)

define_mgk_ddk_ko(
    name = "ps5169",
    srcs = [
        "ps5169.c",
        "mux_switch.h",
    ],
    includes = ["."],
    ko_deps = [":mux_switch"],
    copts = [
        "-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/typec/tcpc/inc",
        "-I$(srctree)/drivers/usb/typec",
    ],
)

define_mgk_ddk_ko(
    name = "ps5170",
    srcs = [
        "ps5170.c",
        "mux_switch.h",
    ],
    includes = ["."],
    ko_deps = [
        "//kernel_device_modules-{}/drivers/misc/mediatek/typec/mux:mux_switch".format(kernel_version),
        "//kernel_device_modules-{}/drivers/usb/mtu3:mtu3".format(kernel_version),
    ],
    copts = [
        "-I$(DEVICE_MODULES_PATH)/drivers/usb/mtu3/",
        "-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/typec/tcpc/inc",
        "-I$(srctree)/drivers/usb/typec",
    ],
)

define_mgk_ddk_ko(
    name = "ptn36241g",
    srcs = [
        "ptn36241g.c",
        "mux_switch.h",
    ],
    includes = ["."],
    ko_deps = [":mux_switch"],
    copts = [
        "-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/typec/tcpc/inc",
        "-I$(srctree)/drivers/usb/typec",
    ],
)

define_mgk_ddk_ko(
    name = "usb_dp_selector",
    srcs = [
        "usb_dp_selector.c",
        "mux_switch.h",
    ],
    includes = ["."],
    ko_deps = [
    	"//kernel_device_modules-{}/drivers/misc/mediatek/typec/mux:mux_switch".format(kernel_version),
        "//kernel_device_modules-{}/drivers/gpu/drm/mediatek/mediatek_v2:mediatek-drm".format(kernel_version)
    ],
    copts = [
        "-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/typec/tcpc/inc",
        "-I$(srctree)/drivers/usb/typec",
    ],
)