load("//build/bazel_mgk_rules:mgk_ddk_ko.bzl", "define_mgk_ddk_ko")
load("//build/kernel/oplus:oplus_modules_define.bzl", "oplus_ddk_get_target")

package(
    default_visibility = [
        "//visibility:public",
    ],
)

filegroup(
    name = "ddk_kconfigs",
    srcs = glob([
        "**/Kconfig",
        "**/Kconfig.arm",
    ]),
)

filegroup(
    name = "srcs",
    srcs = glob([
        "**/Makefile",
        "**/Kbuild",
        "**/*.c",
        "**/*.h",
    ]),
)

target = oplus_ddk_get_target()

define_mgk_ddk_ko(
    name = "mediatek-cpufreq-hw",
    srcs = [
        "mediatek-cpufreq-hw_main.c",
        "mediatek-cpufreq-hw_fdvfs.c",
        "mediatek-cpufreq-hw_fdvfs.h",
    ],
	hdrs = [
		"mediatek-cpufreq-hw_fdvfs.h",
        ],
        ko_deps = ["//vendor/oplus/kernel/cpu:oplus_bsp_omrg",] if target == "k6993v1_64" else [],
)
