load("//build/bazel_mgk_rules:mgk_ddk_ko.bzl", "define_mgk_ddk_ko")
load("@mgk_info//:kernel_version.bzl", "kernel_version",)

package(
    default_visibility = [
        "//visibility:public",
    ],
)

filegroup(
    name = "ddk_kconfigs",
    srcs = glob([
        "**/Kconfig",
    ]),
)

filegroup(
    name = "ddk_src",
    srcs = glob([
        "**/Makefile",
        "**/Kbuild",
        "**/*.c",
        "**/*.h",
    ]),
)

define_mgk_ddk_ko(
    name = "leds-mt6370-flash",
    srcs = [
        "leds-mt6370-flash.c",
    ],
    includes = ["."],
    ko_deps = [
        "//kernel_device_modules-{}/drivers/misc/mediatek/flashlight:flashlight".format(kernel_version),
    ],
    copts = [
        "-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/flashlight",
        "-I$(DEVICE_MODULES_PATH)/drivers/leds",
        "-I$(DEVICE_MODULES_PATH)/drivers/video/backlight",
        "-I$(srctree)/drivers/power/supply",
    ],
)

define_mgk_ddk_ko(
    name = "leds-mt6379",
    srcs = [
        "leds-mt6379.c",
    ],
    includes = ["."],
    ko_deps = [
        "//kernel_device_modules-{}/drivers/misc/mediatek/flashlight:flashlight".format(kernel_version),
#ifdef OPLUS_FEATURE_CAMERA_COMMON
        "//kernel_device_modules-{}/drivers/soc/oplus/boot:oplus_bsp_boot_projectinfo".format(kernel_version),
#endif /*OPLUS_FEATURE_CAMERA_COMMON*/
    ],
    copts = [
        "-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/flashlight",
        "-I$(DEVICE_MODULES_PATH)/drivers/leds",
        "-I$(DEVICE_MODULES_PATH)/drivers/video/backlight",
        "-I$(srctree)/drivers/power/supply",
    ],
)
