/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2024 MediaTek Inc.
 */

#ifndef __MTK_DCM_INTERNAL_H__
#define __MTK_DCM_INTERNAL_H__

#include <mtk_dcm_common.h>
#include "mt6993_dcm_autogen.h"

/* #define DCM_DEFAULT_ALL_OFF */

/* Note: ENABLE_DCM_IN_LK is used in kernel if DCM is enabled in LK */
#define ENABLE_DCM_IN_LK
#ifdef ENABLE_DCM_IN_LK
#define INIT_DCM_TYPE_BY_K	0
#endif

/* Note: If DCM has states other than DCM_OFF/DCM_ON, define here */
enum {
	ARMCORE_DCM_OFF = DCM_OFF,
	ARMCORE_DCM_MODE1 = DCM_ON,
	ARMCORE_DCM_MODE2 = DCM_ON+1,
};

/* Note: DCM_TYPE enums is used in DCM init & SMC calls */
enum {
	INFRA_DCM = 0,
	MCUSYS_ADB_DCM = 1,
	MCUSYS_APB_DCM = 2,
	MCUSYS_CDB_DCM = 3,
	MCUSYS_CORE_DCM = 4,
	MCUSYS_DBGNW_DCM = 5,
	MCUSYS_DSU_DCM = 6,
	MCUSYS_DSU_BUS_DCM = 7,
	MCUSYS_GIC_DCM = 8,
	MCUSYS_L3C_DCM = 9,
	MCUSYS_MPSYS_BUS_DCM = 10,
	MCUSYS_MPSYS_DBG_DCM = 11,
	MCUSYS_MST_VPS_BUS_DCM = 12,
	MCUSYS_SLV_VC_BUS_DCM = 13,
	MCUSYS_SLV_VPS_BUS_DCM = 14,
	MCUSYS_STALL_DCM = 15,
	MCUSYS_VDNR_DCM = 16,
	PERI_DCM = 17,
	VLP_DCM = 18,
};

enum {
	INFRA_DCM_TYPE = BIT(INFRA_DCM),
	MCUSYS_ADB_DCM_TYPE = BIT(MCUSYS_ADB_DCM),
	MCUSYS_APB_DCM_TYPE = BIT(MCUSYS_APB_DCM),
	MCUSYS_CDB_DCM_TYPE = BIT(MCUSYS_CDB_DCM),
	MCUSYS_CORE_DCM_TYPE = BIT(MCUSYS_CORE_DCM),
	MCUSYS_DBGNW_DCM_TYPE = BIT(MCUSYS_DBGNW_DCM),
	MCUSYS_DSU_DCM_TYPE = BIT(MCUSYS_DSU_DCM),
	MCUSYS_DSU_BUS_DCM_TYPE = BIT(MCUSYS_DSU_BUS_DCM),
	MCUSYS_GIC_DCM_TYPE = BIT(MCUSYS_GIC_DCM),
	MCUSYS_L3C_DCM_TYPE = BIT(MCUSYS_L3C_DCM),
	MCUSYS_MPSYS_BUS_DCM_TYPE = BIT(MCUSYS_MPSYS_BUS_DCM),
	MCUSYS_MPSYS_DBG_DCM_TYPE = BIT(MCUSYS_MPSYS_DBG_DCM),
	MCUSYS_MST_VPS_BUS_DCM_TYPE = BIT(MCUSYS_MST_VPS_BUS_DCM),
	MCUSYS_SLV_VC_BUS_DCM_TYPE = BIT(MCUSYS_SLV_VC_BUS_DCM),
	MCUSYS_SLV_VPS_BUS_DCM_TYPE = BIT(MCUSYS_SLV_VPS_BUS_DCM),
	MCUSYS_STALL_DCM_TYPE = BIT(MCUSYS_STALL_DCM),
	MCUSYS_VDNR_DCM_TYPE = BIT(MCUSYS_VDNR_DCM),
	PERI_DCM_TYPE = BIT(PERI_DCM),
	VLP_DCM_TYPE = BIT(VLP_DCM),
};

int mt_dcm_dts_map(void);
void dcm_array_register(void);

#endif /* #ifndef __MTK_DCM_INTERNAL_H__ */
